DEL="_____________________________________\n********** Message supprimé **********"
T={"What's a skill?":"C'est quoi une compétence ?","Missing Skills":"Compétences disparues","Thanks":"Merci","Can't use skills":"Compétence inutilisable","Can you cast a spell on all?":"Un sort sur tout le monde ?","About Defense":"A propos de la défense","Defense and Evade":"Défense et esquive","Do you know tolerance?":"Vous connaissez la résistance ?","Elements":"Les éléments","Opposing Elements":"Eléments opposés","Armor":"Armures","They're too strong!":"Ils sont trop forts !","Check the Board":"Consulte le Forum","Hey":"Hé","BTW":"Au fait","Necrotic Eye":"Oeil nécrosé","Help":"A l'aide","Deleted":"Supprimé","Girl":"Une fille","Strange Guy":"Type bizarre","Mysterious Room":"Salle mystérieuse","Test Version":"Version de test","Harald Hoerwick":"Harald Hoerwick","Harald Rumor":"Rumeur sur Harald","Then":"Alors","Twilight":"Crépuscule","I can't go in":"Impossible d'entrer","Me too":"Moi aussi","Found!":"Trouvé !","Data Breach":"Données altérées","Alf":"Alf","RED too":"RED aussi","Kinda Worried":"Un peu inquiet","Screen Noise":"Parasites à l'écran","Kinda Scared":"Un peu peur","Kinda scared":"Un peu peur","Something I heard...":"On m'a dit que...","Filter":"Filtre","It's Bob":"C'est Bob","Orca":"Orca","Strange Room":"Salle étrange","Challenge Gob!":"Défi gob !","I'll take you on gob":"Je te prends gob","Is it my turn?":"C'est mon tour ?","Whatever":"Peu importe","Oh?":"Oh ?","GAME OVER!!":"GAME OVER !!","Spiral Edge":"Lame spirale","Thank you very much!":"Merci beaucoup !","Wanted: Katana Info":"Cherche infos katana","then":"alors","Grand Opening!":"Inauguration !","Grand Opening":"Inauguration !","Let me join too!":"Je veux en être !","Miss Gardeniaaaaa":"Mlle Gardeniaaaaa","For Example":"Par exemple","Just a loser":"Juste un nul","Epitaph of Twilight":"L'Epitaphe du Crépuscule","Auction":"Enchères","Revenge Gob!":"Revanche gob !","You're pretty good":"Pas mal du tout","Damn":"Zut","Good gob!":"Bien gob !","Handshakes with you":"Séance de poignées de main","For those who want to join":"Avis aux amateurs","10x!!":"x10 !!","I want to talk with you.":"Faut qu'on parle.","Come on! CC!":"Allez CC !","Yeah right":"Mais oui","That mail...":"Ce mail...","Just watching":"Je regarde juste","Hey!":"Hé !","Queen of Darkness":"Reine des Ténèbres","Can't kill enemy":"Ennemi intuable","I'm Level 60":"Je suis niveau 60","Really?":"Vraiment ?","Maybe...":"Peut-être...","Virus Core":"Virus Core","A guess":"Une hypothèse","Shock Symptoms":"Symptômes de choc","Shock Syndrome":"Symptômes de choc","Curse...":"Malédiction...","I've heard as well":"J'ai entendu ça aussi","Revenge Gob":"Revanche gob","Ha ha ha ha":"Ha ha ha ha","Predictable":"Prévisible","Gah!":"Gah !","Announcing New Service":"Nouveau service","Termination of Service":"Fin du service","Hello":"Bonjour","Location of seeds":"Où sont les graines","Just a Little":"Juste un mot","No Subject":"Sans objet","Thing that might be there":"Ce qui s'y trouve peut-être","This time!!!":"Cette fois !!!","Nothing to Say":"Rien à dire","Last one gob":"La dernière gob","Heh":"Hé","*Sob*":"*Snif*","Aim for Hero of Zeit!":"Devenez Héros de Zeit !","Hero of Zeit Ranking":"Classement des Héros de Zeit","What about this RTCS?":"Et ce RTCS ?","Congratulations!":"Félicitations !","Congratulations":"Félicitations !","Long time!":"Ca fait un bail !","Impressions":"Vos avis","RE: Impressions":"RE: Vos avis","Is it that bad?":"C'est si grave ?","What's Deadly Flash?":"C'est quoi Deadly Flash ?","About Deadly Flash":"A propos de Deadly Flash","Selling pretty well":"Ca se vend bien","Net Phone Box":"Cabine Net","New version AGAIN?!":"ENCORE une version ?!","New OS":"Nouvel OS","Twilight of the New Gods":"Crépuscule des nouveaux dieux","Pluto's Kiss":"Pluto's Kiss","Conspiracy?":"Un complot ?","ALTIMIT 2011":"ALTIMIT 2011","Anti-ALTIMIT unveiled!":"L'anti-ALTIMIT dévoilé !","Little Excited":"Un peu excité","All for Reform":"Pour la réforme","Who cares":"On s'en fiche","Besides that...":"A part ça...","Is it the times?":"C'est l'époque ?","RE: Is it the times?":"RE: C'est l'époque ?","Time passes by":"Le temps passe","Disaster...":"Catastrophe...","Lay Off Day":"Journée sans réseau","What about Tsunamis?":"Et les tsunamis ?","Outcast":"Paria","Smoking Regulation is Common Sense":"La loi antitabac, c'est du bon sens","Somebody's Rich":"Y en a qui sont riches","It's a buy":"A acheter","My Friend":"Mon pote","Names of Sex Shops":"Noms de sex-shops","Look for it yourself":"Cherche toi-même","Have you heard?":"Vous avez entendu ?","RE: Have you heard?":"RE: Vous avez entendu ?","Infinite Diversity Theory":"Théorie de la diversité infinie"}
B={
1:"Je viens de commencer ce jeu. Quand j'ai parlé au marchand, il m'a dit : \"Tu peux utiliser des compétences en t'équipant d'armes et d'armures\", mais c'est quoi une compétence ?",
2:"C'est une attaque qui consomme des SP (Skill Points) en combat. Ca peut blesser les ennemis ou soigner les alliés. On dit pas \"magie\" parce que c'est pas que des sorts, y a aussi les techniques des épéistes.",
3:"En changeant d'arme, j'ai perdu une compétence. Y a un rapport ?",
4:"Les compétences dépendent de l'équipement, pas du personnage. Si tu changes d'équipement, tu ne peux plus utiliser la compétence. Celle que tu as perdue était sûrement sur ton ancienne arme.\n\nEn plus de l'attaque et de la défense, pense aux compétences...",
5:"C'est vrai ?!\nJe savais pas, du coup j'ai vendu mon ancienne arme. Je croyais que j'avais juste gagné un niveau et appris de la magie...\n>_<",
6:"J'ai une compétence que j'arrive pas à utiliser. Pourquoi ? @_@",
7:"1. Tu n'as pas assez de SP.\n2. La cible est hors de portée.\nC'est sûrement l'un ou l'autre.\n\nChaque compétence a une portée : si la cible est trop loin, tu ne peux pas l'utiliser.\n\nLa magie porte loin, mais les attaques sont plus courtes, il faut donc te rapprocher.",
8:"Y a des sorts qu'on peut lancer sur tous les ennemis ou tous les alliés, comme dans les autres RPG ?\n\nSinon, ça va être l'enfer quand il faudra soigner son groupe. X_X",
9:"Ca n'existe pas. Mais les compétences marquées #YPortée#W et #YAttaque de zone#W s'en rapprochent, puisqu'elles touchent une zone.\n\nUn sort d'attaque inflige environ la moitié des dégâts aux ennemis autour de la cible. Bien utilisé, ça revient presque au même. Enfin, à peu près...\n\nLes sorts de soin sur les alliés marchent pareil : tu peux soigner les membres autour de la cible.",
10:"J'ai acheté une armure plus chère, mais elle résiste moins bien aux attaques magiques ennemies. Pourquoi ?",
11:"La #YDéfense magique#W de l'armure est sûrement faible.\n\nIl y a la #YDéfense magique#W et la #YDéfense physique#W. Même avec une Défense physique élevée, si ta Défense magique est faible, tu n'encaisses pas les dégâts magiques.",
12:"Merci Korm !\nJe regardais pas les paramètres des armures... Et y a aussi #YDéfense#W et #YEsquive#W, c'est quoi la différence ?",
13:"Regarde toujours les paramètres de tes objets. C'est sûrement la première chose à faire.\n\nPour Défense et Esquive : la Défense réduit les dégâts reçus, l'Esquive joue sur la fréquence à laquelle tu te fais toucher.",
14:"Vous savez que Suvi Lei et Miu Lei (paralysie et charme) ne s'évitent pas même en montant l'esquive magique, hein ? Si vous montez l'#YEsprit#W contre malédiction, sommeil, confusion et charme, puis le #YCorps#W contre poison, paralysie et lenteur, ça ne réduit pas les dégâts, mais vous serez moins souvent affectés par ces sorts.",
15:"Y a des trucs genre \"élément Feu\" sur les compétences. Les #Yéléments#W, ça change quelque chose ?",
16:"Il existe #Y6 éléments#W pour les compétences, les objets et les monstres.\n\nPour les monstres, une #Yicône#W s'affiche à gauche du nom. Tu as les mêmes icônes dans ton écran de statut.\n\nLes éléments ont des #Yéléments opposés#W : un ennemi de Feu résiste aux attaques de Feu, mais craint les attaques d'Eau. C'est assez simple.",
17:"Donc si on lance Vak Don sur un Gobelin magique, ça fait moins de dégâts qu'un autre sort.\n\nQuels éléments s'opposent ? Je connais feu et eau...\n\nQuelqu'un peut me dire ?",
18:"Voici les éléments opposés :\n(les explications sont de moi, mais je pense pas être loin.)\n\n#YBois#W (puise les nutriments) <-> #YTerre#W (décompose les arbres)\n#YFoudre#W (illumine) <-> #YTénèbres#W (couvrent la lumière)\n#YFeu#W (fait bouillir l'eau) <-> #YEau#W (éteint)",
19:"J'ai une Armure à plates mais j'arrive pas à l'équiper. Les Longues Lances peuvent en porter ? Ce serait nul sinon...",
20:"Désolé, mais t'as vu juste. Les Maîtres des Vagues ne portent que les armures les plus légères. Les Lames Jumelles et les Longues Lances ne peuvent pas porter d'armure lourde. Les autres mettent ce qu'ils veulent.\n\nRegarde le #Ystatut de l'armure#W pour ça. Tout dépend de ta classe, alors autant savoir ce que tu peux équiper.",
21:"Les ennemis sont forts dans absolument toutes les zones où je vais !",
22:"En mettant des mots-clés au hasard, on tombe rarement sur une zone à son niveau. Consulte plus souvent le Forum. D'autres joueurs y postent des mots-clés de zones de bas niveau.",
23:"Tu formes des groupes avant de partir ? La difficulté change selon que t'as des amis ou que tu joues solo. Si t'as pas d'amis... là, je peux rien pour toi.",
24:"Il faut l'ID Joueur des autres joueurs pour former un groupe.\n\nUn ID Joueur, c'est comme une carte de visite. Il permet d'appeler par mail des joueurs qui sont dans d'autres villes ou zones. Ouvre le menu dans une Root Town et choisis le joueur voulu.\n\nPour récolter des ID Joueur, il suffit de se faire des amis.",
25:"J'ai croisé un monstre appelé Oeil nécrosé au dernier étage de #B%2 Spun Bloody Tragedy#W et je me suis fait défoncer.\n\nJe vous préviens juste, préparez-vous bien pour celui-là.",
26:"Mon ami est dans le coma après avoir joué à ce jeu. Il est hospitalisé et ne s'est toujours pas réveillé. Est-ce que ce genre de chose arrive vraiment ? Quelqu'un connaît la raison ? Quelqu'un connaît une autre personne dans le même état ? Comment le sortir du coma ? Les gens qui ont fait le jeu lisent aussi ce forum, non ? S'il vous plaît, donnez-moi une information, n'importe laquelle.\n\nMerci.",
27:DEL,
28:"J'ai vu un personnage étrange dans le donjon de :\n#B%0 Expansive Haunted Sea of Sand#W.\n\nC'était une petite fille aux cheveux longs, mais elle ne ressemblait pas à un joueur. Elle était toute blanche, comme un fantôme, et se déplaçait sans un bruit. Ah, et la musique s'est peut-être arrêtée aussi !\n\nJe me trompe peut-être, mais si quelqu'un la voit, dites-le-moi !",
29:"marin l'a vue aussi.\nfille en robe blanche\npoursuivie par\nun truc avec un\nbâton rouge.\nzone :\n#B%4 Quiet Eternal White Devil#W\n...je crois.\n...mais on peut plus y entrer pourquoi ?",
30:"Moi aussi j'ai vu une fille transparente à :\n#B%1 Dolorous Evil Eyed Widow#W.\nJe me suis approché pour lui parler, elle a secoué la tête et a disparu...",
31:"black knight, tu mens !\ncette zone est protégée.\nj'ai pas pu y aller !",
32:"Moi non plus j'ai pas pu y aller.\n\nJ'aime bien la théorie selon laquelle les zones protégées s'ouvrent si on remplit une condition... genre événement caché.\n\nJe devrais peut-être ouvrir un nouveau sujet là-dessus.",
33:"Y avait un type qui racontait des trucs bizarres à :\n#B%1 Scattering Fossil's Milestone#W.\nIl parlait d'un truc appelé Net Slum. C'est un événement ou quoi ?",
34:"Y avait aussi une salle mystérieuse à :\n#B%2 Resonating False Grasslands#W.\n\nC'est protégé maintenant, mais je l'ai déjà vue et je l'avais noté, donc j'en suis à peu près sûre. Mais c'est quoi, ce truc ? Un machin qu'ils ont oublié d'effacer ?",
35:"Il paraît qu'il y a eu une version de test de \"The World\" avant sa sortie. Quelqu'un y a joué ?",
36:"Un pote était testeur, mais ils ont réduit la période de test de 6 mois à 3. La rumeur disait que quelqu'un était mort pendant le test. Comme si on mourait d'un jeu en ligne.",
37:"Il paraît qu'ils l'ont écourtée parce que le programmeur principal a disparu.",
38:"C'est vrai, un joueur s'est suicidé pendant la période de test, mais ça n'avait rien à voir avec le jeu.",
39:"Y a un jeu appelé \"Fragment\" dans un magazine d'il y a 2 ans.",
40:"C'est celui-là. Le titre et le design des menus ont changé, mais le jeu lui-même a l'air identique. Ah, et certains objets ont été supprimés.",
41:"Quelqu'un a écrit sur un autre site que Fragment s'inspire d'un livre. Quelqu'un sait ?\n\nJe me demande si le jeu est plus facile quand on connaît le livre.",
42:"Je crois que c'est \"l'Epitaphe du Crépuscule\".\n\nC'était plutôt un poème épique qu'un roman, je crois.",
43:"Le jeu s'en inspire jusqu'à quel point ?",
44:"C'est le type qui a disparu. Je sais pas si ça a un rapport avec le changement de titre et le reste.",
45:"Harald était apparemment un lecteur passionné de \"l'Epitaphe du Crépuscule\". La rumeur dit que Fragment en est tiré.",
46:"Le monde va entrer dans le crépuscule ?",
47:"Donc ça va vers la fin de quelque chose ???",
48:"Ca sent pas très bon.",
49:"Et après... ce sera \"si sombre qu'on n'y verra plus rien\" ?\n\nDésolé, j'aime pas le noir.",
50:"J'ai essayé un mot-clé au hasard, mais un message d'avertissement est apparu et j'ai pas pu entrer. Je crois que c'était :\n#B%0 Closed Oblivious Twin Hills#W.\n\nQuelqu'un sait quelque chose ?",
51:"Nous non plus on n'a pas pu y aller. On a appelé le service client, ils disent que c'est de la maintenance.",
52:"Moi j'ai pu y aller !\nIls ont dû finir.",
53:"Trouvé une zone protégée sur le serveur %1 aussi. Quelqu'un sait quand ils auront fini la maintenance ?\n\nVous pourrez sûrement pas entrer, mais c'était :\n#B%1 Nameless Seeker's Prairie#W.",
54:"Je suis allé dans la zone qui était protégée avant. Les graphismes étaient tout bizarres... C'est ça, l'altération des données dont les gens parlaient ?",
55:"Ca fait un moment que je t'ai pas vu.\nUn peu inquiète.\n\nAlf, ça va ?",
56:"Je l'ai pas vu non plus.\nIl s'est peut-être lassé.",
57:"Hmmmmmm...\n\nLa dernière fois que je l'ai vu, il disait avoir trouvé une zone intéressante qu'il explorait, alors je crois pas qu'il se soit lassé du jeu...",
58:"Si tu la connais, pourquoi t'y vas pas ?",
59:"J'y suis allée, mais elle était protégée. >_<\n\nEt il répond pas à mes mails non plus... *snif*",
60:"C'est quoi le mot-clé ? Je veux essayer.",
61:DEL,
62:"Ca fait un moment que j'ai pas vu RED non plus. Il est occupé, peut-être ?\n\n\"The World\" reste très profond pour moi. :)",
63:"Y a des problèmes bizarres depuis la dernière panne de serveur... Qu'est-ce qui se passe ? Certains disent que c'est un virus...",
64:"Mon ordi a planté, je me suis reconnecté, mais l'affichage était complètement bizarre. C'était pas normal. Il y avait des parasites à l'écran et un son vraiment fort. C'est arrivé à tout le monde ou juste à moi ?",
65:"On aurait pas dit un cri ? Je l'ai entendu aussi.\n\nJ'ai cru que mon ordi avait lâché. Plutôt contente de pas être la seule. ;)",
66:"C'est pas genre super grave, ça ?",
67:"Y a eu beaucoup de problèmes ces derniers temps. Surtout avec ce qui s'est passé l'autre jour, et maintenant ça. Ils devraient réagir d'une façon ou d'une autre.",
68:"Donc d'autres PC ont eu ce bruit aussi ? Je me demande si ça vient de la carte son. La mienne était livrée avec.",
69:"C'est pas la question !",
70:"Mon PC a fait ce son aussi.\nEt les parasites pareil.\nJ'ai cru qu'il était cassé...",
71:"Je doute que ce soit un virus.\nJe me demande ce qui va se passer maintenant ? <niark>",
72:"J'ai pas intérêt à devoir reformater mon disque dur. Sinon ça va saigner... !",
73:"Un virus... Je me demande ce qu'ils vont faire.",
74:"J'écris ici pour la première fois. La rumeur selon laquelle on tombe dans le coma après avoir joué à ce jeu, c'est faux, hein ? Je commence à avoir un peu peur...",
75:"Je crois pas que ce soit juste une rumeur. D'après un ami, apparemment des gens ont perdu connaissance.",
76:"Si on peut faire ça avec un jeu, plus besoin d'armes de destruction massive. :-)",
77:"Il paraît qu'il y a eu plein de sirènes après le dernier incident des parasites.",
78:"Vous voulez pas arrêter de raconter ce genre de conneries ?",
79:"Explique pourquoi tu trouves que c'est des conneries... !",
80:"Mon chat a appuyé sur reset avant les parasites, du coup j'ai rien vu. :-(",
81:"Un peu de bon sens, les gens. Ce genre de chose n'arrive pas, c'est tout.",
82:"Le bon sens, c'est surfait.",
83:"Hé, vous êtes hors sujet. ;-)",
84:"PIN : mets une capsule de bouteille sur le bouton reset. Mais tu devrais sûrement remercier ton chat.",
85:"Je trouve que ça commence à devenir dangereux...",
86:"Un pote m'a dit que l'image ressemblait à un virus. Je crois que je vais attendre que ce soit réglé.",
87:"La télé répète juste ce que dit CC, mais sur le net on accuse le jeu pour les gens dans le coma. Je me demande qui dit vrai.\n\nJe crois que je vais attendre un peu, moi aussi.",
88:"Ouais, la presse qui tape toujours sur les sous-cultures est étrangement silencieuse. Ca fait vraiment flipper.\n\nJ'écris qu'ici, moi aussi. :-)",
89:"Je suis en retard, mais j'ai le truc que tu voulais. Je serai dans la zone où tu disais emmener ton ami.\n\nPS : le Mailer a l'air de hoqueter, alors j'écris ici. J'espère que ça pose pas de problème.",
90:"Le premier jour où je me suis connectée, un certain Orca m'a beaucoup aidée. Il est connu, j'imagine ?",
91:"Orca m'a soignée ! ^_^",
92:"Ce sont les Descendants de Fianna qui ont bouclé l'événement The One Sin.",
93:"J'ai jamais vu d'ennemi appelé The One Sin. Il est où ? Et c'est quoi, les \"Descendants de Fianna\" ?",
94:"The One Sin était un monstre à durée limitée, il n'est plus là. C'était une galère à tuer. Descendants de Fianna, c'est le nom donné à Balmung du Ciel Azur et à Orca de la Mer Azur. Ce sont les meilleurs.",
95:"Trop la classe !\nJe vais me faire appeler Celery de la Vitamine. (je rigole)",
96:"Au fait, Orca a dit qu'il y avait une salle étrange à :\n#B%2 Chatting Snaring Twins#W.\nLe serveur Omega est ouvert, alors je vais jeter un oeil.",
97:"Bonjour tout le monde.\nJe suis #YStehoney#W le Gobelin doré gob. Si tu me bats à chat, je te donne une récompense. Mais ça risque pas d'arriver gob. Bonne chance gob.\n\nAh, j'oubliais un truc important gob. Stehoney est à :\n#B%0 Detestable Golden Sunny Demon#W.\n\nViens seul gob !",
98:"Mesdames et Mesgobs !\nStehoney s'est fait battre par un illustre inconnu gob.\n\nSi tu vois de quoi je parle, viens seul à :\n#B%0 Detestable Golden Messenger#W gob.\n\n#YJonue le Glouton#W, l'un des Quatre Rois Gobs, t'affrontera gob !!",
99:"Je pensais pas que t'irais aussi loin gob. Pardon, pardon, je vous croyais stupides gob.\n\nMais maintenant que je suis là, ce sera pas si facile gob. #YZyan l'Indiscret#W, l'un des Quatre Rois Gobs, t'attend à :\n#B%0 Detestable Golden Scent#W gob.\n\nViens seul gob !",
100:"Vous êtes tous des mauviettes. Quel rapport entre l'indiscrétion, la bouffe et tout ça gob.\n\nJe suis #YAlbert le Lève-tôt#W, l'un des Quatre Rois Gobs gob !!! Je suis debout depuis 5 h ! Viens à :\n#B%0 Detestable Golden New Truth#W à 6 h gob !\n\nViens seul gob !",
101:"Oh, noooon. Ils sont tous battus gob ? Et il reste que moi gob ? Hiii ! Ca fait peur gob. Je serai à :\n#B%0 Detestable Golden Gate#W gob.\n\nViens seul gob !",
102:"Je viens de commencer ce jeu. J'ai formé un groupe de 3 avec mes potes, et y avait plein de monstres super forts dans le donjon, et d'un coup, GAME OVER.\n\nLes ennemis sont pas un peu trop forts dans ce jeu ?",
103:"Le niveau des ennemis varie selon la zone, il faut donc trouver celle qui te convient. Zone que je conseille aux débutants :\n#B%0 Discovered Primitive Touchstone#W.\n\nLes monstres y ont des niveaux assez proches, tu ne mourras pas trop vite pour revoir cet affreux écran de GAME OVER. Mais le donjon a 5 étages et ceux du bas sont plutôt costauds, alors ne descends pas jusqu'au fond.\n\nMonte au moins au niveau 5 dans les étages du haut avant de descendre.",
104:"Je ne trouve pas la Lame spirale. Quelqu'un pourrait m'aider, s'il vous plaît ? Je sais que je devrais la chercher moi-même, mais je la veux vraiment.\n\nMerci.",
105:"La Lame spirale est à : #B%0 Raging Passionate Melody#W. Mais le monstre là-bas est plutôt costaud !",
106:"Merci beaucoup ! J'y vais tout de suite ! Souhaitez-moi bonne chance !",
107:"Je cherche un katana. Quelqu'un a des infos sur un katana ? Au fait, je suis niveau 8.\n\nMerci.",
108:"Au niveau 8, je te conseille l'\"Epée Kotetsu\" à :\n#B%0 Hideous Destroyer's Far Thunder#W.",
109:"Merci.\nJ'y vais de ce pas.",
110:"On a enfin créé le fan-club de Mlle Gardenia !!!!!\n\nLes fans de Mlle Gardenia doivent s'inscrire maintenant. Pour nous rejoindre, écrivez ce que vous ressentez pour Mlle Gardenia sur ce forum ! Mlle Gardenia le lira peut-être aussi !!!",
111:"J'adore Mlle Gardenia !\nMLLE GARDENIA EST LA MEILLEURE !!!!!!",
112:"Je l'ai seulement croisée, mais quand j'ai vu Mlle Gardenia pour la première fois, c'était le destin.\n\nLaissez-moi entrer moi aussi-----",
113:"La silencieuse Mlle Gardenia... c'est la plus classe !!",
114:"Mlle Gardenia ferait un bon perso ennemi.",
115:"Yoroshikuu : dégage de ce sujet ! Minable !",
116:"Admin !\nSupprimez le message de Yoroshikuu, s'il vous plaît !",
117:"Dites, si on se retrouvait un de ces jours ?",
118:"Ce serait génial, mais tout le monde habite où ?",
119:"Ah, j'avais oublié qu'on est sur le net.",
120:"En ce moment, la zone préférée de Mlle Gardenia est :\n#B%4 Soft Solitary Tri Pansy#W.\n\nSi on s'y retrouvait ? On croisera peut-être Mlle Gardenia !",
121:"Je suis carrément pour !",
122:"Je viens aussi. (je rigole)",
123:"Ca a l'air d'être à la mode en ce moment, alors j'ouvre un nouveau sujet.\n\n\"L'Epitaphe du Crépuscule\" est une oeuvre en ligne qui se trouvait sur un site de romans. Elle était populaire dans certains cercles, mais le site a fermé, donc je n'ai pas pu rassembler grand-chose.\n\nDes fragments du texte se seraient échangés à prix d'or entre fans inconditionnels.\n\nMais je ne sais pas si c'est vrai. Toute cette histoire est pleine de mystères.\n\nSi quelqu'un sait quelque chose, postez.",
124:"Ca parle de quoi ?",
125:"C'est l'histoire de gens qui cherchent le \"Dragon du Crépuscule\", celui qui sauvera le monde de la destruction par \"l'abominable Vague\". C'est tout ce que je sais.",
126:"Apparemment, l'épitaphe originale était numéro 8 des prix de vente les plus élevés de tous les temps sur un site d'enchères.",
127:"C'était combien ?",
128:"Je me demande si ce serait un best-seller en cas de publication.",
129:"Elle a atteint ce prix justement parce qu'elle a pas été publiée, non ?",
130:"Bonjour tout le monde. Ca fait un gob.\n\nJe me suis fait battre facilement la dernière fois, mais pas cette fois gob !\n\nJ'ai un R gob ! R comme Racing gob ! Bon, je vois déjà comment ça va finir, mais je relève le défi gob. Ah, j'oubliais encore le truc important gob. Stehoney R est à :\n#B%1 Detestable Vengeful Sunny Demon#W gob.\n\nViens seul gob !",
131:"Manger vite, c'est pas bon pour le corps, alors je mâche bien en ce moment gob. Du coup j'ai maigri et j'ai la ligne gob ! Je t'attends à :\n#B%1 Detestable Vengeful Messenger#W gob.\n\nViens seul gob !",
132:"Je trouve que tu te débrouilles bien gob. Mais c'est fini gob ! Pourquoi ?\nParce que je perdrai pas gob !\nJe t'attends à :\n#B%1 Detestable Vengeful Scent#W gob.\n\nViens seul gob !",
133:"C'était trop pour ces gars-là gob. Ils comprennent rien au jeu du chat gob.\n\nJ'ai bien dormi, alors je perdrai pas cette fois gob ! Je t'attends à :\n#B%1 Detestable Vengeful New Truth#W gob.\n\nViens seul gob !",
134:"Vraiment ! Je savais que ça\nallait arriver gob ! C'est pénible gob. Moi aussi je suis occupée, tu sais *soupir* Bon, d'accord gob. Je te défie à :\n#B%1 Detestable Vengeful Gate#W gob.\n\nViens seul gob !",
135:"Le \"Nuke Usagimaru Show\" aura lieu dans le donjon de #B%1 Lightless Distant Dead Lands#W.\n\nAppelez vos amis et passez !\n\nMais pas de huées dans le public, merci ! Pour assister au spectacle, venez seul, sans groupe.",
136:"Hé !\nOn organise une convention d'échanges à l'étage B1 du donjon #B%1 Collapsed Pagan Remains#W.\n\nCeux qui trouvent pas les objets qu'ils cherchent ou qui galèrent à échanger, c'est le moment ! Au lieu de chercher tout seul, échangeons !",
137:"Si vous battez le #YLevel 10 Vine#W au fond du donjon\n#B%1 Bottomless Hopeless Footstep#W,\nvotre niveau sera multiplié par 10 !\n\nVérifiez vous-même si c'est vrai ou pas !",
138:"Mon niveau montait pas et aucun groupe voulait de moi, mais après avoir battu le #YLevel 10 Vine#W dans le donjon\n#B%1 Bottomless Hopeless Footstep#W,\nmon niveau a été multiplié par 10 ! Maintenant je rejoins tous les groupes que je veux !\n\nC'est un rêve devenu réalité !\nMerci infiniment !!!",
139:"J'y croyais pas trop, mais j'ai essayé pour rigoler. Le #YLevel 10 Vine#W était facile à battre.\n\nQuand j'ai ouvert ma fenêtre de statut, mon niveau était vraiment 10 fois plus haut qu'avant !!\n\nEssayez un de ces jours !",
140:"Paraît que t'es plutôt connu en ce moment. Mais je sais que les types comme toi, c'est juste un coup de bol. Si tu penses que j'ai tort, viens seul au donjon :\n#B%1 Stalking Silent Footstep#W.\n\nSeul. Je suis sérieux.",
141:"Vous laissez pas faire par les hackers !\n\nSi je peux faire quelque chose, j'aiderai !",
142:"Franchement, tu peux faire quoi... ?",
143:"Je peux lui faire confiance ? Je crois pas qu'il soit piraté, mais tout ça sonne tellement faux.",
144:"Parlons même pas de ce qui est faux. Ca devient franchement bizarre.",
145:"On s'en fiche. Tu peux jouer, non ?",
146:"Je vais me jeter dans la mêlée. Mais les graphismes sont flingués, c'est un peu triste.",
147:"T'es le Bao que je connais ?\nSinon, désolé.",
148:"Faudrait d'abord me dire quel Sato t'es. Comment je suis censé deviner ?",
149:"Je t'attends au Paradis.",
150:DEL,
151:"J'ai vu un nouvel ennemi dégueu avec des pois partout sur le corps, mais j'arrive pas à le tuer. Si quelqu'un sait, dites-moi !",
152:"Ton niveau est peut-être trop bas.",
153:"C'est plutôt que j'arrive même pas à le toucher. J'étais avec des membres d'éléments différents, donc je crois pas que ce soit une histoire d'élément. C'est peut-être un monstre à durée limitée. Mais y a eu une annonce ?",
154:"Te bats pas contre lui !\nTu vas finir dans le coma !!!!!",
155:"Heureusement que j'ai fui...",
156:"Mais t'as pas envie de le tuer, quand même ?",
157:"Le programme illégal diffusé par les hackers, c'est cet ennemi intuable. Ce qui voudrait dire que CC n'a toujours rien corrigé.",
158:"J'ai eu un truc appelé Virus Core, mais ça s'utilise comment ?",
159:"Si tu l'apportes à un joueur nommé Wiseman, il te l'achète TRES cher.",
160:"Il m'en a acheté un, mais c'était pas tant que ça :-/",
161:"Apparemment il sait lire les gens. Pas de bol.",
162:"Je viens de me faire avoir ?",
163:"Ca expliquerait tout si des hackers avaient lâché une sorte de drogue visuelle.",
164:"C'est peut-être un choc dû aux stimuli lumineux et sonores. On dit qu'il faut éclairer la pièce quand on regarde des dessins animés ou qu'on joue. Je croyais que les avertissements servaient à ça.",
165:"Mais alors on n'entend pas parler de guérisons. Pourquoi c'est si long ?",
166:"Ca vient peut-être du matériel.",
167:"La malédiction du programmeur disparu pèse sur une zone, et les joueurs qui la voient...\nHé hé hé hé hé...\nAaaaaah !!!!",
168:"Quelque part dans #B%2 Fleeting Fallow Chaos#W, on entend le cliquetis d'un clavier... et parfois... un cri...\n\nOuuuuuuuuuuuuuuuuuh...",
169:"Bonjour tout le monde. Ca fait un gob... Pas facile gob. C'est la troisième fois, mais je perdrai pas cette fois gob !\n\nJamais deux sans trois, qu'ils disent gob !\n\nBref gob. J'ai un T maintenant gob. Le T de Stehoney T, c'est pour Turbo gob !\n\nAh, j'oubliais encore le truc important gob. Stehoney T est à #B%2 Detestable Gambler's Sunny Demon#W gob !\nViens seul gob !",
170:"Te crois pas fort juste parce que t'as battu Stehoney T gob ! Vive les poids plume gob !\nRapport poids-puissance de Formule 1 gob ! Je t'attends à :\n#B%2 Detestable Gambler's Messenger#W gob !\n\nViens seul gob !",
171:"C'est mon tour gob. Je savais\nque t'irais jusque-là. Je\nt'attends à :\n#B%2 Detestable Gambler's Scent#W gob !\nViens seul gob !",
172:"T'es devenu très fort gob. Pour tout te dire, je sais pas si je peux gagner contre toi gob... Mais tant que c'est pas fini, c'est pas fini gob !\nJe te défie à :\n#B%2 Detestable Gambler's New Truth#W gob !\n\nViens seul gob !",
173:"Aaaaah !!!\nIls ont tous perdu le sens de l'honneur du Gobelin doré gob !!!\nJe vais te montrer les vrais pouvoirs\nd'un Gobelin doré gob !! Combat à :\n#B%2 Detestable Gambler's Gate#W gob !\n\nViens seul gob !",
174:"J'ai le plaisir de vous annoncer un nouveau service de livraison. Quand vous montez en niveau dans votre donjon préféré, que vous êtes à court d'objets, mais que vous voulez pas rentrer à la Root Town...\n\nOu que vous devez donner *** à xxx, mais que vous avez pas le temps...\n\nVous avez déjà connu ce genre de galère, hein ? C'est là qu'intervient le #YRachel Delivery Service#W !\n\nJe vous apporte l'objet ! Ou je le livre pour vous ! Rapide, pas cher et fiable.\nA votre service.\nPour commander, envoyez-moi un mail avec votre classe et le lieu de rendez-vous.\n\nMerci !",
175:"Désolée, c'était beaucoup trop de boulot.",
176:"Bonjour, je suis Ryoko Terajima. Je n'ai pas encore bien saisi comment avancer dans le jeu, quelqu'un pourrait-il m'aider ? J'attendrai à l'étage B1 de :\n#B%2 Cracked Worst Milestone#W.\nMerci beaucoup.",
177:"Si vous cherchez les graines pour ouvrir la porte, allez à #B%3 Splendid Emerald Nobleman#W.",
178:"Vu un Data Bug à #B%3 Dreaming Moonlit Gravestone#W.",
179:"Cochon courir à #B%3 Muted Starving Dry Sea#W !",
180:"Entendu parler d'un rêve où on se fait attaquer par un Data Bug à #B%3 Rotting Countless Sacrifice#W.",
181:"Tu croyais pas que ça recommencerait gob ? Dommage. Les gobelins sont mauvais perdants gob.\n\nStehoney X, version boostée, t'affrontera gob ! C'est pas une croix gob ! C'est le X de l'alphabet gob ! X gob ! Ca sonne puissant, non gob ?\n\nJ'ai encore failli oublier le plus important gob... Combat à\n#B%3 Detestable Elusive Sunny Demon#W gob !\n\nViens seul gob !",
182:"Dis rien et viens à\n#B%3 Detestable Elusive Messenger#W gob !\n\nC'est le dernier combat gob...\nViens seul gob !",
183:"Dommage gob. Peu importe qui gagne, c'est la dernière gob. Même si je croyais que la dernière était la dernière gob. Bon, bonne chance à tous les deux gob. Je t'attends à :\n#B%3 Detestable Elusive Scent#W gob !\n\nViens seul gob !",
184:"Je sais plus quoi dire à la quatrième fois gob...\n\nAlors c'est la dernière gob ? Viens seul à #B%3 Detestable Elusive New Truth#W gob !\n\nPigé gob ?!",
185:"C'est l'heure des adieux gob. Tu connais l'expression \"tout est bien qui finit bien\" gob ?\n\nLa dernière debout, c'est Martina X gob !\n\nBataille finale à #B%3 Detestable Elusive Gate#W gob !\n\nViens seul gob !",
186:"Tout le monde connaît la #Ystatue de Zeit#W ?\n\nLa statue de Zeit, au fond du donjon, cherche un aventurier à qui décerner le titre honorifique de \"Héros de Zeit\".\n\nLe seul moyen d'obtenir ce titre est d'atteindre la statue de Zeit le plus vite possible !\n\nCeux qui veulent les éloges de la statue de Zeit choisiront #BChronicling#W comme partie A à la Chaos Gate.\n\n#R*#W Cherchez d'abord une zone dont le donjon est proche de l'entrée et compte peu d'étages. Le Héros de Zeit doit aussi savoir dénicher une zone avantageuse.",
187:"Voici les #YHéros de Zeit#W actuels :\n\nPremière place\nTitre :  #YMaster Supreme\n#WTemps :  00:02:12\nBalmung\n\nDeuxième place\nTitre :  #YHyper Falcon\n#WTemps :  00:02:26\nOrca\n\nTroisième place\nTitre :  #YSonic Hawk\n#WTemps :  00:02:54\nSieg\n\nQuatrième place\nTitre :  #YMach Wolf\n#WTemps :  00:03:38\nHighlander\n\nCinquième place\nTitre :  #YFurious Tiger\n#WTemps :  00:04:45\nNOG",
188:"Vous qui avez tenté des donjons de haut niveau, mais dont les monstres sont trop forts !\n\nVous qui avez eu ce que vous vouliez, mais avez oublié l'objet de fuite et vous êtes perdus !\n\nPour tous ceux qui sont dans ce cas, j'ai lancé un service de secours.\n\nContactez-moi en cas de pépin ! On arrive tout de suite pour vous aider !\n\nRachel Rescue Center\nPrésidente : Rachel\nEmployé : #0",
189:"Vous savez, le nouveau système de transport RTCS qui démarre demain ? J'aimerais vraiment savoir si les bouchons appartiendront au passé. L'autre jour, j'ai mis 2 heures pour rentrer en ville depuis Odaiba !",
190:"Quel que soit le système, il faut réduire le nombre de voitures.\n\nNon mais y a trop d'abrutis sur la route ! Qu'on les vire !!",
191:"\"The World\" s'est vendu à plus de 20 millions d'exemplaires dans le monde ! J'ai découvert \"The World\" il y a 2 ans. Je me souviens encore de ce que j'ai ressenti en entrant dans mon premier donjon. Je me demande ce que sont devenus tous ceux qui m'ont aidé au début.",
192:"C'est toi, ce NoNo-là ? Je me souviens de toi. Tu te souviens de moi ? Je suis Flan. On se battait ensemble. On était débutants tous les deux, alors on mourait direct. ^^;",
193:"C'est vrai ?! C'est vraiment toi, Flan ? Waouh, ça fait tellement longtemps !!!! Ca fait une éternité que je t'ai pas vue !\n\nOn se connecte ensemble un de ces jours ? Je t'envoie un mail !",
194:"Waouh, c'est vraiment NoNo. J'attends ton mail ! J'ai pas changé d'adresse !!! ^o^",
195:"Quelqu'un a essayé le nouveau visiocasque qui vient de sortir ? J'hésite à en acheter un, mais... Dites-moi ce que vous en pensez, s'il vous plaît...",
196:"J'en ai déjà un. C'est génial ! Tu le mets pour un jeu d'action et, oh la vache ! C'est l'extase totale, je te jure !\n\nJe le recommande pour tout jeu en vue 3D !! Qu'est-ce que t'attends ?! Fonce l'acheter !!!",
197:"C'est faux ! COMPLETEMENT FAUX !! C'est un produit défectueux ! L'image scintille. Le taux d'erreur de reconnaissance à 0 ou je sais pas quoi, c'est de la publicité mensongère. Tu vas faire une crise si tu l'utilises sur un terrain en 3D. Tu bosses pour eux ou quoi ? Va mourir !",
198:"C'est si grave que ça ? Des crises... ?",
199:"Maux de tête, évanouissements, vomissements ! C'est peut-être même aussi grave que \"Deadly Flash\".",
200:"C'est quoi déjà, Deadly Flash ?\nCa me dit quelque chose...",
201:"C'est le pire virus informatique connu. Il s'est répandu il y a une génération de réseau. L'écran clignote très vite ou un truc comme ça et, euh... y a pas des gens qui en sont morts ?",
202:"C'est un virus parti du Japon en décembre 2003. Il faisait clignoter l'écran, agissait sur l'hypophyse et provoquait des troubles de la conscience. Plusieurs centaines de millions de personnes ont été touchées et sept sont mortes. Ils ont arrêté le type au Japon, et ce fut la première affaire relevant de la loi sur la sécurité du réseau. Quant au type... je crois qu'il a été exécuté.",
203:"Il a été condamné à mort, mais pas encore exécuté, je crois. Il paraît qu'ils vont réviser la loi sur la sécurité du réseau à la prochaine session. Ils vont supprimer la clause sur la peine de mort. A mon avis, ce type ne sera pas exécuté à cause de ça. Dire qu'un sujet sur les \"Neuro Goggles\" a fini ici.",
204:"Le visiocasque descendu sur ce forum a l'air de bien se vendre. On peut pas savoir si c'est bien ou pas sans l'essayer.",
205:"On parle de cabines Net en ce moment, mais avec tous ces portables, qu'est-ce que ça change de rendre les cabines téléphoniques connectables ? Je veux dire, on en a vraiment besoin ? Simple réflexion.",
206:"ALTIMIT sort ENCORE une nouvelle version ! ALTIMIT est pas censé être l'OS parfait ?\n\nAlors pourquoi ils sortent sans arrêt de nouvelles versions ???",
207:"C'est le WNC qui dit qu'ALTIMIT est parfait. Ils font juste les supporters de la société ALTIMIT.\n\nJe me demande si le président Coleman montre son vrai visage, comme ALTIMIT ?!",
208:"La rumeur dit qu'une société développe un OS qui n'est pas ALTIMIT. Si c'est vrai, ce serait pas le premier depuis le \"Crépuscule des nouveaux dieux\" ?!\n\nCa commence à m'exciter.",
209:"C'est quoi déjà ?\nL'Anneau du Nibelung ? Wagner ? Siegfried ?",
210:"On appelle ainsi les trois ans entre Pluto's Kiss et le passage général à ALTIMIT, quand le réseau ordinaire était restreint. Ils voulaient sans doute un nom classe pour la culture du net qui a fleuri à la fin du siècle dernier. Les Européens aiment les explications à la sauce littéraire.",
211:"Pluto's Kiss, c'était grave. Genre compte à rebours avant la fin du monde. L'ordinateur central du Pentagone a été touché, quand même. Des missiles allaient partir, non ? Et c'était pas un gamin de 10 ans, le coupable ?",
212:"Ouais, c'était énorme. J'oublierai jamais le réveillon de Noël 2005 ! Tous les réseaux vitaux à l'arrêt. J'étais gamin, mais j'ai cru à la fin du monde. Pluto's Kiss, c'était bien trouvé comme nom. A cause de ça, l'architecture d'internet a été remise en cause et l'OS de base est passé à ALTIMIT. ALTIMIT était le seul OS épargné, non ?",
213:"Donc ALTIMIT est la seule société à en avoir profité ?\nC'est peut-être un complot.",
214:"Complot ou pas, ALTIMIT en a largement profité. Ils contrôlent presque 100%% du marché. ALTIMIT, l'OS parfait, je sais pas. Il déconne ces derniers temps, et quand je me suis connecté au jeu, il a fait n'importe quoi.\n\nLe WNC ferait bien de se ressaisir.",
215:"Et ils viennent de dévoiler ALTIMIT 2011 !\n\nQuel nom original... ou PAS ! Mais ça va bien à l'hégémonique ALTIMIT. Même le nom sent l'administration, genre WNC. Alors ? Tout le monde va faire la mise à jour ou quoi ?",
216:"ALTIMIT 2011 : je vais observer un peu. Le nouvel OS non-ALTIMIT dont quelqu'un parlait sur ce forum m'intéresse aussi.",
217:"Ils l'ont enfin annoncé !\nUn OS anti-ALTIMIT ! Ca se voit direct que ça vient d'Orange Computer ! La légendaire contre-culture est toujours vivante ! J'aime bien le nom de code Star Child, aussi. Ca me rappelle \"2001, l'Odyssée de l'espace\". Je commence à me lasser d'ALTIMIT, il est peut-être temps de prendre le train en marche...",
218:"Ils sortent le WonderHawk ! Ca m'excite un peu. S'il y a vraiment \"The World\" dessus, ce sera génial.",
219:"\"The World\"... ouais,\nje trouve que ce serait super.\nMais même s'ils l'ont vraiment, comment ils vont caser ce jeu énorme dans des specs de téléphone portable ? Je vais pas trop en attendre !",
220:"Je suis à fond pour la réforme de la loi sur la sécurité du réseau ! On peut pas tuer quelqu'un juste parce qu'il a créé un virus informatique !",
221:"Je suis contre la réforme. On peut pas dire que c'est juste un virus informatique. Des gens en sont morts, quand même ! Pluto's Kiss et Deadly Flash nous ont appris les dangers du cyberterrorisme !\n\nJe suis contre une réforme au rabais !!",
222:"Je crois que ça change rien qu'ils la réforment ou pas. ALTIMIT est un OS parfait, non ? Pas besoin de s'inquiéter du cyberterrorisme ou des virus.",
223:"Tu comprends pas que ce genre de discours maintient ALTIMIT et le WNC au pouvoir ? Jette ce fantasme d'un ALTIMIT parfait !",
224:"Moi je voudrais qu'ils changent le nom de cette loi. \"Loi interdisant tout acte ou rassemblement susceptible d'entraîner un fonctionnement incorrect ou irrégulier du réseau, causant dommages et obstruction\", c'est beauuuuuucoup trop long.",
225:"Un magazine littéraire centenaire... mais je le connaissais pas du tout. C'est l'époque, j'imagine. On trouve aussi les mangas en ligne.",
226:"Mon père écoutait les infos d'un air grave. Apparemment il a fait des études de lettres et voulait devenir écrivain...\n\nC'est une facette de mon père que j'avais jamais vue.",
227:"On dirait le courrier des lecteurs. Un jour dans la vie de ma famille. :-)",
228:"Déjà cinq ans depuis Pluto's Kiss. Le temps file. Je me souviens de l'ouverture du réseau à tous, il y a tout juste trois ans. C'était le réveillon de Noël et le monde entier faisait la fête. Il n'y a plus eu de cyberterrorisme depuis : c'est sûrement grâce au WNC et à ALTIMIT. C'est vraiment un OS parfait, sans faille !!",
229:"Je vous l'ai dit, jetez ce fantasme d'un ALTIMIT parfait ! Vous faites le jeu d'ALTIMIT et du WNC ! On dit que la catastrophe frappe quand on s'y attend le moins ! Si on fait pas gaffe, ce sera l'enfer sur terre.",
230:"ALTIMIT et le WNC qui se prennent pas pour rien, je sais pas, mais elle a un sens, cette Journée sans réseau ? C'est pas juste un truc bidon pour que le WNC se sente mieux ?",
231:"Le Mega Float qu'ils viennent de construire dans la baie de Tokyo, il résiste aux tsunamis, au moins ? La boîte d'un ami va s'y installer. Ils ont beau dire que c'est solide en théorie, je m'inquiète quand même.",
232:"Je sais pas si ça tiendra ou pas, mais une chose est sûre : que tu t'inquiètes ou non, ça change rien.",
233:"La loi antitabac... ce serait nul qu'elle passe. Sérieux, y a déjà des zones non-fumeurs partout, et maintenant ils veulent une loi...\nJe déteste vraiment le gouvernement.",
234:"D'accord avec toi. Si ça continue, le seul endroit où je pourrai fumer sera ma chambre.\n\nAu lieu de tout interdire, j'aimerais qu'ils aillent vers des espaces séparés...",
235:"Je suis à fond pour la loi antitabac ! C'est quoi cette histoire d'espaces séparés ! Ca n'a aucun sens s'il y a des fumeurs autour d'une zone non-fumeurs ! Et qu'est-ce qu'elle a de si génial, la clope ? Ca n'apporte rien du tout ! Je comprends même pas qu'on en vende !",
236:"Le chiffre d'affaires de CC Corporation atteint 2 000 milliards de yens !!!! Y en a qui sont riches. Mais c'est logique, puisqu'ALTIMIT est un produit de CC Corporation. Sauf que son chiffre dépasse celui d'ALTIMIT lui-même : pour ALTIMIT, c'est comme louer un local et se faire racheter par le locataire.",
237:"Qu'ils gagnent de l'argent, d'accord, mais tout cet argent vient de nous, les utilisateurs, non ?\n\nAlors j'aimerais bien qu'ils baissent l'abonnement de \"The World\" !!",
238:"Les portables nouvelle génération arrivent ! Entièrement compatibles ALTIMIT, avec commandes vocales en plus ! Et les accessoires sont top aussi ! Pour moi, c'est clairement à acheter !!!",
239:"Même si les specs sont bonnes, tout est une question de prix. Si le forfait bouge pas et que le téléphone est à 40 000 yens, je dis oui.",
240:"Vous savez qu'ils ont démantelé ce réseau de prostitution en ligne ? Un pote l'utilisait et il s'est fait choper par les flics.\nQuel abruti.",
241:"Ca s'appelle \"Viens quand tu veux\", non ? Les noms de ces trucs sont vraiment ringards. Vous saviez qu'il y a une boutique à Ikebukuro qui s'appelle \"Ze Worlde\" ?",
242:"Hé, je veux aller à \"Ze Worlde\". C'est où exactement ? Côté nord ?",
243:"Ces choses-là, on les cherche soi-même ! Je prie pour ta réussite !",
244:"Ah ben merci.",
245:"La théorie publiée par un prof de je sais plus quelle fac ? On pourrait régler la \"portée\" d'un phénomène futur. C'était peut-être une rumeur du net ? Je crois l'avoir vue quelque part. Y avait des équations aussi...\n\nJe parie que c'est un canular.",
246:"Ouais. C'est pas plutôt connu chez certains ? J'en sais pas grand-chose, mais c'est genre : \"Tous les événements futurs dépendent de la force d'imagination de l'individu.\"",
247:"C'est vrai ? Alors si je prie très\nfort \"je veux être riche\", je deviens riche ?\n\nCa me va. :-D",
248:"Je crois que c'est ce qu'on appelle la \"théorie de la diversité infinie\", la rumeur de ces 2-3 dernières années. J'ai entendu parler de l'équation qui règle le \"rayon d'action\" des événements futurs.\nJ'en veux plus !!",
249:"L'équation de la théorie de la diversité infinie est : \"V = L x (I-F)\". L (lumière) est la lumière intérieure de l'humain (composition pure), et c'est une constante. Si on retire \"l'environnement de l'individu (phénomène)\" de \"l'imagination de l'individu\" et qu'on multiplie par L, on obtient le \"nombre d'événements\" ou le \"champ des possibles\" à venir. Je me demande qui a lancé un truc aussi bidon.",
}
