# Textes systeme de l'executable.
# S : adresse -> liste de lignes (meme nombre que l'original) ou texte (remis en lignes, complete par des lignes vides).
# F : adresse -> champs de 16 caracteres (une seule chaine a largeur fixe).
MC="memory card (8MB) (pour PlayStation%E2)"
def nosave(v): return ["Aucune sauvegarde pour",".hack//%s (chaque volume"%v,"a ses propres sauvegardes)."]
def clear(v): return ["Les données à écraser sont","#R.hack//%s Clear Data#W."%v,"Elles servent au transfert vers","le volume suivant."]
def lose(v): return ["Sauvegarder fera perdre","#R.hack//%s Clear Data#W."%v,"Ecraser les données ?"]
def busy(verb,n): return [verb,"Ne retirez pas la memory card","(8MB) (pour PlayStation%E2)","de la fente MEMORY CARD %d."%n]
ORD=["First","Second","Third","Fourth","Fifth","Sixth","Seventh","Eighth","Ninth","Tenth","Eleventh","Twelfth","Thirteenth","Fourteenth","Fifteenth","Sixteenth","Seventeenth","Eighteenth","Nineteenth","Twentieth"]
ORDFR=["Première","Deuxième","Troisième","Quatrième","Cinquième","Sixième","Septième","Huitième","Neuvième","Dixième","Onzième","Douzième","Treizième","Quatorzième","Quinzième","Seizième","Dix-septième","Dix-huitième","Dix-neuvième","Vingtième"]
GOB={0x371560:0,0x371760:1,0x3717a0:2,0x3717e0:3,0x371820:4,0x371b40:5,0x371b80:6,0x371bd0:7,0x371c10:8,0x371c50:9,0x3720c0:10,0x372110:11,0x372160:12,0x3721b0:13,0x372200:14,0x372760:15,0x3727b0:16,0x372800:17,0x372850:18,0x3728a0:19}
S={
0x34c0b0:["Aucune memory card (8MB) (pour","PlayStation%E2) n'est insérée","dans la fente MEMORY CARD 1."],
0x34c100:["Aucune memory card (8MB) (pour","PlayStation%E2) n'est insérée","dans la fente MEMORY CARD 2."],
0x34c150:["Ceci n'est pas une memory card","(8MB) (pour PlayStation%E2)."],
0x34c190:["Espace libre insuffisant sur","cette memory card (8MB) (pour","PlayStation%E2)."],
0x34c1e0:["Sauvegarder ce jeu demande au","moins 685 Ko."],
0x34c210:["Cette memory card (8MB) (pour","PlayStation%E2) n'est pas formatée."],
0x34c260:["Formater cette memory card (8MB)","(pour PlayStation%E2) ?"],
0x34c2a0:["Choisissez une fente MEMORY CARD."],
0x34c2c0:["Choisissez les données à charger."],
0x34c2e0:["Charger ces données ?"],
0x34c300:busy("Chargement...",1),0x34c360:busy("Chargement...",2),
0x34c3c0:["Données chargées."],0x34c3e0:["Echec du chargement."],
0x34c400:["Choisissez où sauvegarder."],
0x34c420:busy("Sauvegarde...",1),0x34c480:busy("Sauvegarde...",2),
0x34c4e0:["Sauvegardé."],0x34c4f0:["Echec."],
0x34c510:["Créer des données ?"],
0x34c530:["Des données existent déjà.","Les écraser ?"],
0x34c560:busy("Formatage...",1),0x34c5c0:busy("Formatage...",2),
0x34c620:["Memory card (8MB) (pour","PlayStation%E2) formatée."],
0x34c660:["Echec du formatage."],
0x34c680:busy("Création des données.",1),0x34c6f0:busy("Création des données.",2),
0x34c760:["Données créées."],0x34c780:["Echec de la création."],
0x34c7a0:clear("INFECTION"),0x34c820:lose("INFECTION"),0x34c880:clear("MUTATION"),0x34c900:lose("MUTATION"),
0x34c950:clear("OUTBREAK"),0x34c9d0:lose("OUTBREAK"),
0x34ca20:["Les données à écraser sont","#R.hack//QUARANTINE Clear Data#W."],0x34ca70:lose("QUARANTINE"),
0x34cad0:["Aucune sauvegarde pour ce jeu.","Créer une sauvegarde ?"],
0x34cb10:nosave("INFECTION"),0x34cb70:["Créer une sauvegarde pour",".hack//INFECTION ?"],
0x34cba0:nosave("MUTATION"),0x34cc00:["Créer une sauvegarde pour",".hack//MUTATION ?"],
0x34cc30:nosave("OUTBREAK"),0x34cc90:["Créer une sauvegarde pour",".hack//OUTBREAK ?"],
0x34ccc0:nosave("QUARANTINE"),0x34cd20:["Créer une sauvegarde pour",".hack//QUARANTINE ?"],
0x34cd50:["Aucune sauvegarde de",".hack//INFECTION."],0x34cd80:["Aucune sauvegarde de",".hack//MUTATION."],
0x34cdb0:["Aucune sauvegarde de",".hack//OUTBREAK."],0x34cde0:["Aucune sauvegarde de",".hack//QUARANTINE."],
0x34ce10:["Données corrompues."],
0x34ce30:["Aucune memory card (8MB) (pour PlayStation%E2)","insérée. Sauvegarder ce jeu demande au","moins 685 Ko.","Lancer le jeu quand même ?"],
0x34ceb0:["Espace libre insuffisant sur cette memory card","(8MB) (pour PlayStation%E2). Sauvegarder","ce jeu demande au moins 685 Ko.","Lancer le jeu quand même ?"],
# menus
0x36d310:["Choisissez une compétence."],0x36d340:["Choisissez un objet."],0x36d360:["Choisissez un objet clé."],
0x36d390:["Jeter un objet."],0x36d3b0:["Voir le statut."],0x36d3d0:["Changer d'équipement."],
0x36d3f0:"Former un groupe avec les joueurs qui ont donné leur ID Joueur.",
0x36d440:["Rentrer en ville depuis le terrain."],
0x36d470:"Se déconnecter et revenir à l'écran de connexion de The World.",
0x36d4b0:["Infos sur la zone actuelle."],0x36d4d0:["Réglages de la manette."],
0x36d4f0:["Activer/couper les vibrations."],0x36d520:["Ajuster la position de l'écran."],
0x36d540:["Réglages du son."],0x36d560:["Démo du Data Drain : ON/OFF."],
0x36d590:["Changer la langue des voix."],0x36d5b0:["Sous-titres des vidéos : ON/OFF."],
0x36d5e0:"Quitter le jeu et revenir à l'écran-titre.",
0x36d610:["#YQuitter#W et revenir à l'#Yécran-titre#W."],
0x36d640:["#YLes données non sauvées seront perdues.#W","Continuer ?"],
0x36d670:["Vibrations #Yactivées#W."],0x36d690:["Vibrations #Ycoupées#W."],
0x36d6b0:["La démo du Data Drain sera jouée."],0x36d6e0:["La démo du Data Drain ne sera pas","jouée."],
0x36d710:["Réglage actuel : #YA-1#W."],0x36d730:["Réglage actuel : #YA-2#W.","Rotation de caméra inverse de A-1."],
0x36d770:["Réglage actuel : #YB-1#W."],0x36d790:["Réglage actuel : #YB-2#W.","Rotation de caméra inverse de B-1."],
0x36d7d0:["Voix réglées sur #Yanglais#W."],0x36d800:["Voix réglées sur #Yjaponais#W."],
0x36d830:["Sous-titres #Yactivés#W."],0x36d850:["Sous-titres #Ycoupés#W."],
0x36dad0:["Compétences !","Premiers soins !","Affaiblis !","Renforce !","Pas de compétences !","Attaque !","Magie !","Ocarina esprit !","Opération Bataille libre","Opération Bataille unie","Opération Suivez-moi","Opération Récupération","Désigner une cible","Désigner une compétence","Rassemblement","En attente","Tout le monde ici !","Dispersion !","Changer d'équipement"],
0x36dbf0:["Compétences","Stratégie","Membres"],
0x36dc30:"Utiliser compétences physiques et magiques dans ce combat. (Sans compétence : objets.)",
0x36dc90:["Utiliser les compétences de soin.","(Sans compétence : objets.)"],
0x36dcd0:["Affaiblir les ennemis.","(Sans compétence : objets.)"],
0x36dd20:["Renforcer les alliés par des","compétences.","(Sans compétence : objets.)"],
0x36dd70:["Ni compétences ni objets."],
0x36dd90:["Compétences d'attaque physique","dans ce combat."],
0x36ddc0:["Compétences d'attaque magique","dans ce combat.","(Sans compétence : objets.)"],
0x36de10:["Utiliser l'Ocarina esprit."],
0x36de30:["Attaquer l'ennemi le plus proche.","Ni compétences ni objets."],
0x36de70:["Tous sur le même ennemi.","Ni compétences ni objets."],
0x36deb0:["Se regrouper et avancer en","formation. Attaquer si ennemi","proche. Ni compétences ni objets."],
0x36df10:["Ne pas bouger et se soigner."],
0x36df40:["Choisir la cible à attaquer"],0x36df60:["Choisir la compétence à utiliser."],
0x36df80:["Rassembler tout le monde."],0x36dfa0:["Les alliés agissent seuls."],
0x36dfc0:["Choisissez le membre à diriger."],
0x36dff0:["Changer l'équipement du membre","choisi."],
0x36e020:["Aucune compétence utilisable."],
0x36e050:["Impossible de changer d'équipement","pendant une compétence."],
0x36e090:["Changement impossible."],
0x36e100:["Attaque","Magie","Soin","Renforcement","Affaiblissement","Data Drain"],
0x36e170:["Compétences interdites en ville."],0x36e1a0:["Pas assez de SP."],
0x36e1c0:["J'ai promis.","Je ne peux pas l'utiliser.","","Data Drain impossible."],
0x36e200:["Objets","Parchemins","Livres","Trésors","Equipement","Objets clés"],
0x36e270:["Objet d'événement","Nourr. Grunty","Virus Core","Book of 1000"],
0x36e2c0:["Objet inutilisable."],0x36e2e0:["Objet inutilisable en ville."],
0x36e310:["Objet utilisable seulement sur","le terrain."],0x36e340:["Objet utilisable seulement en","donjon."],
0x36e370:["Objet inutilisable ici."],0x36e3a0:["Inutilisable en combat."],
0x36e3d0:["Combien voulez-vous en jeter ?"],0x36e3f8:["Jeter "],
0x36e410:["Objet utilisable seulement","en ville."],0x36e440:["Retournez sur le terrain."],
0x36e490:["Aucune cible à portée."],
0x36e4b0:["Data Drain impossible !","Il faut un #YPROTECT BREAK#W !"],
0x36e4f0:["L'#Yinfection virale#W s'est propagée !","#YData Drain hors de contrôle !#W","#YHP et SP de tous restaurés#W !","#YAttaque physique#W en baisse !","#YDéfense physique#W en baisse !","#YPrécision physique#W en baisse !","#YAttaque magique#W en baisse !","#YDéfense magique#W en baisse !","#YPrécision magique#W en baisse !","#YDuk Lei#W est lancé !","#YSuvi Lei#W est lancé !","#YDek Do#W est lancé !","#YMiu Lei#W est lancé !","#YRanki Lei#W est lancé !","#YMumyn Lei#W est lancé !","#YMaj Lei#W est lancé !","#YDuk Lei#W est lancé sur tous !","#YSuvi Lei#W est lancé sur tous !","#YDek Do#W est lancé sur tous !","#YMiu Lei#W est lancé sur tous !","#YRanki Lei#W est lancé sur tous !","#YMumyn Lei#W est lancé sur tous !","#YMaj Lei#W est lancé sur tous !","#YHP drainés#W à tous !","#YSP drainés#W à tous !","#Y200 EXP#W perdus !","#Y400 EXP#W perdus !","#Y600 EXP#W perdus !","#Y800 EXP#W perdus !","#Y1000 EXP#W perdus !","#YHP et SP de tous à 1#W !"," a disparu !","#RSYSTEM ERROR#W","Mais rien ne s'est passé."],
0x36e860:["!!!!!","Le bracelet brille... !!!"],
0x36e890:["Bracelet amélioré par le Book of 1000 !"],
0x36ec70:["#YDrain Arc#W est désormais utilisable."],
0x36eca0:["Choisissez-le dans #YData Drain#W,","menu des compétences."],
0x36ece0:["Nouvelle amélioration (Book of 1000) !"],
0x36ed10:["#Y2128 Drain#W est désormais utilisable."],
0x36ed40:["Amélioration finale (Book of 1000) !"],
0x36ed70:["#YDrain Heart#W est désormais utilisable."],
0x36eda0:["Effet ajouté en combat","Chance de drainer les HP de","l'adversaire.","Life Drain"],
0x36ee00:["Effet ajouté en combat","Chance de drainer les SP de","l'adversaire.","Skill Drain"],
0x36ee60:["Effet ajouté en combat","Chance d'infliger le double de","dégâts.","Critical Hit"],
0x36eec0:["Effet ajouté en combat","Chance de mettre l'adversaire","à l'agonie.","Death"],
0x36ef20:["Effet ajouté en combat","Chance de ne subir aucun dégât","des attaques ennemies.","No Damage"],
0x36f0e0:["Lame Jumelle","Maître Lame","Lame Lourde","Hache Lourde","Longue Lance","Maître des Vagues"],
0x36f130:["Arme équipée","Touche %6 : statut de l'arme."],
0x36f170:["Armure de tête équipée","Touche %6 : statut de l'armure."],
0x36f1b0:["Armure de corps équipée","Touche %6 : statut de l'armure."],
0x36f1f0:["Armure de mains équipée","Touche %6 : statut de l'armure."],
0x36f230:["Armure de jambes équipée","Touche %6 : statut de l'armure."],
0x36f270:["Puissance d'attaque."],0x36f280:["Défense contre les attaques","adverses."],
0x36f2b0:["Précision des attaques."],0x36f2d0:["Esquive des attaques adverses."],
0x36f2f0:["Puissance magique."],0x36f300:["Défense contre les magies","adverses."],
0x36f330:["Précision magique."],0x36f350:["Esquive des magies adverses."],
0x36f370:["Attaque et défense de","l'élément Terre."],0x36f3a0:["Attaque et défense de","l'élément Eau."],
0x36f3d0:["Attaque et défense de","l'élément Feu."],0x36f400:["Attaque et défense de","l'élément Bois."],
0x36f430:["Attaque et défense de","l'élément Foudre."],0x36f460:["Attaque et défense de","l'élément Ténèbres."],
0x36f490:["Contre malédiction, sommeil,","charme, confusion, magie en baisse."],
0x36f4d0:["Contre poison, paralysie, lenteur,","physique et élément en baisse."],
0x36f510:["Touche %6 : voir le statut."],
0x36f530:["Touche %8 : changer d'équipement.","Touche %6 : voir le statut."],
0x36f570:["Esquive des attaques","adverses."],
0x36f730:["Limite : 40 objets différents.","","Changement d'équipement impossible."],
0x36f780:["Limite : 99 exemplaires de cet","objet.","Changement d'équipement impossible."],
0x36f7d0:["Ajouter au groupe des joueurs dont","vous avez l'ID Joueur."],
0x36f810:["Retirer un membre du groupe."],
0x36f830:["Dissoudre le groupe et quitter","tous les membres."],
0x36f860:["Groupes formables en ville seulement."],
0x36f890:["Commande réservée aux joueurs","en groupe."],
0x36f8d0:["3 membres maximum par groupe.","Retirez un membre avec","\"Remove\" ou \"Disband\"."],
0x36f930:["Aucun membre ne peut rejoindre","votre groupe."],
0x36f960:["Pas de réponse au Flash Mail.","","Joueur absent de The World."],
0x36f9b0:["Ajouter "," au groupe."],
0x36f9d0:["Appel du membre.","Veuillez patienter."],
0x36fa00:["Retirer "," du groupe."],
0x36fa20:["Retrait de tous les membres."],0x36fa40:["Rentrer en ville."],
0x36fa60:["Se déconnecter (écran de connexion)."],
0x36fa90:["Inutilisable en combat."],
0x36fab0:["Obtenu : ","Déjà 99 : ","Limite : 40 objets différents.","Echanger avec un objet actuel ?","Abandonné : ","Jeté : "," : ID Joueur","#W s'ajoute à la liste de mots.","Ajouté aux #Yobjets clés#W.","et obtenu : ","Abandonner ","Jeter ","#W pour "],
0x36fbb0:["Piège déclenché !","Gros dégâts d'#Yexplosion#W !","Jet de #Ygaz toxique#W !","Jet de #Ygaz maudit#W !","Mais rien ne s'est passé."],
0x36fc50:["#YHors classement#W"],0x36fc70:["#YClassé#W"],
0x36fcc0:["Temps actuel : #R"],
0x36fce0:["#YPremière place","#YDeuxième place","#YTroisième place","#YQuatrième place","#YCinquième place","#YDivine Emperor#W.","#YLightning Noble#W.","#YSupersonic Hawk#W.","#YQuicksilver Wolf#W.","#YHigh Speed Tiger#W."],
0x36fe20:"Cette source a quelque chose d'étrange. Je devrais y jeter une arme ou une pièce d'armure.",
0x36fe80:["Vous n'avez rien à jeter."],0x36fea8:["Jeter #G"],0x36fec0:[" #Wa été jeté."],
0x36fee0:["As-tu perdu une Hache d'or ?","Ou bien une Hache d'argent ?"],
0x36ff20:["Une Hache d'or, dis-tu ?"],0x36ff40:["Une Hache d'argent, dis-tu ?"],0x36ff60:["Quoi ?! Ni l'une ni l'autre ?"],
0x36ff90:["Voyons... serait-ce ceci ?"],0x36ffc0:["Entre nous..."],
0x36ffe0:["Avec une arme de ce niveau,","je ne peux rien faire."],
0x370020:["Va dans une zone bien plus dure","et demande à Grandpa."],
0x370060:["En consolation, prends ceci..."],0x370080:["A la prochaine.","Au revoir..."],
0x3700a0:["Est-ce une Hache d'or, ton arme ?","Ou bien une Hache d'argent ?"],
0x3700e0:["Avec une arme de ce niveau,","je ne peux rien faire."],
0x370120:["Il te faudra aller à une source","d'un serveur plus fort."],
0x370160:["A plus dans le bus..."],
0x370180:["Super !","Cet objet est bien meilleur","qu'avant."],
0x3701c0:["On dirait qu'il s'est changé","en quelque chose de mieux."],
0x3701f0:["Hmm... cet objet s'est","affaibli ?"],
0x370300:["Les Grunties","La nourriture","L'élevage"],
0x3703b0:["Pas de nourriture."],0x3703c8:["Donner "],
0x370400:["Choisissez un objet dans la liste","présentée par le joueur."],
0x370450:["Choisissez vos objets à échanger.","L'échange est possible si le mot","\"Approve\" s'allume."],
0x3704a0:["Echanger à ces conditions ?"],0x3704d0:["Aucun objet à échanger."],
0x3704f0:["Echange impossible : vous dépasseriez","la limite de 40 types d'objets."],
0x370540:["Echange impossible : vous","dépasseriez la limite de 99","objets du même type."],
0x3705a0:["Choisissez la quantité."],0x3705c0:["Donner "],0x3705d0:["Aucun objet à donner."],
0x3705f0:[" a reçu "],0x370600:[" a équipé "],0x370610:[" utilise "],
0x3706a0:["Combien voulez-vous en vendre ?"],0x3706c0:["Vente : "," #Wpour "," GP."],
0x3706e0:["Combien voulez-vous en acheter ?"],0x370700:["Achat : "," #Wpour "," GP."],
0x370720:["Pas assez d'argent."],
0x370740:["Achat impossible : vous","dépasseriez la limite de 40","types d'objets."],
0x370790:["Achat impossible : vous","dépasseriez la limite de 99","objets du même type."],
0x3707f0:["Combien voulez-vous en déposer ?"],0x370810:["Dépôt : "],
0x370820:["Le dépôt est limité à 99 types","d'objets."],0x370850:["Vous avez déjà déposé 99","exemplaires de cet objet."],
0x370880:["Combien voulez-vous en retirer ?"],0x3708b0:["Retrait : "],
0x3708c0:["Retrait impossible : vous","dépasseriez la limite de 40","types d'objets."],
0x370910:["Retrait impossible : vous","dépasseriez la limite de 99","objets du même type."],
0x3709d0:["Vous obtenez le Data Flag de",".hack//INFECTION.","Sauvegarder ?"],
0x370a10:["Vous obtenez le Data Flag de",".hack//???.","Sauvegarder ?"],
0x370a50:["Former un mot-clé au hasard."],0x370a80:["Saisir un mot-clé à la main."],
0x370aa0:["Listes de mots tirés d'événements."],
0x370ac0:["Historique des mots-clés saisis","au hasard ou à la main."],
0x370b00:["Aller dans une autre ville (serveur)."],
0x370b30:["Choisissez le mot de la partie A."],0x370b50:["Choisissez le mot de la partie B."],0x370b70:["Choisissez le mot de la partie C."],
0x370b90:["#RPROTEGEE#W","Téléportation impossible ici."],
0x370bc0:["Aller à"],
0x370bd0:["Téléporter","Annuler","Niv. de combat :","Elément :","Terre","Eau","Feu","Bois","Foudre","Ténèbres"],
0x370c80:["Type de terrain"],0x370ca0:["Relief"],0x370cc0:["Niveau de zone"],0x370ce8:["Portails"],
0x370cf8:["Part. A"],0x370d00:["Part. B"],0x370d08:["Part. C"],
0x370d10:[" Serveur %0"," Serveur %4"," Serveur %1"," Serveur %2"," Serveur %3"],
0x370d50:["Aller à Mac Anu, la cité aquatique,","Root Town du serveur %0."],
0x370d90:["Aller à Dun Loireag, la cité des","hauteurs, Root Town du serveur %4."],
0x370dd0:["Aller à Carmina Gadelica, la cité","savante, Root Town du serveur %1."],
0x370e10:["Aller à Fort Ouph, la cité","aérienne, Root Town du serveur %2."],
0x370e50:["Aller à Lia Fail, la cité des","reliques, Root Town du serveur %3."],
0x370ef0:["Aucun serveur enregistré."],0x370f20:["Aucune zone enregistrée."],
0x370f40:["Inutilisable une fois mort."],0x370f60:["Les fées examinent la carte."],
0x370f90:["augmente de "," diminue de ","Attaque physique ","Défense physique ","Précision physique ","Esquive physique ","Attaque magique ","Défense magique ","Précision magique ","Esquive magique ","Elément Terre ","Elément Eau ","Elément Feu ","Elément Bois ","Elément Foudre ","Elément Ténèbres ","HP ","SP "],
0x3710a0:["Piège désamorcé."],
0x3710c0:["Aucun Grunty à appeler sur","ce serveur."],
0x371100:["#RINSTALLATION ERROR#W","Ecrasement des données du","personnage interdit."],
0x371140:["J'échange "," #Wcontre "],
0x371158:[": Parler"],0x371160:[": Attaquer"],0x371170:[": Examiner"],0x371180:[": Détruire"],
0x3711a0:["Nouveau mail !"],
0x3711c0:["Rés. physique","Rés. magique","Rés. Terre","Rés. Eau","Rés. Feu","Rés. Bois","Rés. Foudre","Rés. Ténèbres"],
# descriptions de zones
0x371230:["Zone indiquée par Orca.","Pour débutants."],
0x371260:["Zone indiquée par BlackRose.","Très louche..."],
0x3712a0:"Zone du mail de Roy@BANDAI. Percez le mystère de la flotte aérienne !",
0x371300:"Zone postée sur le Forum, où la silhouette d'une fille a été vue.",
0x371350:["Zone du mail de Mia.","Elle a dit de venir seul."],
0x371380:"Zone dite \"zone protégée\" d'après un message du Forum.",
0x3713d0:["Zone où Elk t'a invité."],
0x3713f0:["Zone indiquée par Mistral.","Réputée dangereuse."],
0x371430:"Zone révélée par l'enquête de BlackRose.",
0x371460:["Zone indiquée par Bob."],0x371480:["Zone indiquée par Linda."],
0x3714a0:"Rendez-vous fixé par BlackRose avec l'amie d'Alf, le joueur disparu.",
0x371500:"Zone où l'ami de Meg a disparu. Effacée du Forum, mais Helba te l'a envoyée.",
0x3715a0:"Zone pour débutants indiquée sur le Forum.",
0x3715d0:"Zone où Piros te demande d'être témoin de sa victoire sur le monstre.",
0x371620:"Zone où est caché l'objet qui guérira Piros.",
0x371660:"D'après le Forum, l'Epée Kotetsu se trouve ici.",
0x3716a0:"Mot-clé du message du fan-club de Gardenia.",
0x3716d0:["Zone où Gardenia t'a invité."],
0x3716f0:"D'après le Forum, la Lame spirale se trouve ici.",
0x371730:["Un objet y est peut-être caché."],
0x371860:"Mot-clé d'un mail anonyme. Des infos sur les joueurs dans le coma, peut-être...",
0x3718c0:"Nouvelle zone protégée postée sur le Forum.",
0x3718f0:"Zone que Lios demande d'examiner. La pollution des données s'y propage.",
0x371940:"Zone du mail d'Aura. Est-ce là qu'elle se trouve... ?",
0x371980:"Zone du mail de Linda. Balmung y est allé sur les traces d'Orca.",
0x3719e0:"D'après 01, Wiseman, qui connaît l'Epitaphe du Crépuscule, est dans cette zone.",
0x371a40:"Zone où est cachée la Lame étincelle. A échanger avec Wiseman contre des infos.",
0x371aa0:"Zone postée sur le Forum, où une silhouette mystérieuse a été vue.",
0x371af0:"Zone révélée par Plaird, une IA errante. Le Net Slum semble être ici...",
0x371c90:"Zone du sujet du Forum. Le Nuke Usagimaru Show s'y tiendra.",
0x371ce0:"Zone où Marlo a dit à #0 de venir seul.",
0x371d10:"D'après le Forum, la convention d'échanges se tient au B1 du donjon.",
0x371d70:"Zone du mail de Piros. Le chat qui l'a fait souffrir est ici.",
0x371dc0:["Zone où Gardenia t'a invité"],
0x371de0:"Zone où Sanjuro t'a invité. On y trouve de bonnes épées.",
0x371e20:"D'après le Forum, le Level 10 Bind est ici... Ca sent le canular...",
0x371e80:["Zone où Moonstone t'a invité"],
0x371ea0:"D'après le Forum, une zone sur laquelle Orca enquêtait.",
0x371ee0:"Zone désignée par Helba. Pour la rencontrer, il faut venir seul.",
0x371f20:"D'après Helba, les données de cette zone enflent. L'une des 8 Phases, peut-être.",
0x371f90:"Zone que Lios demande d'examiner. La pollution des données progresse.",
0x371fe0:"Obtenir le Virus Core sans Data Drain pour avoir l'aide de Lios.",
0x372030:"Dite \"zone maudite\" d'après un message du Forum.",
0x372070:"Zone postée sur le Forum, où une salle mystérieuse a été vue.",
0x372250:["Zone où Nuke t'a invité."],
0x372270:"Mot-clé d'un message du Forum. L'Oeil nécrosé que cherche Marlo serait ici.",
0x3722d0:"Zone du mail de livraison de Rachel. Le client attend dans le donjon.",
0x372320:"Zone indiquée par Piros. Lancer un sort dans le donjon révèle un objet rare...",
0x372380:"Zone où Sanjuro t'a invité. Le Donjon du Quiz du Maître d'épée s'y trouve.",
0x3723d0:"Zone où Moonstone t'a invité. Le Moon Knife y est caché.",
0x372410:"Mot-clé d'un message du Forum. Ryoko Terajima y attend de l'aide.",
0x372460:"Zone du mail de Roy@BANDAI. Percez le mystère de la créature flottante !",
0x3724c0:"Zone que Lios demande d'examiner.",
0x3724f0:"Zone indiquée par Spiritas, habitant du Net Slum. Une salle mystérieuse s'y trouve.",
0x372550:"Zone choisie par Wiseman pour vaincre la \"Vague\" avec le programme vaccin.",
0x3725b0:"Zone indiquée par Jinn, habitant du Net Slum.",
0x3725f0:"Zone indiquée par Sconk, habitant du Net Slum.",
0x372630:"Zone indiquée par Culhwh, habitant du Net Slum.",
0x372670:"Zone indiquée par Dorin, habitant du Net Slum.",
0x3726b0:"D'après Helba, un brusque afflux de données est confirmé dans cette zone.",
0x372700:"Zone indiquée par Tartarga, du Net Slum. Harald, l'IA errante, y est allé.",
0x3728f0:["Zone où Moonstone t'a invité."],0x372920:["Zone où Marlo t'a invité."],
0x372940:"Zone d'une mission du Rachel Rescue Service.",
0x372980:"Zone où Piros t'invite à vaincre un joueur malfaisant.",
0x3729c0:["Mot-clé du Forum.","Bear et Mimiru s'y retrouvent."],
0x372a00:["Mot-clé du Forum.","Un bâton rouge y a été vu."],
0x372a40:["Mot-clé du Forum.","Un joueur y appelle Subaru.","Viendra-t-elle ?"],
0x372a90:"Zone où Ryoko Terajima t'invite. Il s'y trouve un objet intéressant.",
0x372ad0:"Zone où t'invitent BlackRose et Ryoko Terajima. J'ai un mauvais pressentiment...",
0x372b30:"Mot-clé du mail d'Aura. Une nouvelle vie va naître dans cette zone.",
0x372ba0:["C'est illisible."],
}
for a,i in GOB.items(): S[a]=["Zone du défi de chat lancé","par le Gobelin doré.",ORDFR[i]+" manche"]
for i,r in enumerate(["I","II","III","IV","V","VI","VII","VIII"]):
    S[0x36e8c0+[0,0x70,0xe0,0x160,0x1d0,0x240,0x2b0,0x330][i]]=["#GLivre Ryu %s#W est généré"%r,"par le bracelet."]
    S[0x36e8f0+[0,0x70,0xf0,0x160,0x1d0,0x240,0x2c0,0x340][i]]=["#GLivre Ryu %s#W s'ajoute à la"%r,"liste des #Yobjets clés#W."]
F={
0x36d8d0:["Volume général","Volume BGM","Volume SE","Sortie","Mono","Stéréo"],
0x36d940:["Menu perso","Menu chat","Action/Valider","Annuler","Options","Mode carte"],
0x36d9b0:["Zoom avant","Zoom arrière","Rotation","Changer de vue","Réinitialiser"],
0x36da10:["Déplacement","Choix du menu"],
0x36da40:["OK","Annuler"],
0x36daa0:["Anglais","Japonais"],
0x36ef90:["Niveau","EXP","Argent","Classe"],
0x36efe0:["Physique :","Magique :","Attaque","Défense","Précision","Esquive","Autres :"],
0x36f060:["Compétences :"],0x36f080:["Effets ajoutés:"],0x36f0a0:["Equipement :"],0x36f0c0:["Objets"],
0x36f5a0:["Equipé","Arme :","Disponible","Arme :"],
0x36f5f0:["Equipé","Tête :","Disponible","Tête :"],
0x36f640:["Equipé","Corps :","Disponible","Corps :"],
0x36f690:["Equipé","Mains :","Disponible","Mains :"],
0x36f6e0:["Equipé","Jambes :","Disponible","Jambes :"],
0x370220:["Aucune","Hache d'or","Hache d'argent"],
0x370340:["Taille","Odeur","Rébellion","Brutalité","Intelligence","Pureté"],
0x370620:["Argent","En poche","Déposer","Retirer","En dépôt","Donner","Jeter"],
0x370970:["fente 1","fente 2","Vide","Données","MEMORY CARD"],
0x370ea0:["Rotation","Ajouter/Retirer","Valider","Annuler"],
}
