# Dialogues de l'executable. Sans "\n" : remis en lignes automatiquement (3 lignes max). Avec "\n" : lignes imposees.
D={
0x350ce0:"C'était quoi, ça ?! T'as vu ?",
0x350d10:"Ouais. Ce truc la poursuivait ?",
0x350d40:"Ouais, mais... un truc pareil à ce niveau ?",
0x350d80:"Ou alors... la rumeur était vraie ?",
0x350db0:"Prends ça...",
0x350dc0:"Hein ?",
0x350dd0:"Je t'en prie, prends-le.\nIl n'y a plus de temps !\nJe t'en prie !",
0x350e00:"C'est quoi ?",
0x350e10:"Une grande force...",
0x350e30:"Son pouvoir peut apporter le salut ou la destruction, au gré de celui qui s'en sert.",
0x350e90:"Tu es...",
0x350ea0:"Il arrive !",
0x350eb0:"Fuis ! Il va te tuer !",
0x350ed0:"C'est quoi ce délire... ?\nC'est quoi ce truc...",
0x350f00:"Y a un problème...\nRien ne marche !",
0x350f50:"Ca ne devait pas se passer ainsi. Je suis... désolé...",
0x350f90:"Tire-toi d'ici !",
0x350fc0:"Quoi ? Qu'est-ce qu'il y a ?",
0x350fe0:"T'as un truc à dire ?",
0x351010:"Ah, j'ai pigé. T'es un débutant, c'est ça ? J'aurais dû m'en douter. Alors, oui ou non ?",
0x351070:"Allez, sois pas timide, tu peux me le dire.",
0x3510a0:"Ecoute, au cas où tu le saurais pas, t'es très impoli, là.",
0x3510f0:"Ca se fait pas de fixer quelqu'un comme ça.",
0x351120:"Faut que tu comprennes que c'est comme dans la vraie vie. Tu piges pas ?",
0x351180:"Dernière chance... C'est quoi ton problème, hein ?",
0x3511c0:"Allez ! Tu vas dire quelque chose, à la fin !",
0x3511f0:"C'est quoi ce truc ?",
0x351208:"Reste en arrière !",
0x351218:"Oh non... !",
0x351230:"C'est tout ? Plutôt faiblard, non ?",
0x351260:"Tiens donc. T'avais même pas besoin de mon aide, en fait ?",
0x3512b0:"Cette statue...",
0x3512d0:"Elle a l'air si... si triste.",
0x3512f0:"Skeith, Innis, Magus...\nJe n'arrive pas à lire le reste.\nL'inscription est effacée.",
0x351340:"Au fait, euh...",
0x351358:"Hmm ?",
0x351360:"Tu dois bien voir que moi aussi, je débute ?",
0x351390:"Mmm... ouais.",
0x3513a0:"Ca devait se voir, vu comment j'ai réagi tout à l'heure.",
0x3513e0:"Mais t'es resté avec moi. Tu sais quoi ? T'es plus sympa que je pensais.",
0x351430:"Tu vois, je... j'essaie de trouver...",
0x351460:"Hé ! Qu'est-ce que tu fais ?!",
0x351480:"Quoi ?! Et toi alors, hein ?",
0x3514a0:"Pas le temps d'expliquer. C'est trop dangereux ici.",
0x3514d0:"Quoi... ?",
0x3514e0:"Je te dis de sortir !",
0x351500:"Partez d'ici sur-le-champ !",
0x351520:"Celui-ci aussi...",
0x351540:"Mais comment ? Dis-moi ce qui se passe ! Ce truc aurait dû... il aurait dû être mort !!",
0x3515a0:"Pourquoi il brille comme ça ?\nCa fout les jetons !\nC'est pas possible ?!",
0x3515f0:"C'est un bug dû à un virus. Le virus réécrit les données.",
0x351640:"Ses HP sont... infinis.",
0x351670:"C'est celui-là... !",
0x351690:"Fuis pendant que je gagne du temps.",
0x3516c0:"A cause de ce truc...",
0x3516e0:"Je vais te tuer !",
0x351700:"Non ! Tu ne peux pas le tuer ! Laisse-le ou c'est toi qui mourras !",
0x351750:"\n    #YVirus Core M#W obtenu.",
0x351780:"C'était comme... comme la fois où Orca...",
0x3517d0:"Cette compétence... Je comprends, à présent.",
0x351800:"Tu es comme le virus. Dire que j'ai été sauvé par quelqu'un de ton espèce !",
0x351850:"Non ! C'est pas... je sais même pas ce que...",
0x351880:"Ne me mens pas !",
0x3518a0:"Ces derniers temps, bien des lieux de \"The World\" ont été endommagés par un virus.",
0x3518f0:"Ceux qui répandent sciemment le virus et détruisent ce monde pour s'amuser, ceux-là...",
0x351950:"Ils n'auront droit à aucune pitié !",
0x351970:"Non ! C'est pas moi ! Je...",
0x351990:"Je ne pensais pas trouver le responsable aussi vite...",
0x3519d0:"Dégaine ! Dégaine ton épée. Maintenant !",
0x3519f0:"Non ! Y a aucune raison de faire ça !",
0x351a20:"Moi, j'en ai une.",
0x351a40:"Non ! Je veux pas me battre !\nJe... je...",
0x351a70:"C'est quoi ton problème, à la fin !",
0x351a90:"En voilà une façon de parler à celui qui vient de te sauver la vie !",
0x351ad8:"Mm !\nHmm...",
0x351af0:"Je ne te fais toujours pas confiance. Il me faut seulement le temps d'y réfléchir.",
0x351b40:"Mais si je découvre que tu es bel et bien des leurs...",
0x351b80:"Je te tuerai.",
0x351ba0:"Plutôt puéril pour Balmung du Ciel Azur, le Descendant de Fianna...",
0x351c00:"Je ne parle pas aux hackers !",
0x351c20:"Ce garçon... C'est un ami de ton partenaire.",
0x351c50:"Orca ?",
0x351c70:"J'ai trouvé une super zone pleine d'Herbe parfumée. Tu viens ?",
0x351cb8:"Ouais, bien sûr !",
0x351cd0:"OK. Préparons-nous, alors.",
0x351cf0:"Ah, Mia ?",
0x351d00:"Excuse-moi.",
0x351d10:"Toi. Oui, toi !",
0x351d30:"Quel bracelet singulier !",
0x351d50:"Je peux regarder ?",
0x351d70:"Tu le vois ?",
0x351d90:"Oui, bien sûr ! Tu veux dire que toi, tu ne vois pas ce joli bracelet ?",
0x351de0:"Même sans le voir, du moment qu'on sait qu'il est là, c'est comme si on le voyait, non ?",
0x351e50:"Un bracelet ? Dis, de quoi tu parles ? Je vois aucun bracelet, Mia.",
0x351ea0:"Bon, merci beaucoup de m'avoir laissé regarder ton bracelet.",
0x351ee0:"J'ai le sentiment qu'on se reverra.",
0x351f30:"Allez, à la prochaine.",
0x351f50:"Attends, Mia ! Et l'Herbe parfumée ?",
0x351f80:"Aura ?",
0x351f90:"Je vois que tu as reçu le mail que je t'ai envoyé... pourtant...",
0x351fd0:"Mais il est trop tard.",
0x351ff0:"Attends ! J'ai quelque chose à te demander.",
0x352028:"Noooooon !!",
0x352050:"Le Caché...",
0x352070:"Nous nous retrouvons. Il semble donc que tu connaisses Orca.",
0x3520b0:"Si je le connais ? C'est lui qui m'a invité à venir jouer à ce jeu.",
0x352100:"Alors je dois te le demander. Je n'ai pas pu le joindre depuis cet événement.",
0x352150:"Qu'est-il advenu de lui ?",
0x352170:"Tu me fais confiance ?",
0x352190:"Cela dépendra de ce que tu diras.",
0x3521b0:"#0 raconta comment Orca avait subi le Data Drain.",
0x3521e0:"Je vois. J'ignore quelle part de vérité il y a là-dedans.",
0x352220:"Mais ne t'avise pas d'oublier...",
0x352240:"Le pouvoir de ce bracelet est le même que celui... qui a plongé Orca dans le coma !",
0x352290:"Ouais, je sais. Pas besoin de me le rappeler.",
0x3522d0:"Tu n'as pas le temps de déprimer.",
0x352300:"Qui es-tu ?",
0x352310:"Une amie, ou peut-être une ennemie ?",
0x352330:"Une fouineuse porteuse d'un avertissement.",
0x352350:"C'est toi qui as envoyé ce mail ?\nHelba ?",
0x352370:"Cela mis à part, je dois te prévenir. Méfie-toi de Lios.",
0x3523a0:"Lios ?",
0x3523b0:"Lios est du côté du Système. Avec ce bracelet, on te traitera comme un virus.",
0x352410:"Et il te faudra ceci.",
0x352430:"\n     #YVirus Core O#W obtenu.",
0x352460:"Tu te demandes \"Comment elle sait ?\", pas vrai ?",
0x352490:"Ce n'est pas si dur à imaginer. Je te l'ai dit.",
0x3524c0:"On t'observe en permanence.",
0x3524f0:"Attends. Pourquoi tu m'aides ?",
0x352520:"T'aider ?",
0x352530:"Qui sait. C'est peut-être toi qui m'aides. Prends soin de toi...",
0x352570:"...mon petit.",
0x356c80:"Je vais d'abord lire mes mails.",
0x356ca0:"OK, l'inscription est faite. Maintenant, un nom...",
0x356ce0:"Yasuhiko doit déjà m'attendre là-bas. Faut que je me dépêche.",
0x356d30:"Hé. T'as réussi à venir !",
0x356d60:"Hé, c'est moi. Orca, le Maître Lame.",
0x356d90:"Waouh ! Tu ressembles pas du tout au vrai Yasuhiko. Rien à voir avec toi en vrai.",
0x356de0:"Hé, dans ce jeu je suis Orca ! Peu importe qui je suis en vrai. Je suis assez connu ici.",
0x356e40:"Quoi... ?",
0x356e50:"Non, t'as la classe. :-)",
0x356e70:"Bref, prends ça.",
0x356e90:"L'#YID Joueur#W, c'est l'adresse Flash Mail accessible seulement dans \"The World\".",
0x356ef0:"Avec le Flash Mail, tu échanges des messages en temps réel tant que t'es dans \"The World\".",
0x356f60:"Les débutants s'en servent surtout pour contacter d'autres joueurs et former un groupe.",
0x356fb0:"Essaie en m'invitant dans ton groupe.",
0x356fe0:"D'abord, appuie sur la #Ytouche %6#W pour ouvrir le menu.",
0x357020:"Dans le menu, choisis #YGroupe#W.",
0x357050:"Ensuite, choisis #YAjouter#W.",
0x357070:"Les joueurs qui t'ont donné leur ID Joueur sont listés ici.",
0x3570c0:"Choisis un joueur à inviter dans ton groupe et envoie-lui un Flash Mail.",
0x357110:"Comme tu débutes, t'as sûrement que mon ID Joueur. :-)",
0x357160:"Maintenant, appuie deux fois sur la #Ytouche %8#W pour m'envoyer un Flash Mail.",
0x3571b0:"...Ah, reçu ! \"Rejoins mon groupe !\" C'est bizarre de s'écrire alors qu'on est face à face. :-)",
0x357220:"Tu vois ? Mon nom apparaît en bas de ton écran. Ca veut dire que je suis dans ton groupe.",
0x357270:"Au fait, le Flash Mail ne marche que quand t'es en ville.",
0x3572c0:"Ah, et tu peux pas contacter les gens qui sont pas connectés à \"The World\".",
0x357310:"Les gens ont une vie, tu sais. On n'est pas en ligne 24 h sur 24 !",
0x357350:"Autrement dit, tu peux pas toujours compter sur les mêmes membres pour ton groupe.",
0x3573a0:"Alors récolte un max d'ID Joueur. Tu t'amuseras plus comme ça.",
0x357400:"Enfin, tu joues comme tu veux, mais comme l'EXP et le reste sont pas divisés entre membres...",
0x357460:"...t'as vraiment rien à gagner à jouer solo. ;-)",
0x3574a0:"Bon, on y va ? T'as rien à craindre. J'ai trouvé l'endroit parfait pour les débutants !",
0x357510:"Voici la #YChaos Gate#W, une sorte de téléporteur qui nous emmène d'un lieu à un autre.",
0x357570:"Maintenant, appuie sur la #Ytouche %8#W.",
0x3575a0:"Dans \"The World\", chaque lieu de jeu s'appelle une zone, définie par #Y3 mots-clés#W.",
0x357610:"Choisis #YNouveau mot-clé#W.",
0x357630:"Voici l'écran des mots-clés. En haut, c'est la zone de saisie.",
0x357670:"Tu y places les 3 mots-clés choisis, un par partie : A, B et C.",
0x3576c0:"A gauche, sous la zone de saisie, il y a tous les mots-clés que tu possèdes.",
0x357700:"Tu en récoltes d'autres en lisant tes mails, le Forum, et auprès d'autres joueurs.",
0x357760:"Bon, entrons des mots-clés, en commençant par la partie A.",
0x3577a0:"Choisis #BBursting#W dans la liste.",
0x3577d0:"Bien. Pour la partie B, choisis #BPassed Over#W.",
0x357810:"Et pour finir, en partie C, choisis #BAqua Field#W.",
0x357850:"Voilà, la zone est définie.",
0x357880:"Ah, encore un truc. Tu vois le symbole à gauche du mot-clé ?",
0x3578d0:"C'est le #Ysymbole du serveur#W. Il indique sur quel serveur t'es connecté.",
0x357930:"Ce symbole, c'est delta : on est donc connectés au serveur Delta.",
0x357970:"La liste en bas à droite, c'est la liste d'état de la zone.",
0x3579b0:"Tu vois le #Yjoyau#W à côté du type de terrain et du donjon ?",
0x3579f0:"Il indique comment le mot-clé choisi agit sur l'état.",
0x357a30:"Par exemple, regarde le type de terrain. Tu vois le joyau à droite ?",
0x357a80:"Ca veut dire que le type de terrain est fixé par #BAqua Field#W, le mot-clé en C.",
0x357ae0:"On saura pas quel terrain ce mot-clé va créer avant d'y être.",
0x357b40:"Mais une fois son effet connu, on peut le combiner efficacement avec d'autres mots-clés.",
0x357bb0:"Pour plus de détails, va voir le Forum à l'occasion.",
0x357bf0:"Allez, en route pour\n#B%0 Bursting Passed Over Aqua Field#W !",
0x357c40:"Choisis #YWarp#W.",
0x357c60:"Quand tu veux que je fasse un truc, utilise les commandes de chat.",
0x357ca0:"Hé, si on allait voir le donjon ? On n'est pas venus pour rien.",
0x357cf0:"Avant d'y aller, je t'explique le #Ycontrôle de la caméra#W.",
0x357d40:"En jeu, les ennemis attaquent de toutes les directions.",
0x357d80:"Le but, c'est d'ajuster vite ta vue pour voir l'ennemi et saisir la situation.",
0x357de0:"J'y reviendrai, mais retiens que les #Ycompétences#W ne visent que les cibles que tu vois.",
0x357e40:"En gros, si tu gères mal la caméra, t'es mort avant d'avoir compris.",
0x357ea0:"D'abord, fais tourner la caméra. Essaie de bouger le #Ystick analogique droit#W.",
0x357ef0:"Bien. Maintenant, zoom avant et zoom arrière.",
0x357f20:"Pour zoomer, utilise les #Ytouches R1#W et #YR2#W.\nEssaie.",
0x357f70:"Ouais, c'est ça.",
0x357f90:"Enfin, réinitialise la caméra avec la #Ytouche L1#W.",
0x357fd0:"Et voilà. Retiens bien : dès que le combat commence, ajuste ta caméra en permanence.",
0x358020:"Bon, et voici le #Yterrain#W. C'est le niveau le plus bas de la zone.",
0x358070:"Pour rentrer en ville, appuie sur la #Ytouche %6#W et choisis #YGate Out#W dans le menu.",
0x3580e0:"Prairie, terres sauvages, jungle... ce sont des types de terrain. Les mots-clés les fixent.",
0x358140:"Le type de terrain et la météo déterminent l'#Yélément de la zone#W.",
0x3581a0:"Par exemple, une prairie sous la pluie donnera une zone d'#Yélément Eau#W.",
0x358210:"Les éléments jouent aussi sur les monstres qui apparaissent et les objets à gagner.",
0x358270:"T'en fais pas pour l'instant. Avec l'habitude, combine les mots pour varier les éléments.",
0x3582d0:"Allez, en route pour notre quête ! D'abord, regarde la carte en haut à droite.",
0x358320:"Tu vois la #Yflèche rouge vers le bas#W ? C'est la porte du #Ydonjon#W.",
0x358370:"Au plus profond du donjon se trouve une #Ystatue Gott#W, qui renferme souvent un objet rare.",
0x3583d0:"En gros, le but est d'atteindre cette statue.",
0x358400:"Mais les ennemis sont souvent plus coriaces en bas : gagne des niveaux en surface d'abord.",
0x358470:"OK, attends une seconde.",
0x358490:"Orca utilise un #GOrbe de fée#W !",
0x3584b0:"Avec l'#GOrbe de fée#W, les données cachées de la carte deviennent visibles, comme ça.",
0x358510:"Les zones jaunes de la carte sont des #Yportails magiques#W : monstres et trésors t'y attendent.",
0x358570:"Allez ! On va chercher la bagarre ? Dirige-toi vers un portail magique.",
0x3585c0:"Pour une attaque de base, approche-toi de la cible et appuie sur la #Ytouche %8#W.",
0x358610:"Au fait, un curseur apparaît sur la cible pour que tu voies son nom et ses HP.",
0x358670:"Essaie de battre quelques monstres avec l'attaque de base.",
0x3586b0:"Tu commences à piger le truc, non ? OK, essayons les #Ycompétences#W.",
0x358700:"Appuie sur la #Ytouche %6#W pour ouvrir le menu, et choisis #YCompétences#W.",
0x358750:"OK, choisis #YRepth#W dans la liste.",
0x358780:"Quand le curseur apparaît, choisis la cible et appuie sur la #Ytouche %8#W pour lancer.",
0x3587e0:"Et voilà. Facile, hein ?",
0x358800:"Tu peux cibler un allié pour les soins et remèdes, et l'ennemi pour les attaques.",
0x358860:"Retiens bien : une compétence ne s'applique qu'aux cibles dans ton champ de vision.",
0x3588b0:"Avant d'en lancer une, règle la caméra pour avoir ta cible à l'écran.",
0x358900:"Bon, tu dois en avoir marre de moi, à force. ;-)",
0x358940:"A ton tour de me donner des ordres, avec les #Ycommandes de chat#W.",
0x358990:"OK, je t'apprends la commande pour que tes membres soignent.",
0x3589d0:"Bon, appuie sur la #Ytouche %7#W pour ouvrir le menu.",
0x358a10:"Ensuite, vas-y, choisis #YPremiers soins !#W dans le menu.",
0x358a50:"Alors ? C'est bon d'être le chef, hein ? :-)",
0x358a80:"Bien utilisé, ça permet de foncer à plusieurs sur l'ennemi ou de donner un ordre à chacun.",
0x358af0:"Quand tu ajoutes des membres au groupe, teste les commandes de chat pour voir leurs effets.",
0x358b50:"C'est tout pour l'instant ! Retiens ce que t'as appris et pars explorer.",
0x358ba0:"Quand tu te sens prêt, on file au donjon !",
0x358be0:"D'abord, tourne la caméra. Appuie sur la #Ytouche L1#W ou #YR1#W pour la déplacer.",
0x358c50:"Tu peux zoomer avec le #Ystick analogique droit#W.\nEssaie.",
0x358ca0:"Enfin, réinitialise la caméra avec la #Ytouche R2#W.",
0x358ce0:"Hé, attends ! Y a pas le feu. Allons d'abord à un portail magique ! :-)",
0x358d30:"Maintenant on peut explorer le donjon !",
0x358d60:"Un truc à retenir : tu peux pas faire de Gate Out quand t'es dans un donjon.",
0x358dc0:"Pour un Gate Out vers la ville, il faut d'abord remonter sur le terrain.",
0x358e10:"L'#GOcarina esprit#W te ramène à la surface, mais elle est inutilisable en combat.",
0x358e70:"Attention, on est piégés ici !",
0x358ea0:"Dans les donjons, il y a des salles piégées un peu partout.",
0x358ee0:"Le seul moyen de sortir d'un piège pareil, c'est d'activer tous les portails de la salle.",
0x358f50:"Allez, on fonce sur ce portail magique !",
0x358f80:"C'est la salle où se trouve la statue.",
0x358fb0:"Il n'y en a qu'une, au plus profond du donjon, et elle donne des objets rares.",
0x359010:"Assez d'aventure pour l'instant. On prend le trésor et on rentre en ville, d'accord ?",
0x359070:"Avec un #GOcarina esprit#W on sortirait direct, mais on n'en a pas.",
0x3590d0:"Donc faut repartir par où on est venus.",
0x359100:"Quand tu veux que je fasse un truc, dis-le-moi avec les commandes de chat.",
0x359150:"Voici un coffre au trésor.\nMais ça, tu le savais, non ?\n;-)",
0x359190:"Sache qu'il y a deux types de coffres : les normaux et les piégés.",
0x3591f0:"Celui-ci est normal. Appuie sur la #Ytouche %8#W pour l'ouvrir.",
0x359230:"Celui-ci est piégé. Tu vois la couleur différente ? Ouvre-le tel quel et t'es cuit.",
0x3592a0:"Utilise le #GFil de fortune#W dessus. Cet objet désamorce le piège.",
0x3592f0:"Orca utilise le #GFil de fortune#W !",
0x359320:"Tu vois, plus de danger. Appuie sur la #Ytouche %8#W pour l'ouvrir.",
0x359370:"(C'est un cul-de-sac. Cette fille...)",
0x3593a0:"Qu'est-ce qu'il avait, Yasuhiko ? Pourquoi il était bouleversé ?",
0x3593e0:"Je voulais lui demander, mais il décrochait même pas le téléphone.",
0x359420:"Le lendemain, j'ai appris que Yasuhiko avait été hospitalisé.",
0x359470:"J'ai foncé à l'hôpital, mais ils m'ont même pas laissé le voir.",
0x3594c0:"C'est peut-être mieux ainsi. Je voulais pas le voir tout faible, et lui non plus.",
0x359530:"Mais...\nQu'est-ce qui lui est arrivé ?",
0x359560:"J'ai le sentiment que la clé se trouve quelque part dans...\n\"The World\".",
0x3595b0:"Merci de votre visite dans \"The World\".",
0x3595e0:"Tous les services sont actuellement indisponibles pour cause de maintenance.",
0x359620:"Veuillez nous excuser pour la gêne et faire preuve de patience.",
0x359660:"Je devrais parler de Yasuhiko sur le Forum. Quelqu'un répondra peut-être.",
0x3596b0:"(Qui a envoyé ça ? C'est illisible.)",
0x3596d8:"Et puis...",
0x359700:"Encore toi... Je suis occupée, là. Tu peux pas me lâcher ?",
0x359748:"Attends une seconde !",
0x359760:"Ouais, toi. Je, euh... je connais des mots-clés intéressants.",
0x3597a0:"Si tu viens avec moi, je te les dis. Tu veux les connaître ?",
0x3597f0:"\n  Oui, volontiers.\n  Ah, une autre fois peut-être.",
0x359820:"Voilà ! C'est ça l'esprit ! Parole de vrai débutant.",
0x359860:"Très bien. Fais ta tête de mule.",
0x359880:"Ah, donc tu veux bien venir. Fallait le dire tout de suite !",
0x3598d0:"\n  Ouais, je viens.\n  Tout compte fait, non.",
0x359910:"Ben fallait le dire tout de suite ! OK, on y va !",
0x359950:"Décide-toi, à la fin !",
0x359980:"Les mots-clés sont :\n#B%0 Hidden Forbidden Holy Ground#W.",
0x3599c0:"Hé, on va pas à\n#B%0 Hidden Forbidden Holy Ground#W ?",
0x359a10:"Tu fais quoi ? Faut m'ajouter à ton groupe !",
0x359a50:"Waouh. Cet endroit, c'est...",
0x359a80:"Laisse tomber. On y va. Alors, tu m'escortes comme un vrai gentleman ?",
0x359ae0:"Ahhhhhhhhhhhhhh !\nAhhhhhhhhhhhhhh !\nAhh...",
0x359b10:"J'ai cru mourir d'une crise cardiaque...",
0x359b50:"Qu... quoi ? Me fais pas flipper comme ça !",
0x359b80:"Ca se fait pas ! Vraiment pas !!",
0x359ba0:"Le livre.\nOuvre le livre.",
0x359bc0:"Le livre ?",
0x359bd0:"Son pouvoir peut apporter le salut ou la destruction, au gré de celui qui s'en sert.",
0x359c30:"Tu utilises le livre d'installation, le #YLivre du Crépuscule#W !",
0x359c70:"J'ai cru qu'il finirait comme Orca, et... j'ai paniqué. C'est là que j'ai entendu sa voix.",
0x359cd0:"C'était la voix de la fille qui a donné le livre à Orca.",
0x359d10:"Je vois. Mais tu feras quoi si le Data Bug réapparaît ?",
0x359d60:"Ce pouvoir a mis ton ami... euh...\nPardon.",
0x359d90:"Je sais même pas ce qu'est ce pouvoir...",
0x359dc0:"Ni ce qu'elle voulait qu'Orca fasse. Et moi, je suis censé en faire quoi ?",
0x359e10:"Tout ce que je veux, c'est aider Orca...",
0x359e40:"Bon, faut que j'y aille.",
0x359e60:"Aujourd'hui, c'était... euh...\nJe sais pas quoi dire, mais...",
0x359e98:"Bonne nuit.",
0x359eb0:"T'es sûr ? T'auras plus jamais une occasion pareille !",
0x359ef0:"(Je vais d'abord m'équiper. Et récolter quelques infos, aussi.)",
0x359f40:"Elle est au courant pour mon bracelet. Qui est-elle ?",
0x359f70:"Le message que j'avais posté a été supprimé.",
0x359fa0:"J'ai vu un perso bizarre dans la ruelle. On aurait dit un chat. :-) On peut modifier comme ça ?",
0x35a010:"Un chat ? Ah ouais, je l'ai vu aussi. Mais je préfère les filles-lapins.",
0x35a050:"Voyons ce qu'il y a sur le Forum.",
0x35a080:"Je suis venu après avoir lu le Forum, mais l'opérateur m'a refoulé. On peut pas jouer ici.",
0x35a0f0:"Merci de jouer à \"The World\".",
0x35a120:"Cette zone est instable et ne fonctionne pas correctement : ses données sont corrompues.",
0x35a190:"Veuillez regagner le terrain immédiatement et faire un Gate Out vers la ville.",
0x35a1e0:"Oups ! Waouh !",
0x35a200:"Pardon, pardon.\nJ'étais super pressée.",
0x35a230:"Hein ? Pourquoi je suis pressée ? Euh... parce que... oh... hum... bonne question.",
0x35a280:"Je suis venue parce que j'ai lu un message sur le Forum et que ça avait l'air intéressant.",
0x35a2d0:"Mais cet endroit est trop bizarre. Même avec des données corrompues, c'est trop. :O",
0x35a330:"Waouh ! Trop cool ! :D",
0x35a350:"T'as battu le monstre en réécrivant ses données, j'y crois pas ! T'as fait comment ?",
0x35a3a8:"Je, euh...",
0x35a3c0:"Oh. J'ai touché un point sensible ? Je ferais mieux de me taire ?",
0x35a400:"Enfin bref. On dirait qu'il se passe des choses étranges partout dans \"The World\".",
0x35a460:"Depuis la panne de serveur, tout part de travers. Il se trame quelque chose !",
0x35a4c0:"Quoi !? Oh, zut !",
0x35a4e0:"J'ai cramé le dîner... :_(",
0x35a500:"Bon, faut que j'y aille. :*",
0x35a520:"Ah, j'allais oublier. Invite-moi dans ton groupe la prochaine fois. On remet ça, OK ?",
0x35a580:"Non, si j'abandonne maintenant, je pourrai jamais l'aider ! Je dois continuer.",
0x35a5e0:"(...Un Data Bug ?!)",
0x35a600:"(Il me faut le #YData Drain#W pour le battre !)",
0x35a630:"Je vais d'abord lire mes mails.",
0x35a650:"Félicitations ! Vous êtes le grand gagnant de notre concours ! Voici votre prix.",
0x35a6a0:"Le #GLivre de la loi#W est un objet rare qui améliore votre personnage.",
0x35a6f0:"Sélectionnez-le dans la fenêtre d'objets : le niveau du personnage sera mis à jour.",
0x35a750:"(J'ai gagné... ? Allons voir une boutique en ville.)",
0x35a780:"Lisons d'abord mes mails.",
0x35a7a0:"Mia a dit de venir seul.",
0x35a7d0:"Salut ! Je t'attendais. En fait, moi aussi ton bracelet m'intéresse. Merci d'être venu.",
0x35a840:"Je suis au dernier niveau du donjon. Tu peux arriver jusqu'ici, non ?",
0x35a890:"Comment tu connais le Data Drain ?",
0x35a8c0:"Hmm, difficile à dire.",
0x35a8e0:"Merci de jouer à The World.",
0x35a910:"Cette zone est instable et ne fonctionne pas correctement : ses données sont corrompues.",
0x35a980:"Veuillez regagner le terrain immédiatement et faire un Gate Out vers la ville.",
0x35a9d0:"Alors, t'en penses quoi ? Tu crois que la zone est vraiment corrompue ?",
0x35aa20:"La vérité, c'est que pour que quelque chose naisse, quelque chose doit se briser.",
0x35aa60:"C'est pareil pour les humains. Tu comprends ce que je veux dire ?",
0x35aaa0:"T'es venu percer le secret du bracelet, mais tu me fais pas vraiment confiance.",
0x35ab00:"Le monde n'est pas fait que de 1 et de 0. Il admet des zones entre le oui et le non.",
0x35ab70:"Les humains sont intéressants, tu trouves pas ?",
0x35aba0:"Approche-toi de ce portail magique.",
0x35abd0:"Maintenant, montre-moi le pouvoir de celui qui porte le bracelet !",
0x35ac10:"Alors c'est ça, le Data Drain. Je l'avais jamais vu.",
0x35ac50:"Quoi !? Qu'est-ce que tu veux dire par là !",
0x35ac80:"T'es fâché ?",
0x35aca0:"Je voulais juste connaître l'étendue de ton pouvoir.",
0x35ace0:"Si t'étais trop faible, ça servirait à rien de t'apprendre à pirater les portes.",
0x35ad38:"Pirater les portes ?",
0x35ad50:"Tu viens de drainer un Virus Core. Ce talent est bien utile quand on sait ce qu'on fait.",
0x35adb0:"Les Virus Cores sont la clé pour franchir les barrières de protection.",
0x35ae00:"Evidemment, ils sont inutiles à ceux qui n'ont pas le bracelet.",
0x35ae50:"Je vais te montrer comment pirater les portes. Viens à la Chaos Gate. J'ai adoré le Data Drain.",
0x35aec0:"(Je peux pas revenir en arrière. Enfonçons-nous dans le donjon !)",
0x35af00:"Ajoute-nous d'abord à ton groupe, ensuite on ira à la porte.",
0x35af40:"Tu obtiens les #YID Joueur#W de #YMia et d'Elk#W.",
0x35af80:"T'oublies de nous ajouter à ton groupe.",
0x35afb0:"Entre les mots-clés d'une zone protégée.",
0x35afe0:"Ca devrait ouvrir le menu de piratage de la porte.",
0x35b010:"Tu connais les mots-clés d'une zone protégée. Ils étaient postés sur le Forum.",
0x35b060:"Les mots-clés sont :\n#B%0 Closed Oblivious Twin Hills#W.",
0x35b0a0:"Tu vois ? Il faut des Virus Cores pour pirater les portes.",
0x35b0d0:"Regarde la jauge : elle indique le type et le nombre de Virus Cores nécessaires.",
0x35b130:"Si t'as tous les Virus Cores requis, tu remplis la jauge et tu pirates la porte.",
0x35b190:"Après le piratage, les Virus Cores utilisés disparaissent.",
0x35b1d0:"Une fois la porte piratée, la zone est ouverte à tous.\nT'as compris ?",
0x35b230:"\n  Non, pas vraiment.\n  Ouais, je crois.",
0x35b260:"Il doit y avoir un secret dans ces zones protégées. C'est pour ça qu'on les verrouille, non ?",
0x35b2c0:"Si tu t'approches d'un portail magique, des Data Bugs apparaîtront.",
0x35b300:"En leur faisant un Data Drain, tu en tireras des Virus Cores.",
0x35b350:"Il y a forcément une raison si tu portes ce bracelet.",
0x35b390:"Tu vas y aller pour la découvrir, non ?",
0x35b3d0:"La raison pour laquelle j'ai ce bracelet ?",
0x35b400:"En fait, ce bracelet appartient à mon ami.",
0x35b430:"#0 raconta à Mia tout ce qui s'était passé.",
0x35b460:"Ce qui t'est arrivé dans le passé, je m'en fiche.",
0x35b4a0:"Mais ce que tu vas faire du bracelet à l'avenir, ça, ça m'intéresse.",
0x35b500:"Bon, c'est à peu près tout. Si je peux t'aider en quoi que ce soit, je ferai de mon mieux.",
0x35b570:"Pas besoin de me remercier. Je fais juste ce dont j'ai envie.",
0x35b5c0:"Dis, Mia...",
0x35b5d0:"Je devrais emmener Mia et Elk dans cette zone.",
0x35b600:"Lisons d'abord mon nouveau mail.",
0x35b630:"Hé. Un gentleman ne fait jamais attendre une dame ! :)",
0x35b660:"Tu viens bien avec moi à #B%4 Quiet Eternal#W\n#BWhite Devil#W, hein ?",
0x35b6b0:"Je t'attends à la Chaos Gate. Ramène-toi dès que t'es prêt.",
0x35b700:"J'arrive tout de suite. :-)",
0x35b720:"Oh, tu me plantes là. Très bien. Je m'en fiche...",
0x35b760:"Allô ? On va à :\n#B%4 Quiet Eternal White Devil.#W",
0x35b7a0:"Eh ben, c'était facile. Bizarre...",
0x35b7d0:"Y a personne. Ni le truc au bâton rouge, ni la fille.",
0x35b810:"C'était un canular ? C'est pas possible, si ?",
0x35b840:"Y a un truc qui cloche, mais ça sert à rien de rester là. On rentre pour l'instant ?",
0x35b8a0:"(BlackRose en a parlé aussi, allons sur le #Yserveur %4#W.)",
0x35b8e0:"(C'est un cul-de-sac.)",
0x35b900:"Vous pouvez désormais aller sur le #Yserveur %4#W.",
0x35b930:"Choisissez #YAutres serveurs#W dans le menu de la Chaos Gate.",
0x35b970:"Mia, t'es bizarre ces temps-ci. Pourquoi tu t'intéresses autant à ce type ?",
0x35b9c0:"Ce que je fais ne te regarde pas, Elk.",
0x35b9f0:"Mia... Il te plaît ?",
0x35ba10:"Me plaire ? Qu'est-ce que tu veux dire par là ?",
0x35ba40:"Mia, euh... euh... je...\nJe t'aime bien.",
0x35ba70:"Hein ? Qu'est-ce que c'est ?\nJe me sens bizarre.",
0x35baa0:"Hé ! On peut parler une minute ?",
0x35bad0:"J'ai une zone préférée, mais elle est bizarre ces temps-ci. C'est peut-être un Data Bug.",
0x35bb40:"T'es le seul à pouvoir m'aider. C'est #B%0 Plenteous Smiling#W\n#BHypha#W. Tu viens avec moi ?",
0x35bbc0:"Merci !",
0x35bbd0:"Euh, pardon. La zone, c'est :\n#B%0 Plenteous Smiling Hypha#W.",
0x35bc20:"On y va pas ensemble ?",
0x35bc40:"Désolé, mais je veux y aller seulement avec toi.",
0x35bc70:"Je vois rien d'anormal ici.",
0x35bca0:"Pardon. En fait, euh... j'ai quelque chose à te demander.",
0x35bcf0:"Je te donne tous mes objets. En échange, euh... tu peux me donner ton bracelet ?",
0x35bd50:"S'il te plaît ! Je t'en supplie !",
0x35bd70:"Si je l'ai... Mia traînera de nouveau avec moi, comme avant.",
0x35bdc0:"Qu'est-ce que... Quoi ?!\nQu'est-ce qui se passe ?",
0x35bdf0:"Allons au donjon.\nOn trouvera peut-être quelque chose.",
0x35be30:"Cet endroit n'était pas comme ça avant. Mon mensonge est devenu vrai.",
0x35be78:"Mensonge ?",
0x35be80:"J'ai menti pour te faire venir ici, et maintenant c'est devenu vrai.",
0x35bec0:"Mia ! Qu'est-ce que tu fais là !?",
0x35bee8:"Elk !!!",
0x35bf00:"Mia m'appelle...\nMia m'appelle !",
0x35bf30:"Elk...\nJe me doutais que tu serais ici.\nJe te cherchais.",
0x35bf70:"Tu me cherchais ? Moi ?",
0x35bf90:"Je sais pas trop, mais... tu me manques quand t'es pas là.",
0x35bfd0:"Merci Mia. Mais...\nnotre zone préférée est fichue.",
0x35c010:"En théorie, le nombre de zones est infini. On en trouvera une autre ailleurs.",
0x35c070:"Ouais. T'as raison.",
0x35c090:"#B%4 Cursed Despaired Paradise#W\nTu viens, hein ?",
0x35c0d0:"Pourquoi tu tiens tant à me faire ça ?!",
0x35c100:"J'ai pas assez de Virus Cores.",
0x35c130:"Les mots-clés d'ici étaient peut-être dans le message d'origine, et quelqu'un l'a modifié.",
0x35c190:"Mon message aussi a été...",
0x35c1b0:"Supprimé, c'est ça ?",
0x35c1d0:"Je sais pas trop ce qui se passe, mais j'ai un mauvais pressentiment.",
0x35c220:"Arrête un peu. C'est un objet super rare. 9999 GP ! C'est mon dernier prix !",
0x35c270:"Y a moyen de payer à crédit ?",
0x35c2a0:"A taux élevé, ouais.",
0x35c2d0:"Ouin !\nEpargnez-moi l'enfer de la dette ! :(",
0x35c300:"L'enfer de la dette. Ca sonne affreux.",
0x35c330:"Pire qu'affreux !!",
0x35c350:"Bon, la négociation est terminée.",
0x35c380:"Ah ! Depuis quand tu me regardes ?",
0x35c3b0:"Depuis que t'as demandé pour le crédit.",
0x35c3e0:"Hé hé. :)\nMoi, faut que je collectionne absolument tous les objets.",
0x35c430:"C'est pour ça que je m'emballe. ;)",
0x35c460:"Euh, d'accord...",
0x35c470:"Bon, je vais faire un tour pour me calmer. :)",
0x35c4a8:"Bonjour !",
0x35c4b8:"Oui ?",
0x35c4c0:"J'ai ce #GLivre de fer#W. Ca t'intéresse ? Bien sûr que oui.",
0x35c500:"Installe cet objet, et il annulera très souvent l'attaque d'un ennemi.",
0x35c560:"Ca te dit, pour 999 GP ?",
}
