# -*- coding: utf-8 -*-
G={
761:"Je me suis lié d'amitié avec un certain Kikurin l'autre jour, et en fait c'ETAIT déjà mon pote !",
762:"C'est marrant, non ?",
763:"Je rappais, vu que le serveur était HS. Mon blaze, c'est Borscht, fais-moi signe.",
764:"Le mot russe du jour.\nGorbatchev.\nPas mal, hein ?",
765:"Ca sonne carrément russe.",
766:"Mon groupe préféré va se séparer...\nLaisse-moi tranquille...",
767:"Mon ami déménage...\nOn commençait juste à se connaître...",
768:"Le net, c'est génial ! Je peux retrouver mes amis ici, même s'ils habitent très loin !",
769:"Hé hé hé.",
770:"Hé hé. Bon, comment je vais les arnaquer la prochaine fois ?",
771:"Hé ! Ecoute pas aux portes ! J'y travaille encore.",
772:"Il paraît que traîner par ici augmente la défense, hé hé hé.",
773:"Le pont de Mac Anu est vieux, tu pourrais passer à travers. Attention en traversant...",
774:"Hé, c'est pas Balmung, là ?!",
775:"T'as regardé !\nHaha, le boulet.",
776:"Il paraît que traîner par ici augmente l'attaque, hé hé hé.",
777:"Y a plein de types qui mentent. Les débutants se font souvent avoir.",
778:"Hé, toi aussi, fais gaffe, tu sais.",
779:"Hé, j'ai vu 10 000 GP par terre au fond d'une ruelle. Sérieux, va voir !",
780:"Il paraît que traîner par ici augmente les HP max, hé hé hé.",
781:"Hé, tu savais que si ton groupe meurt sur le terrain, faut ramener de la terre du terrain chez soi ?",
782:"Hé, c'est ce qu'on m'a dit : The World ferme à la fin du mois.",
783:"Il paraît que traîner par ici fait trouver une porte secrète, hé hé hé.",
784:"Il paraît que traîner par ici rapporte de l'argent, hé hé hé.",
785:"Il paraît que traîner par ici est une perte de temps, hé hé hé.",
786:"Il paraît que traîner par ici augmente la défense, hé hé hé.",
787:"Hé, hé, hé, ça va ?",
788:"Hé hé hé hé. Tu m'embêtes. T'es obligé de me parler maintenant ?",
789:"Hé, hé, hé, tu préfères le curry ou les ramen ?",
790:"Hé hé hé hé !\nTu préfères le pain ou le riz ?",
791:["Héhéhéhéhéhéhéhéhéhéhéhé","Héhéhéhéhéhéhéhéhéhéhéhé","Héhéhéhéhéhéhéhéhéhéhéhé"],
792:"Alors, j'ai dit hé combien de fois ?",
793:"Hé, hé, hé, t'as vu un objet bizarre dans le ciel ?",
794:"Hé hé hé hé !\nY a pas un gars pénible qui te pose sans arrêt des questions ?",
795:"Hé hé hé hé !\nTu m'aimes ou tu me détestes ?",
796:"Hé, hé, hé, j'ai entendu un bruit étrange. Tu sais quelque chose ?",
797:"Hé hé hé hé !\nJe te dérange ?",
798:"Hé hé hé hé !\nOu yo yo yo yo !\nTu préfères quoi ?",
799:"Hé, hé, hé, j'avais pas touché au jeu depuis des lustres et je me suis fait gronder parce que je jouais trop.",
800:"Hé, hé, hé, quelqu'un a déjà écrasé ta sauvegarde ?",
801:"Hé, hé, hé, t'es au courant pour le plantage du serveur ?",
802:"Hé, hé, hé, tu mets de la sauce soja ou de la sauce piquante sur la friture ?",
803:"Euh...\nOn se connaît ?",
804:"Euh... t'es qui, déjà ? J'ai ton nom sur le bout de la langue. Bon, ça me reviendra.",
805:"Tuer des ennemis faibles ne rapporte pas beaucoup d'EXP.",
806:"Pardon !\nJ'oublie tout en ce moment.\nCa va me revenir, attends.",
807:"Attends, on s'est vus dans la vraie vie ?",
808:"J'ai mal au cou quand je joue trop. Ma mère me dit d'arrêter.",
809:"Mais ça, c'est pas près d'arriver.",
810:"Tu devrais consulter souvent le Forum.",
811:"Hé, t'es Yoshida, non ? Je suis toujours comme ça. Le prends pas mal, OK ?",
812:"Désolé de t'avoir planté l'autre fois.\n... Dis quelque chose.",
813:"Attends ! Oh non, mon dos !! Mon dos s'est encore bloqué !",
814:"Pff, ça craint...",
815:"Sois sympa avec les joueurs que tu veux dans ton groupe.",
816:"Hmmm... c'est peut-être pas bien d'avoir trop d'amis... Je sais plus qui est qui...",
817:"Oh, pardon. C'est juste que t'as pas l'air d'avoir beaucoup d'amis, tu vois ?",
818:"Mon dos me fait un mal de chien en ce moment. J'espère que je suis pas malade...",
819:"Je ferais mieux d'y aller mollo...",
820:"Il paraît qu'ils vont ouvrir d'autres serveurs que %1.",
821:"Il paraît que ce jeu...\n... est dangereux...",
822:"Il paraît que le jeu continue même après l'avoir fini.",
823:"Yo, tu veux savoir un truc ?",
824:"Alors, t'aimes le Hirami Insider ? J'en aurai d'autres à notre prochaine rencontre. Ca te va ?",
825:"On ne peut porter qu'un nombre limité d'objets, alors dépose-les à l'Elf's Haven.",
826:"Pour faire des économies, faut revendre tes objets.",
827:"Hirami te dit : méfie-toi des joueurs louches sur le terrain... Garde l'oeil ouvert.",
828:"Changer d'équipement, c'est aussi changer de compétences.",
829:"Pour choisir un équipement, regarde les compétences, pas les paramètres.",
830:"Il paraît qu'il existe un objet rare appelé Hyakkidouran. C'est quelle langue ? Trop classe.",
831:"Hirami trouve le PC nommé Wing très bizarre. Le conseil de Hirami ? Reste loin ! TRES loin.",
832:"J'ai aussi parlé à Cima... Elle était en transe. Deux sacrés numéros... !",
833:"Il paraît qu'une magie invoque un gobelin géant.",
834:"La version japonaise de The World en est encore à la Version 2.01.",
835:"Les patchs par pays, ça doit prendre du temps.",
836:"D'après l'enquête de Hirami, des ondes toxiques ont été détectées chez Henako !",
837:"Va comprendre.",
838:"Des objets appelés Books augmentent ton statut de façon permanente.",
839:"Il paraît qu'il existe un objet appelé Tombeurs.",
840:"Les créateurs du jeu te remercient vraiment d'avoir joué jusqu'ici.",
841:"Oh yeah ! Allez ! Trop bien !",
842:"Henako est fatiguée... Henako n'a plus d'énergie. Henako va dormir. Bonne nuit, dit Henako.",
843:"Quel beau jeune homme. Tes hormones sont en marche ? Tu me donnes chaud !",
844:"Je suis Henako, la déesse de l'amour !",
845:["Lalalalalala","Lalalalalala","Lalalalalala"],
846:"Genre, je capte une aura super forte chez toi.",
847:"Que le rayon d'amour Henako touche ceux qui remontent ce chemin.",
848:"Tu vois ? Tu sens l'amour, là ?",
849:"Toi ! Identifie-toi en 16 caractères maximum.",
850:"Genre, je suis sensible aux ondes bizarres, mais toi. Toi, t'as autre chose.",
851:"Touche-moi et tu te brûles. Je suis chaude, chaude, chaude ! Je SUIS Henako Bomb 2002 !",
852:"Héééé !!\nCa va ?\nQui ferait une chose pareille ?",
853:"Je suis trop heureuse !! Je te présente papa Henako ! Alors c'est toi, le petit ami.",
854:"Papa, on peut se marier ce soir ? OK. Troooop bien !!!! Merci, papa !",
855:"Hé, tu sais ce que veut dire %1 ? Je crois que ça a un rapport avec le cosmos !!",
856:"Hackers et rockers. Oh, les deux vivent à fond et foncent !",
857:"Mais sans cette vibe, l'aura du cosmos faiblit, et y a moi qui te veux ! Bisou bisou !!",
858:"..........\n... Pardon...\nJe pensais à autre chose...",
859:"Hmm... dis, tu peux me laisser un moment ? J'arrive pas à me concentrer avec du monde autour.",
860:"Ca fait combien de temps que tu joues à ce jeu ?",
861:"Quoi... ?\nTu veux quoi ?",
862:"Euh... attends...\nHum... euh... zut, j'ai oublié ce que j'allais dire !",
863:"Attends, me parle pas maintenant. Ca va me revenir. Donne-moi une seconde.",
864:"J'ai entendu une très sale rumeur sur ce jeu, une fois... J'espère que c'est qu'une rumeur...",
865:"Tu veux savoir comment avoir des objets ? C'est pas si dur. Sers-toi de ta tête.",
866:"Euh... attends...\nHum... euh... zut, j'ai oublié ce que j'allais dire !",
867:"Ah oui, ça me revient ! C'est à propos de l'objet. Euh... je crois...",
868:"Ce bruit...\nC'est...",
869:"OK, c'est bon.\nPff, ce jeu est vraiment instable.",
870:"Ah, OK !\nJe vois...",
871:"Mais attends...\nNon, ça peut pas être ça...",
872:"L'arrêt du serveur, ça recommence...\nPourvu que ce soit que moi...",
873:"Le net est plein de rumeurs...\nMais ça me tracasse quand même...",
874:"L'annonce de CC... ça se tient... mais... ça tombe quand même trop bien...",
875:"Je pense écrire un récit documentaire sur ce qui s'est passé dans The World.",
876:"Oh, bonjour.",
877:"Hé hé, arrête de me regarder avec ces yeux de chien battu.",
878:"Pour ce que ça vaut, je trouve les génies un peu fêlés... Haha.",
879:"Je joue à ce jeu depuis longtemps, mais il ressemble aux autres RPG. Un vrai RPG, ça existe ?",
880:"Tout le monde aime la stabilité. Les RPG, la société, tout est toujours pareil.",
881:"C'est comme ça que les gens l'aiment.",
882:"C'est trop paisible. On va vivre comme ça ? Ou vivre selon nos propres règles ?",
883:"S'il ne se passe rien d'autre dans le jeu, je ne me connecterai plus pendant un moment. Dommage...",
884:"Pas besoin de révolution, mais si on a peur du changement, comment évoluer et avancer ?",
885:"En quoi tu crois, toi ?\nMoi je dis : suis ton instinct.",
886:"Je ne savais pas qu'il y avait un événement caché pareil ! Ce jeu est plus profond que prévu.",
887:"Je crois qu'il va se passer quelque chose. Le sang va couler. Crois-moi. On n'a rien sans rien.",
888:"Un cas isolé, ou le début de quelque chose d'énorme... qui sait ?",
889:"Je ne savais pas qu'ils avaient prévu des effets en cas de panne du serveur. Je dois réévaluer ce jeu.",
890:"Ca devient bon.\nVoilà ce que doit être un RPG !",
891:"Ce chaos, c'est exactement ce que j'attendais. Je prends les devants !",
892:"Rêves brisés...\nEspoirs et ambition envolés...\nNon... Je recréerai le chaos !!!",
893:"T'es encore loin de pouvoir m'adresser la parole !",
894:"T'es encore là ?! C'est quoi ton problème ?! T'as pas compris ?!",
895:"Si t'as compris, dégage.",
896:"Que des nuls en ce moment. Les gens ne voient pas que ce jeu est trop dur pour eux ?",
897:"Tout le monde n'en a que pour Balmung ou Orca. The World ne tourne pas autour d'EUX.",
898:"A qui tu crois parler ! Tu as sûrement entendu parler de moi... ... Non ?!",
899:"Hmm, c'est moi la plus forte en ce moment ? Pas vu ce pénible d'Orca ces temps-ci...",
900:"Hahaha !\nOn se vaut tous à peu près.",
901:"Je joue depuis l'époque où Balmung était haut comme trois pommes...",
902:"Je t'ai eu ! Les persos de jeu ne grandissent pas à l'écran. Tu devrais le savoir.",
903:"Ca devient intéressant ces temps-ci. Les joueurs ordinaires commençaient à m'ennuyer.",
904:"Alors, c'est quoi l'histoire ?",
905:"Wing ne vaut rien, mais il est trop mignon... Mon instinct maternel s'emballe. J'ai envie de le câliner.",
906:"Le serveur %1 n'a pas l'air normal. Bah, ça prouve juste ma force.",
907:"Tu croirais pas le monstre que j'ai croisé l'autre jour ! Il sortait d'où ?!",
908:"Mort et destruction ! Et je serai la seule en vie ! Oui ! Rien que moi... hahahaha...",
909:"C'est plus drôle...\nTout est redevenu comme avant...",
910:"Je vais très bien, merci.",
911:"Quoi ? Oui, je peux vous aider ?",
912:"Je viens de commencer, mais ça me plaît déjà, merci.",
913:"Correct. Il y a des ennemis effrayants.",
914:"On me prend souvent pour un policier cosaque.",
915:"Je crois que je maîtrise enfin le jeu, merci.",
916:"Correct. Je n'arrive pas à avoir de bonnes armes.",
917:"Correct, je n'ai aucun sens de l'orientation, mais c'est aussi ce qui rend ça excitant.",
918:"Le serveur a planté, mais je n'ai eu aucun souci, merci.",
919:"Le plantage, ça allait, mais la foudre a causé une coupure de courant dans le quartier.",
920:"Correct. J'ai perdu 6 heures de données de jeu...",
921:"Je me déconnecte bientôt.\nJe me lève tôt.",
922:"Il y a plus d'aventure maintenant que %1 a ouvert, merci.",
923:"Il y a beaucoup de problèmes de serveur, mais ce sera réglé, je le sais, merci.",
924:"Il y a beaucoup de problèmes de serveur, mais ce sera réglé, je le sais, merci.",
925:"Les hackers... ça m'inquiète... merci.",
926:"C'est revenu à la normale, mais je sens quelque chose de différent, merci.",
927:"Après vous avoir parlé, je brûle de faire des recherches...",
928:"Je n'ai que cela en tête pour l'instant. Nous reparlerons plus tard.",
929:"C'est mon premier jeu en ligne, alors je ne saisis pas encore tout...",
930:"J'étudie la biologie, alors l'informatique et moi...",
931:"Une question me trotte dans la tête depuis un moment. Pourquoi seulement 5 notes, de A à F ?",
932:"Je n'utilisais pas les mots-clés jusqu'à récemment.",
933:"Hmmm... La structure évolutive des organismes de ce monde me fascine.",
934:"Comment les monstres se reproduisent-ils ? J'adorerais en faire une thèse.",
935:"Je n'ai jamais parlé à une personne du sexe opposé, j'ai passé ma vie à étudier.",
936:"C'est gênant, mais j'espère que cela mènera à quelque chose un jour.",
937:"J'ai été vraiment choqué quand le serveur a planté.",
938:"Comment un serveur plante-t-il ? Quelqu'un le conduit ? Que se passe-t-il ?",
939:"Quoi ?! Ce n'est pas ça ?!\nQuelle honte !\nJe n'y connais vraiment rien.",
940:"Ce qui m'a désarçonné, c'est que la fille à qui j'ai parlé hier était en fait un garçon !",
}
