# -*- coding: utf-8 -*-
G={
941:"C'est trop intense ! Où va le monde ?! Mais c'est bien pour cela que l'on fait de la recherche.",
942:"Je ne suis encore jamais allé dans une zone de %1. Les ennemis y seraient plus forts.",
943:"Un simple virus de hacker a autant d'effet sur le jeu ?",
944:"Je me demande...\nQue se passait-il...",
945:"Coucou.",
946:"Désolée... ! Le serveur... a... en... core... planté... On... se... re... parle.",
947:"J'ai l'impression d'aller toujours au même endroit, encore et encore...",
948:"Quand j'ai dit à Yuckey que j'aimais le curry, elle a juste dit : Ah. Ca veut dire quoi ?",
949:"Quand j'ai dit à Yuckey que j'aimais le pain, elle a juste dit : Ah. Ca veut dire quoi ?",
950:"Tu connais le sujet sur la statue Zeit, sur le Forum ? Ca me passionne en ce moment.",
951:"J'ai eu un super objet !\nJe suis troooop contente !",
952:"J'ai vu Balmung tout à l'heure. J'adorerais avoir ses ailes...",
953:"Alors c'était un problème de serveur... Je croyais que c'était mon ordi...",
954:"Le problème de serveur fait peur, mais mon ordi déconne à la maison. Pourvu que LUI ne plante pas !",
955:"Il paraît que Balmung peut voler avec ses ailes. C'est vrai ?",
956:"Si oui, je l'envie vraiment...",
957:"Maintenant que le serveur %1 a rouvert, on aura peut-être plus de joueurs.",
958:"Mon objet rare a fait bye bye quand le serveur a planté :-(",
959:"C'est peut-être pas une bonne idée de jouer en ce moment...",
960:"Allez. Je lâche tout ce que j'ai accumulé jusqu'ici et je m'éclate !",
961:"Alors... ça te dirait d'acheter un livre d'oreilles de chat que j'ai fait ? Je crois que ça te plaira.",
962:"Il paraît qu'un mot-clé contrôle la difficulté de la zone... Je le savais.",
963:"Hé, je suis un pro des chats. J'espère qu'il y en a plein dans The World.",
964:"Un fanzine de groupe ! Cool ! On rencontre plein de gens sympas grâce à ça.",
965:"Il paraît qu'une source améliore les objets...\n... Je le savais.",
966:"Y a pas un joueur chat ?! Je veux faire pareil... Tu sais comment ?",
967:"On bosse sur le même fanzine, mais ce qu'il écrit est vraiment osé, tu vois ?",
968:"Enfin, je suis mal placée pour parler... Hahaha.",
969:"Il paraît que les bons objets sont près de la statue Zeit...\n... Je le savais.",
970:"Je suis un chat !\nUn chat pro !\nPas vrai, Beni ?",
971:"La deadline du fanzine approche. Il a intérêt à se dépêcher avec son texte...",
972:"Bon, moi aussi je dois finir mon texte, alors je me tais et je m'y mets.",
973:"Il paraît qu'il y a de meilleurs objets sur les serveurs fermés...\n... Je le savais.",
974:"Il paraît que certains objets ne s'obtiennent que par échange...\n... Je le savais.",
975:"Il paraît que certaines compétences viennent d'objets d'événement...\n... Je le savais.",
976:"... Tu sais...\nThe World, c'est sympa, mais j'aime bien aussi le jeu de chasse au chat...",
977:"Mon objectif !\nConquérir 10 zones en une journée !!",
978:"Je vais à présent me retirer, car je rédige une lettre d'amour pour ma bien-aimée Alicia.",
979:"Veuillez ne point lui révéler mes sentiments véritables. C'est fort gênant.",
980:"Je suis allé dans une zone d'un niveau un peu plus élevé et j'ai été balayé... La route est longue.",
981:"Oooh, les pages web de chats me mettent dans tous mes états...",
982:"On m'a confié un texte pour le fanzine, mais il est devenu osé. Cela ira, j'espère...",
983:"Mais si j'envoie cela, Mutsuki sera furieuse. Je vais user de mes talents de ninja pour l'adoucir.",
984:"J'ai ouï dire qu'il existe un joueur célèbre nommé Orca. J'aimerais jouer avec lui.",
985:"Oh, parfois, quand je croise Alicia et Stare, j'ai des papillons dans le ventre.",
986:"C'est l'amour, je crois.",
987:"Hmm... mes mangas d'oreilles de chat... J'aimerais que le célèbre Orca les lise...",
988:"J'ai perdu mes données quand le serveur a planté.",
989:"Hmmm, comme j'aimerais user de mes talents de ninja pour...",
990:"Oh ! Vous ne devez point écouter cela !",
991:"Mais oui ! Je peux mettre le retard du texte sur le dos du plantage !",
992:"Alors seulement, Mutsuki cessera de se plaindre.",
993:"Le serveur %1 a ouvert, je vais donc jouer sans compter.",
994:"Il semble y avoir bien des problèmes de serveur ces temps-ci...",
995:"Ces hackers sont fort incommodants...",
996:"Je vais jouer avec une ardeur renouvelée !!",
997:"Bonjour !\nJe suis Bell, Lame Jumelle !",
998:"Tu... sais pas qui je suis, hein ? Quoi ? Euh... oh... hum, rien. Je crois que je vais me taire.",
999:"Tu viens de commencer ?\nMoi aussi !",
1000:"Tu regardes beaucoup la télé ? Tu penses quoi des émissions de téléréalité ?",
1001:"Je suis tellement occupée que j'ai pas le temps de Level UP. Ca craint !",
1002:"T'as entendu parler d'Orca ? C'est un joueur super célèbre !",
1003:"T'as vu celle qu'ils ont tournée en Australie ? C'était trop intense !",
1004:"Je dois l'avouer, je suis un peu accro à ces émissions.",
1005:"Quand je suis trop occupée pour jouer, quelqu'un joue mon perso et monte de niveau pour moi.",
1006:"Il est au chômage, alors il a tout son temps.",
1007:"Y a eu plein de problèmes quand le serveur a planté...",
1008:"La session fusée, c'était de la folie ! T'y étais ?",
1009:"Il paraît qu'il y a des cartes à collectionner de ces émissions... Qui achète ça ?!",
1010:"Le serveur %1 est enfin ouvert ! Même si j'ai pas besoin d'y aller, c'est excitant !",
1011:"Tout ce boulot de leveling, perdu à cause des problèmes de serveur !! Je suis furax !!",
1012:"Ces hackers devraient arrêter les problèmes et venir jouer avec moi !",
1013:"Cette fois, ça y est !\nShowtime !",
1014:"Ha !\nQuelle belle patrouille aujourd'hui !",
1015:"Oui chef ! Rien d'autre à signaler, chef !",
1016:"Ha !\nJe me suis donné pour mission de patrouiller pour rendre ce jeu sûr.",
1017:"Ohé, je veux devenir fort comme le Chevalier Pourpre !",
1018:"Ohé, j'adore danser.\nTu sais, la danse cosaque.",
1019:"Ha !\nMon but est de devenir un joueur comme Orca !",
1020:"Ohé, y a un joueur bizarre là où je suis posté... Je veux jamais devenir comme ça.",
1021:"Il devrait prendre exemple sur Orca...",
1022:"Ohé !\nC'est quoi ce... ?!",
1023:"Y a un caillou dans mon burger !!",
1024:"Ha !\nMême un plantage du serveur n'arrête pas ma patrouille...",
1025:"Ohé, le serveur n'a pas planté en salle de réunion. Il a planté dans The World.",
1026:"Ohé ! Le modem câble dépasse la vitesse autorisée. Tous les utilisateurs seront arrêtés !",
1027:"Moi, je suis encore en bas débit...",
1028:"Ha !\nJ'ai étendu ma patrouille maintenant que le serveur %1 est ouvert.",
1029:"Ha !\nTous ces problèmes de serveur, c'est un avertissement ?",
1030:"Ha !\nJ'en reviens pas que des hackers soient derrière tout ça !",
1031:"Ha ! Etrange !\nLa même vieille ville a l'air différente, va savoir pourquoi.",
1032:"Yo !\nCa va ?",
1033:"Hé, si je te parle trop longtemps, mes fans vont s'agiter, tu vois. La règle : 3 minutes par personne.",
1034:"Je veillerai à t'accorder un peu de temps à l'avenir. Prends rendez-vous avec ma secrétaire.",
1035:"Yo, si t'as des questions, demande-moi.",
1036:"J'en ai pas l'air, mais je suis une idole dans The World, tu vois ?",
1037:"Ajoute tu vois à la fin de tes phrases et tu parleras comme moi, tu vois ?",
1038:"Yo, Orca est célèbre, mais pas autant que moi.",
1039:"Balmung est jaloux, c'est moi qu'on regarde maintenant, tu vois ?",
1040:"Ca va se répandre comme une traînée de poudre, tu vois ? Tout le pays va s'y mettre, tu vois ?",
1041:"Yo, les problèmes de serveur, c'est courant dans les jeux en ligne... T'inquiète !",
1042:"Y a eu un événement Entourez Alue. Je suis trop populaire, tu vois ?",
1043:"Tu pourras dire que tu connaissais celui qui a tout lancé, tu vois ?",
1044:"Yo, le serveur %1 est ouvert ! Je vais explorer toute la journée !",
1045:"Yo, y a trop de problèmes de serveur.\nJe vais me faire discret...",
1046:"Yo, je déteste les hackers !!",
1047:"Yo, je suis tout excité quand je viens dans The World !",
1048:"Buongiorno !\nMoi, c'est Alpha Ichigoro !",
1049:"Ah... Moi pas comprendre. Moi étudier ce que toi dire maintenant.",
1050:"Parle à moi plus tard. Moi aller étudier. Ciao.",
1051:"Comment toi aller ?\nMoi, magnifique !",
1052:"En Italie, nous manger pasta tous les jours ! Matin, midi et soir. Pasta, pasta. Toute la journée pasta.",
1053:"Moi né à Roma, mais vivre à Tokyo. Toi connaître Sushi Co. ?",
1054:"Moi préférer les makis de pasta.",
1055:"Oh ! Bravo !\nC'est toi qui étais avec Orca, no ?",
1056:"Prochaine fois, toi et Orca manger spaghetti que moi cuisiner, si ?",
1057:"Sushi, mangia mangia.",
1058:"C'est horrible !\nLe serveur a planté !\nMoi pas rester longtemps.",
1059:"Moi avoir un peu le mal du pays... Comment dire... Ah... OK. Moi OK.",
1060:"Moi espérer que mes parents OK aussi...",
1061:"Moi OK, mais serveur pas OK. Moi manger sushi pour être content. Sushi beurre de cacahuète et confiture !",
1062:"Bravo ! Bravissimo !\nLe serveur %1 est ouvert !\nMa passion brûle de nouveau !",
1063:"Ces temps-ci, moi inquiet. Est-ce qu'on retrouvera le bon vieux temps de The World...",
1064:"Grazie à toi !\nGrazie à VOUS TOUS !",
1065:"Tu veux échanger ?",
1066:"On ne s'ennuie jamais avec toi.",
1067:"J'ai hâte de voir le pouvoir du bracelet aujourd'hui.",
1068:"Onnes en nuit jamé\navek toa.",
1069:"G hat de voar le pou voar\ndu brasse let ojour dui.",
1070:"Yo !\nTu t'es fait au jeu ?",
1071:"T'inquiète.\nJe couvre tes arrières !",
1072:"Quoi, t'as un problème ?",
1073:"T'éloigne pas trop devant.\nT'es faible, je te rappelle.",
1074:"Hé, qu'est-ce qui va pas ?",
1075:"Si t'as des épées, donne-les-moi, d'accord ?",
1076:"Coucou !\nTu veux mon autographe ?",
1077:"Ne me déteste pas parce que je suis belle.",
1078:"Comment te portes-tu ?",
1079:"Reste sur tes gardes, même face aux ennemis faibles.",
1080:"... oh.",
1081:"Je dois devenir... plus fort.",
1082:"Ô toi, Beaux Yeux !\nSouhaites-tu que je te prête mon courage ?",
1083:"Donne-moi tes objets rares, et ma gratitude sera ta récompense !",
1084:"Eh bien,\nque puis-je pour toi ?",
1085:"Nous pourrions faire un échange, si tu veux.",
1086:"Oui, qu'y a-t-il ?",
1087:"Je me demande si Mia s'amuse bien.",
1088:"Oui !\nJe peux t'aider ?",
1089:"J'espère qu'on deviendra bien plus forts !",
1090:"Ouais, un souci ?",
1091:"Puisqu'on est là, j'accepte un cadeau.",
1092:"Quoi ?",
1093:"Je n'ai rien à dire.",
1094:"Oui, que puis-je pour vous ?",
1095:"Grâce à vous, je ne me perds plus.",
1096:"Ouais ?\nQuoi de neuf ?",
1097:"Quoi, tu veux échanger un truc ? Me refile pas de la camelote !",
1098:"Ha ha ha :)\nC'est trop excitant ! ;D",
1099:"Quoi encore ?\nTu veux échanger ?",
1100:"Je peux t'aider ?",
}
