# -*- coding: utf-8 -*-
G={
406:"C'est parce que ce sont des adultes.",
407:"Donnez à ce petit la nourriture que vous avez récoltée.",
408:"Vous l'avez sûrement remarqué, de la nourriture pousse dans chaque zone.",
409:"Récoltez-la sur les terrains et en donjon, puis donnez-la au Grunty.",
410:"Parlez-lui, il vous dira ce qu'il veut. Donnez-lui ce qu'il réclame.",
411:"Il mange tout ce qu'on lui donne, mais impossible de savoir comment il grandira.",
412:"Cela dit, varier les aliments n'est peut-être pas plus mal.",
413:"C'est en mangeant qu'un Grunty devient adulte.",
414:"En grandissant, il grossit et sa façon de parler change.",
415:"Au début ses demandes sont vagues, puis elles se précisent avec l'âge.",
416:"Au début, nourrissez-le, c'est tout.",
417:"Quand ses demandes se précisent, mieux vaut lui donner ce qu'il veut.",
418:["Vénérés comme des êtres divins,","on les appelle les Sitters","dans ce monde."],
419:["Leur nombre a fondu et l'espèce","est jugée menacée."],
420:["Voir un petit est encore plus","rare. Vous avez de la chance","de pouvoir en élever un."],
421:"Merci de jouer à The World.",
422:"Cette zone est actuellement instable : ses données sont corrompues.",
423:"Regagnez immédiatement le terrain et faites Gate Out vers la ville.",
424:"Oh, euh...\nBonjour...",
425:"Euh... j'aime pas trop parler... J'ai rien à raconter.",
426:"Bon... bonjour...\nJ'ai pas l'habitude...",
427:"Tout ça, c'est nouveau pour moi.",
428:"On se moque de moi parce que je suis un peu maladroite.",
429:"Au début, je savais même pas me servir du Chaos Gate.",
430:"Mais un certain Orca m'a montré... faudrait que je le remercie un jour...",
431:"Je savais pas m'équiper, j'ai demandé à Cima, et elle m'a dit de dégager de The World.",
432:"Dans les jeux en ligne, y a des gens cool et des malpolis...",
433:"T'as jamais été retenu à la cantine parce que t'avais pas fini ton assiette ?",
434:"Je détestais les carottes, je les planquais dans mon cartable dès que la maîtresse tournait le dos. Hé hé.",
435:"J'ai été surprise quand le serveur a planté. Je savais pas que ça pouvait arriver.",
436:"Cima... ?! Quoi ? Jamais je lui adresserai la parole ! Haha.",
437:"Le serveur a planté d'un coup et j'ai pété un câble ! Heureusement, personne te voit paniquer.",
438:"On dirait que ça revient à la normale. Je vais pouvoir retourner sur le serveur %1.",
439:"Y a plein de problèmes de serveur en ce moment...\nC'est toujours comme ça ?",
440:"Il paraît que c'est des hackers... Je me demande si ça craint vraiment rien... ?",
441:"En ce moment, je m'éclate vraiment sur ce jeu.",
442:"Salut !\nT'es niveau combien ?",
443:"Quoi ? Tu veux que je te parle de ma muscu ? Plus tard, OK ?",
444:"C'est dur de monter de niveau...\nOu c'est juste moi ?",
445:"J'essaie de faire plus de sport et de rester en forme.",
446:"Je bois des protéines, là, mais c'est infect. Tu connais un truc pour que ça passe mieux ?",
447:"Bref, écoute. Je me dégonfle toujours au moment crucial. C'est quoi mon problème ?",
448:"Un certain Orca m'a sorti d'un sale pétrin une fois...",
449:"Une fois, j'ai suivi un programme de muscu intensif et j'ai fini à l'hôpital.",
450:"J'ai voulu prendre confiance en jouant dans une pièce, mais j'avais un tel trac que j'ai oublié mon texte.",
451:"Le serveur a planté, et mes heures de leveling ont planté avec...",
452:"Je deviens tout en muscles. Mais il paraît que le muscle aux protéines, c'est du faux muscle.",
453:"Si j'arrive pas à monter de niveau en jeu, je monterai en vrai, à la salle...",
454:"%1 a rouvert, alors je vais monter de niveau comme un malade.",
455:"Avec tous ces problèmes, j'ai pas le luxe de monter de niveau...",
456:"C'est sûrement la faute des hackers si mes niveaux montent pas !!!",
457:"Depuis que je fais des groupes avec des amis, le niveau, on s'en fiche. =)",
458:"Hé, tu tiens le coup ?",
459:"Hé, tu veux bien écouter mon accent anglais ?",
460:"Zis iz a pain. Ca sonne comment ?\nOK ?",
461:"T'es un débutant, hein ?\nCa se voit à ta façon de bouger.",
462:"Hé, tu regardes beaucoup d'anime ? Moi, juste de temps en temps.",
463:"T'as vu Supernova cette semaine ? C'est génial ! C'est Kaneto Shiozame qui double le capitaine ?",
464:"Je vais bosser mon anglais, vu que je vais parler à des étrangers en ligne.",
465:"T'as vu Magical Miss Nova ? J'adore quand elle dit Bippity bop en lançant ses sorts.",
466:"Mon anglais s'améliore.\nEcoute !",
467:"Am I a flower ?\nYes. I am.\nTu vois ? Parfait.",
468:"Tu te souviens du dernier plantage ? Surtout, touche pas au bouton reset et reste calme.",
469:"Je regardais Novamon quand le serveur a planté, donc ça allait.",
470:"Je crois que je ferais mieux d'aller étudier à l'étranger.",
471:"Hé, t'es tout pâle...\n... je rigole, c'est le jeu.\n=)",
472:"Ca devient n'importe quoi en ce moment. Tu devrais peut-être arrêter toi aussi.",
473:"T'as entendu ? Il paraît que les derniers problèmes viennent de hackers.",
474:"Hmm ? T'as bonne mine, toi.\nIl t'est arrivé un truc bien ?",
475:"Mais oui...\nC'est le jeu... =)",
476:"J'aimerais bien avoir de bons objets...",
477:"Quand tu entends parler de tous ces drames, tu te dis pas que t'as de la chance d'être là ?",
478:"J'ai jamais de chance...\nPareil pour les zones, on dirait...",
479:"Truc flippant aujourd'hui : 50 chats noirs sont apparus et m'ont fixée. T'en penses quoi ?",
480:"... ? Hé ! T'as un truc sur l'épaule !",
481:"Quoi ? Non, j'ai vu aucun fantôme de guerrier surpuissant !",
482:"Le seul objet rare que j'ai...",
483:"C'est Orca qui me l'a donné...\nJe me demande ce qu'il devient...",
484:"Je crois que je fais partie de ces filles maudites à vie... tu vois ?",
485:"Ouais, c'est ça.\nJe me demande ce qui va encore arriver.",
486:"Tu sais quoi ? Ca reste entre nous... je vois... des fantômes...",
487:"Y a une fille au visage tout blanc derrière toi... !!!",
488:"J'ai perdu mon objet rare quand le serveur a planté...\nLa poisse jusqu'au bout...",
489:"J'espère que le serveur a pas planté à cause de ma poisse... ?! Hé, pourquoi tu détournes les yeux !?",
490:"Ca reste entre nous...\nJe vois... des fantômes...",
491:"Genre, je vois une statue de pierre derrière toi. Hmmm... ça veut dire quoi ?",
492:"Je trouverai peut-être des nouveautés sur le serveur %1...\nPff, tu parles...",
493:"On m'appelle Miss Poisse. La seule chose que j'ai jamais gagnée... c'est une intoxication alimentaire...",
494:"Les virus, ça fait peur...",
495:"Regarde ça !!\nMême avec ma poisse, j'ai eu un objet rare !",
496:"Fini de m'appeler\nMiss Poisse !!",
497:"Yo yo !\nTu t'amuses bien ?",
498:"Hé ! T'es pas la sorcière ! Je me suis fait avoir par ta couleur rouge. Désolé, je file.",
499:"Ce jeu est troooop génial !!\nQuoi ? Non, je suis pas un des programmeurs. =-)",
500:"Ce jeu déchire !\nL'histoire et le design, c'est de la bombe !",
501:"Passe le bonjour à Piros.",
502:"Les zones aléatoires, c'est carrément génial !\nQuel frisson !",
503:"L'autre fois, je suis parti avec une fille, c'était trop réel, mec.",
504:"Notre rencontre, c'est le destin.",
505:"J'ai eu une drôle d'éruption la semaine dernière. Je suis allé chez le médecin : une piqûre d'insecte.",
506:"Fais gaffe où tu traînes, mec.",
507:"Le serveur a planté ?\nM'en fiche.\nCa me va très bien !!",
508:"C'est justement parce que le serveur plante que c'est excitant. Tu captes pas, mec ?!",
509:"Je suis mal. Mes devoirs s'empilent mais je préfère jouer à The World...",
510:"Youhou ! Le serveur %1 est ouvert ! Ca va devenir intéressant !",
511:"Ouais, ça a l'air de chauffer.\nMais bon, ça fait partie du fun !",
512:"Virus ? Hackers ?\nOn s'en fiche !?\nC'est encore plus intéressant !!",
513:"Plus y a de joueurs, plus ce jeu est fun.",
514:"Euh... ça... recom... mence à\n... ra... mer...\nOn... se... re... parle.",
515:"... Désolé... connexion lente...",
516:"Hé, c'est censé être du haut débit...",
517:"Je peux... t'aider... ?\nDésolé... ça va... encore...\nplanter...",
518:"... Ma connexion... est si lente...\n... Me parle... pas...\n... trop...",
519:"Euh... attends...\nTu... me vois... ?\nC'est... trop... lent...",
520:"Ca veut... dire quoi... PING... 3000... ?",
521:"... le serveur a planté... ?\nCa m'arrive... tous les jours...\n... hahahahaha... =(",
522:"Euh... désolé...\nCa a gelé... j'ai dû...\nredémarrer...",
523:"Est-ce que... j'ai l'air... de marcher... normalement... ? On dirait... que je me... téléporte...",
524:"... le serveur %1... est ouvert...\n... 20 minutes... pour\n... recevoir... le mail...",
525:"... c'est... un peu... dingue...",
526:"... les hackers... ça fait... peur...",
527:"J'en reviens pas comme c'est bon de parler à cette vitesse ! Enfin libre !!",
528:"Bonjour !\nQuoi de neuf ?",
529:"Hé ! Je viens de recevoir un mail d'Ushiwaka. Faut que j'y aille.",
530:"Hache Lourde, c'est trop lent ! J'aurais dû prendre Lame Jumelle.",
531:"Tiens, d'ailleurs, Benkei maniait une lance, pas une hache... Je vais refaire mon perso.",
532:"Tu me donnes cet objet ? Je suis Benkei : je collectionne les armes, tu le sais, non ?",
533:"J'ai un ami qui s'appelle Ushiwaka, il est TROP classe. J'aimerais être comme lui.",
534:"Plein de gens me donnent des objets, mais ils servent tous à rien.",
535:"Les attaques ne font rien aux fantômes.",
536:"J'aurais dû prendre de la magie...",
537:"J'ai parlé à Hayate, elle dit que Hache Lourde, c'est classe. Ouais, y a la puissance, mais...",
538:"J'en ai eu une super dans un coffre, mais j'ai dû la laisser au dépôt, je pouvais plus rien porter.",
539:"Une forte tolérance Corps ne protège ni du sommeil ni du charme...",
540:"Si seulement ma tolérance Esprit pouvait monter...",
541:"J'avais que de l'armure d'élément Feu,",
542:"mais ça servait à rien contre le Dalaigon... je vais monter l'élément Eau cette fois...",
543:"J'avais toutes les attaques, mais aucun soin, alors on a abandonné.",
544:"Faut vraiment pouvoir soigner.",
545:"Une Hache Lourde, c'est lent, mais on peut compter dessus.",
546:"Bonsoir.\nComment ça va ?",
547:"... ? J'entends un appel au secours ?! Hayate, la belle Lame Jumelle, arrive. Attends un peu !",
548:"C'est pas un peu faible, Lame Jumelle ? J'aurais dû prendre Lame Lourde.",
549:"Lame Jumelle rugissante... Hayate Beam ! C'est à moi que tu as affaire : Hayate, la belle princesse guerrière !",
550:"Oh... ! T'es là depuis combien de temps ?!",
551:"Hé, attends ! J'ai jamais vu cette arme !",
552:"Ah... si. Je l'ai... t'aimerais pas avoir un truc plus puissant ?",
553:"C'est pas un peu faible, Lame Jumelle ? J'aurais dû prendre Lame Lourde.",
554:"Je veux faire sensation à chaque apparition...",
555:"Mais faut que je monte de niveau avant de tenter une bêtise... Sinon, la honte.",
556:"Tu l'as eue où ? J'en veux une aussi. Hahaha.",
557:"La magie marche jamais très bien sur les Golems...",
558:"J'aurais dû miser sur les compétences d'attaque.",
559:"En discutant avec Benkei, on s'est rendu compte qu'on enviait chacun la classe de l'autre...",
560:"Hé ! T'as une nouvelle arme ?",
561:"Comment t'as eu autant d'armes en si peu de temps ?!",
562:"Même avec une forte tolérance Esprit, je reste sans défense face au poison et à la paralysie.",
563:"Argh ! Comment on monte la tolérance Corps ?",
564:"Zut !!\nLes compétences des armures d'élément Eau ne faisaient rien...",
565:"... contre l'Hydrosaurus !\nJ'y retourne avec l'élément Feu pour ma revanche.",
566:"J'avais plein de sorts de soin, mais ils nous sont tombés dessus à plusieurs et GAME OVER...",
567:"Comme quoi, il faut quand même des compétences d'attaque qui cognent fort.",
568:"Les Lames Jumelles sont faibles, mais rapides !",
569:"Wesh !",
570:"T'aimes les ragots, hein ? Alors attends, je vais avoir une info bien croustillante dans pas longtemps.",
571:"Ca change, hein, avec W3 à fond ? Je pensais que même le patch arrangerait rien.",
572:"CC fait du bon boulot, quand même.",
573:"Trop intense !\nPour moi, c'est genre un combo 100 HIT.",
574:"Le prochain président, je sais pas. Il a l'air de s'y connaître, mais ça m'étonnerait qu'il règle le problème GDO.",
575:"Le gars de %2 qui s'opposait aux deux, Ciel Azur et Mer Azur...",
576:"Il paraît qu'il est remonté à bloc.\nBon, c'est qu'une rumeur.",
577:"T'as lu Game Weekly ? C'est nul ! Voilà pourquoi je déteste la génération BQ.",
578:"Voilà ce qui arrive à force de tirer des rayons sur les gens.",
579:"Le patron de Jyoto Elec. s'est encore fait agresser. Quel idiot se balade avec un million sur lui ?!",
580:"Le truc de l'autre fois... Il paraît que deux gars de la maintenance se sont fait virer.",
581:"Et sinon, quoi d'autre ? Tu commences à te faire des sous ?! Ouais, je parie que oui.",
582:"Madame Cobalt fait pas du tout ses 95 ans ! Toute cette chirurgie a payé...",
583:"Si %1 est ouvert, c'est qu'ils ont serré la vis sur le NEL. Hé, ça sort dans deux mois.",
584:"T'as beau bien connaître PA, ils commenceraient pas plus tôt avec un J only, si ?",
585:"T'as beau bien connaître PA, ils commenceraient pas plus tôt avec un J Only, si ?",
586:"Genre, y a des gens louches derrière CC Corp., mais plus de la moitié sont pas avec W de toute façon ?",
587:"Ils se mélangent pas trop avec les badges blancs. Je parie que 2 ou 3 se sont fait sortir...",
588:"La sécurité doit pleurer toutes les larmes de son corps, avec PD et Ice anéantis...",
589:"Je parie qu'ils regrettent le bon vieux temps des pare-feu...",
590:"Alors, une fusion fracto ?\nJe m'en doutais...",
}
