# -*- coding: utf-8 -*-
G={
76:"dans le Vol. 1.",77:"dans le Vol. 2.",78:"dans le Vol. 3.",
79:"#RLimite atteinte.",
81:"Nombre de zones visitées en",82:"activant le Chaos Gate.",83:"Temps de jeu actuel.",
84:"Portails magiques ouverts",85:"sur les terrains et en donjon.",
86:"Nombre de terrains vidés de",87:"tous leurs portails magiques.",88:"Nombre de donjons vidés de",
89:"Nombre de coffres ouverts sur",90:"les terrains et dans les donjons.",
91:"Caisses, tonneaux, jarres et os",92:"détruits dans les donjons.",
93:"Nombre de coffres de statue",94:"Gott ouverts.",
95:"Nombre de rencontres avec Monsieur",96:"à la Source de Myst.",97:"Nombre de rencontres avec Grandpa",
98:"Nombre de Symboles activés",99:"sur les terrains et en donjon.",
100:"Liste des Grunties élevés.",101:"Aliments de Grunty obtenus",
102:"Le Livre Ryu I va créer un objet.",103:" zones visitées.",104:" de temps de jeu total.",
105:"Le Livre Ryu II va créer un objet.",106:" portails magiques ouverts.",
107:"Le Livre Ryu III va créer un objet.",108:" noms enregistrés.",109:"La liste des noms est complète.",
110:"Echange fait avec tous les joueurs.",
111:"Le Livre Ryu IV va créer un objet.",112:" monstres dans la liste.",113:"La liste des monstres est complète.",
114:"Le Livre Ryu V va créer un objet.",115:"GP en cadeaux.",
116:"Le Livre Ryu VI va créer un objet.",117:" coffres au trésor ouverts.",
118:" caisses, tonneaux, jarres",119:"et os détruits.",120:" coffres de statue Gott ouverts.",
121:"Le Livre Ryu VII va créer un objet.",122:" rencontres avec Monsieur.",123:" rencontres avec Grandpa.",124:" Symboles activés.",
125:"Le Livre Ryu VIII va créer un objet.",126:"Tu as élevé toutes les sortes de",127:"Grunties.",
128:" aliments de Grunty obtenus.",129:"Tu as obtenu tous les aliments",130:"de Grunty.",
133:"Salut !",134:"Oups, pardon !",135:"Merci.",136:"Quoi de neuf ?",137:"Mouais, pas terrible...",
138:"Si seulement j'avais plus de sous...",139:"J'ai beaucoup trop acheté...",140:"C'est parti ! :-)",
141:"Il me faut ça...",142:"Je vais m'en servir ?",143:"J'ai acheté trop de trucs...",
144:"C'est beaucouuup trop cher !",145:"Ca devrait suffire !",146:"Je suis fauché !!!",
147:"Tout ça n'est qu'un rêve...",148:"Un peu cher...",149:"Parfait !",
150:"J'avais déposé quoi, déjà ?",151:"J'ai tout retiré... zut...",152:"Hmmm... :/",
153:"Plus peur du game over !",154:"C'est teeeellement pénible...",155:"Ca va un peu mieux !",
156:"OK, on s'y remet !",157:"Hmm, on va où ?",158:"Désolé pour le retard !",
159:"Hé ! Je suis là !",160:"Il est où ?",161:"Coucou coucou coucou !",162:"Ca roule ?",163:"sa-lut !",
164:"Quelqu'un veut échanger ?",165:"T'as quoi ?",166:"Hmmmmmm...",167:"Des armes et...",
168:"Montre ce que t'as.",169:"T'as des armures ?",170:"Armure de jambes...",171:"On échange ?",
172:"Ca va !",173:"Merci !",174:"Il était fort, cet ennemi...",175:"Ouais, grave...",
176:"On peut battre un truc pareil ?",177:"Il était beaucouuup trop fort !",
178:"Ouais, c'était plié en un instant !",179:"On devrait attaquer autrement ?",
180:"Faudra sûrement se soigner plus souvent...",181:"Ouais...",182:"Et les niveaux ?",
183:"Faut les monter aussi ?",184:"C'est la base d'un RPG !",185:"J'imagine...",186:"Bon, on y va !",
187:"Oh, salut.",188:"Yo !",189:"Bof, ça va.",190:"Je commence enfin à maîtriser le jeu.",
191:"On s'échange nos ID ?",192:"Ouais, vas-y.",193:"On échange.",194:"Alors, ça te dit ?",
195:"Ca me va !",196:"OK, go !",197:"Ca fait un bail !",198:"J'étais pris par le boulot.",
199:"Je compatis...",200:"Bon, je suis de retour !",201:"Moi aussi !",202:"On va où aujourd'hui ?",
203:"Des idées ?",204:"T'as entendu la rumeur ?",205:"Ah, ce donjon-là.",206:"C'est vrai ?",
207:"Hmmmmm... ?",208:"On va voir ?",209:"Je vote pour !",
210:"Je veux des Grunt Mints groin !",211:"Je veux des Oignon vespérals groin !",
212:"Je veux du Snaky Cactus groin !",213:"Je veux du Oh No Melon groin !",
214:"Je veux des Cordyceps groin !",215:"Je veux des White Cherries groin !",
216:"Je veux des Légume racines groin !",217:"Je veux des La Citrouilles groin !",
218:"Je veux des Mushrooms groin !",219:"Je veux des Mandragoras groin !",
220:"Je veux des Pomme de pins groin !",221:"Je veux des Oeuf immatures groin !",
222:"Je veux des Oeuf ours-chats groin !",223:"Je veux des Oeuf invisibles groin !",
224:"Je veux des Oeuf sanglants groin !",225:"Je veux des Golden Eggs groin !",
227:["Draine les données, baisse le niv.","Efficace uniquement sur les","ennemis en #YPROTECT BREAK#W."],
228:"Data Drain sur plusieurs ennemis.",
229:["Data Drain sur un ennemi.","Forte chance d'obtenir un objet","rare."],
231:"Restaure 150 HP.",232:"Restaure 400 HP.",233:"Restaure tous les HP.",
234:["Rend 150 HP à la cible et aux","membres proches."],235:["Rend 400 HP à la cible et aux","membres proches."],
236:["Rend tous les HP à la cible et","aux membres proches."],
237:["Empoisonne la cible.","Les HP baissent avec le temps."],
238:["Paralyse la cible.","Immobilisée un certain temps."],
239:["Ralentit la cible.","Déplacement réduit pendant","un certain temps."],
240:["Charme la cible.","Attaque ses alliés un moment."],
241:["Endort la cible.","Immobilisée un certain temps."],
242:["Sème la confusion chez la cible.","Attaque alliés et ennemis","pendant un certain temps."],
243:["Maudit la cible.","Les SP baissent avec le temps."],
244:"Baisse l'attaque de la cible.",245:"Baisse la défense de la cible.",246:"Baisse la précision de la cible.",
247:"Baisse la magie de la cible.",248:"Baisse la défense magique.",249:"Baisse la précision magique.",
250:["Baisse l'élément Terre de la","cible et des membres proches."],251:["Baisse l'élément Eau de la","cible et des membres proches."],
252:["Baisse l'élément Feu de la","cible et des membres proches."],253:["Baisse l'élément Bois de la","cible et des membres proches."],
254:["Baisse l'élément Foudre de la","cible et des membres proches."],255:["Baisse l'élément Ténèbres de la","cible et des membres proches."],
256:["Harmonise la cible.","Rend des HP avec le temps."],257:["Bénit la cible.","Rend des SP avec le temps."],
258:["Accélère la cible.","Vitesse de déplacement accrue","temporairement."],
259:["Soigne poison, paralysie,","lenteur et baisses de","statut physique."],
260:["Soigne malédiction, sommeil,","confusion, charme et baisses","de statut magique."],
261:"Ranime une cible devenue fantôme.",
262:"Augmente l'attaque de la cible.",263:"Augmente la défense de la cible.",264:"Augmente la précision de la cible.",
265:"Augmente la magie de la cible.",266:"Augmente la défense magique.",267:"Augmente la précision magique.",
268:["Augmente l'élément Terre de la","cible et des membres proches."],269:["Augmente l'élément Eau de la","cible et des membres proches."],
270:["Augmente l'élément Feu de la","cible et des membres proches."],271:["Augmente l'élément Bois de la","cible et des membres proches."],
272:["Augmente l'élément Foudre de la","cible et des membres proches."],273:["Augmente l'élément Ténèbres de","la cible et des membres proches."],
274:"Coincé ?",275:"Restaure les HP à la valeur choisie.",
276:["Harmonise la cible et ses proches.","Rend des HP avec le temps."],
277:["Bénit la cible et les membres","proches.","Rend des SP avec le temps."],
278:["Augmente l'attaque de la cible","et des membres proches."],279:["Augmente la défense de la cible","et des membres proches."],
280:["Augmente la précision de la","cible et des membres proches."],281:["Augmente la magie de la cible","et des membres proches."],
282:["Augmente la défense magique de","la cible et des membres proches."],283:["Augmente la précision magique de","la cible et des membres proches."],
284:"Restaure tous les HP.",285:"Ranime un allié mort.",
286:["Hausse temporaire de","l'#YAttaque physique#W de la cible."],287:["Hausse temporaire de la","#YDéfense physique#W de la cible."],
288:["Hausse temporaire de la","#YPrécision physique#W de la cible."],289:["Hausse temporaire de","l'#YAttaque magique#W de la cible."],
290:["Hausse temporaire de la","#YDéfense magique#W de la cible."],291:["Hausse temporaire de la","#YPrécision magique#W de la cible."],
292:["Hausse temporaire de","l'#YElément Terre#W de la cible."],293:["Hausse temporaire de","l'#YElément Eau#W de la cible."],
294:["Hausse temporaire de","l'#YElément Feu#W de la cible."],295:["Hausse temporaire de","l'#YElément Bois#W de la cible."],
296:["Hausse temporaire de","l'#YElément Foudre#W de la cible."],297:["Hausse temporaire de","l'#YElément Ténèbres#W de la cible."],
298:"Restaure 100 SP.",299:"Restaure 250 SP.",300:"Restaure tous les SP.",301:"Restaure tous les HP et SP.",302:"Restaure 800 HP.",
303:"Poison. Les HP baissent peu à peu.",304:"Paralysie. Immobilisé.",305:"Charme. Attaque ses alliés.",
306:"Sommeil. Immobilisé.",307:["Confusion. Attaque ennemis et","alliés."],308:"Malédiction. Les SP baissent.",
309:["Baisse temporaire de","l'#YAttaque physique#W de la cible."],310:["Baisse temporaire de la","#YDéfense physique#W de la cible."],
311:["Baisse temporaire de la","#YPrécision physique#W de la cible."],312:["Baisse temporaire de","l'#YAttaque magique#W de la cible."],
313:["Baisse temporaire de la","#YDéfense magique#W de la cible."],314:["Baisse temporaire de la","#YPrécision magique#W de la cible."],
315:["Baisse temporaire de","l'#YElément Terre#W de la cible."],316:["Baisse temporaire de","l'#YElément Eau#W de la cible."],
317:["Baisse temporaire de","l'#YElément Feu#W de la cible."],318:["Baisse temporaire de","l'#YElément Bois#W de la cible."],
319:["Baisse temporaire de","l'#YElément Foudre#W de la cible."],320:["Baisse temporaire de","l'#YElément Ténèbres#W de la cible."],
321:"Rend des HP avec le temps.",322:"Rend des SP avec le temps.",
323:["Hausse temporaire de la vitesse","de déplacement."],
324:["Rend 150 HP à la cible et aux","membres proches."],325:["Rend 400 HP à la cible et aux","membres proches."],
326:["Rend tous les HP à la cible et","aux membres proches."],
327:"#Y+30#W aux #YHP maximum#W.",328:"#Y+15#W aux #YSP maximum#W.",329:"#Y+10#W aux #YHP maximum#W.",330:"#Y+5#W aux #YSP maximum#W.",
331:["Désamorce le piège des coffres","piégés."],332:["Quitte le donjon et ramène","sur le terrain."],
333:["Affiche les zones inconnues","de la carte."],
334:["Inutilisable.","A vendre ou à échanger."],
335:["Inutilisable.","Ca sent bon.","A vendre ou à échanger."],
336:["Inutilisable.","Peut servir pour un échange..."],
337:["Inutilisable.","Artisanat traditionnel de Hida.","Peut servir pour un échange..."],
338:["Inutilisable.","Amulette de naissance heureuse.","Peut servir pour un échange..."],
339:["Inutilisable.","Spécialité des sources de Karo.","Peut servir pour un échange..."],
340:["Inutilisable.","Bento de la ligne Takayama.","Peut servir pour un échange..."],
341:["Inutilisable.","Il est écrit : Gagné !","Peut servir pour un échange..."],
342:"Sert à pirater les portails.",343:"Nourriture pour Grunty.",
344:["Lire un fragment de l'Epitaphe","du Crépuscule."],345:"Epitaphe ?",346:"Un message de quelqu'un... ?",
347:"Appelle un Grunty sur le terrain.",
348:["On dirait un badge de limonade","très prisé des gobelins."],
349:["Des éloges griffonnés d'une","écriture de cochon."],
350:["Des os assemblés en croix,","ornés d'un ruban."],
351:["Orné de plumes colorées.","Trop petit pour ta tête."],
352:"Parle de Gardenia sans arrêt.",
354:["Lot de la campagne Power Up","du premier anniversaire."],
355:["Un objet incroyable qui annule","les attaques ennemies !"],
356:["Objet demandé par Wiseman contre","des infos sur l'Epitaphe."],
357:["Objet que veut ANNE.","A quoi ça peut servir... ?"],358:["Objet que veut Bate.","A quoi ça peut servir... ?"],
359:["Objet que veut Catherine.","A quoi ça peut servir... ?"],360:["Objet que veut Dick.","A quoi ça peut servir... ?"],
361:["Objet que possédait Bate.","A quoi ça peut servir... ?"],
362:["Cadeau de la campagne Power Up.","Echangé contre le Livre de la loi."],
363:"Segment d'Aura.",
364:["Livraison. Donne-la à Akai et","échange-la contre le Bonnet jaune !"],365:["Livraison. Donne-la à Aoyama et","échange-la contre le Bonnet jaune !"],
366:["Livraison. Donne-la à Yokota et","échange-la contre le Bonnet jaune !"],
367:["Recense le nombre de zones","visitées et le temps de jeu."],
368:["Recense le nombre de portails","magiques des terrains et","donjons."],
369:["Recense les noms des joueurs","que tu as rencontrés."],370:["Recense les noms des monstres","que tu as combattus."],
371:"Recense tes amis.",
372:["Recense statues Gott, coffres,","caisses, tonneaux, jarres","et os."],
373:["Recense la Source de Myst","et les Symboles."],374:["Recense les Grunties et leur","nourriture."],
375:"Fragment de mémoire.",
376:["Bienvenue.","Ici, c'est le magasin d'armes."],
377:["Les armes et armures équipées","donnent des compétences."],
378:["En achetant de l'équipement,","regardez les compétences autant","que les paramètres."],
379:["Bienvenue. Vous pouvez déposer","ici les objets inutilisés."],
380:["On peut stocker jusqu'à 99","types d'objets différents."],
381:["On peut stocker jusqu'à 99","exemplaires de chaque objet."],
382:["Les objets déposés se retirent","dans n'importe quel Elf's Haven."],
383:["Soyez prévoyant !!","On a plein de remèdes pour","tous vos petits bobos !"],
384:["Partir avec plein de remèdes","de soin, c'est du bon sens."],
385:["Avec des remèdes de SP, plus","besoin de se priver sur les","compétences !"],
386:["Bienvenue !","Des parchemins magiques, ça","vous tente ?"],
387:["Un parchemin ne sert qu'une","fois, mais ne coûte aucun SP !"],
388:["Pensez aussi aux compétences","d'éléments qui vous manquent."],
389:["Bienvenue ! Et si vous","sauvegardiez votre aventure ?"],
390:["Je peux sauvegarder vos données.","Passez me voir souvent pendant","votre aventure."],
391:["Bienvenue au ranch de Grunties","de Dun Loireag."],
392:["Ici, on nourrit les petits du","légendaire Grunty."],
393:["Il a toujours faim. Rapportez-","lui à manger depuis les","zones."],
394:["La Flûte Grunty n'appelle que","le Grunty élevé dans la ville","du serveur où vous êtes."],
395:["En gros, un Grunty élevé sur","le serveur %4 ne s'appelle que","depuis le serveur %4."],
396:["Bienvenue au ranch de Grunties","de Carmina Gadelica."],
397:["En gros, un Grunty élevé sur","le serveur %1 ne s'appelle que","depuis le serveur %1."],
398:["Bienvenue au ranch de Grunties","de Fort Ouph."],
399:["En gros, un Grunty élevé sur","le serveur %2 ne s'appelle que","depuis le serveur %2."],
400:["Bienvenue au ranch de Grunties","de Lia Fail."],
401:["En gros, un Grunty élevé sur","le serveur %3 ne s'appelle que","depuis le serveur %3."],
402:["Vénérés comme des êtres divins,","on les appelle les Sitters","dans ce monde."],
403:["Leur nombre a fondu et l'espèce","est jugée menacée."],
404:["Voir un petit est encore plus","rare. Vous avez de la chance","de pouvoir en élever un."],
405:["Les Grunties qui errent en ville","sont sauvages et ne mangent pas."],
}
