# -*- coding: utf-8 -*-
G={
591:"Comment ça va ?",
592:"Je tourne le dos une seconde pour discuter et ma boîte mail déborde... Attends, je trie tout ça.",
593:"Je viens de commencer ce jeu et je commence enfin à prendre le coup.",
594:"J'espère me faire cent amis.",
595:"Ca se dispute tout le temps dans mon groupe. J'aimerais qu'on s'entende tous.",
596:"C'était pas toi qui marchais avec Orca l'autre jour ?",
597:"Connaître une célébrité pareille, c'est impressionnant.",
598:"Euh... si tu connais Orca, tu dois aussi connaître Balmung ?",
599:"Euh... tu crois que tu pourrais me les présenter ?",
600:"Je crois que mon cousin me déteste. C'est triste, hein ?",
601:"Mais je vais m'en sortir.\nJ'abandonne pas.",
602:"Ca a été pour toi quand le jeu a planté ?",
603:"Mon but, c'est 100 amis ! J'en suis à 38, il m'en reste 62 !",
604:"J'ai su après que le serveur avait planté. J'étais au téléphone à ce moment-là, ça m'a sauvée.",
605:"Je dois une fière chandelle à mon amie !",
606:"C'est génial que le serveur %1 soit de retour, non ?",
607:"C'est génial que le serveur %1 soit de retour, non ?",
608:"Je suis venue, mais le serveur déconne, je crois que j'irai dans aucune zone...",
609:"Ces hackers, j'y crois pas... Répandre des virus partout...",
610:"Contente que les serveurs se portent plutôt bien.",
611:"Bonjour !",
612:"J'espère que les flics écoutent pas notre conversation... Bon, je file. A plus.",
613:"Il est plutôt classe, ton perso !",
614:"C'est qu'un jeu, mais c'est trop bien. J'en savoure chaque minute.",
615:"Les joueurs classes, quel régal à voir.",
616:"J'ai vu deux joueurs vraiment classes. On les appelait les Descendants de Fianna, je crois...",
617:"J'aimerais bien les revoir.",
618:"Trop content qu'il y ait la reconnaissance vocale maintenant. Je détestais ce fichu clavier.",
619:"On s'entraîne en tuant. C'est la règle de conduite de ce monde...",
620:"Il a dû se passer quelque chose.",
621:"Je me demande s'il y a autre chose pour se faire de l'argent...",
622:"Qu'est-ce qu'il y a d'autre dans The World ?",
623:"Je viens de me faire pulvériser. Le serveur %1 est un peu trop fort pour moi... (TT)",
624:"Je me sens un peu trahi avec tous ces problèmes... J'aimais bien ce jeu, avant.",
625:"Ils savent même pas quand %3 reviendra en ligne... J'y crois pas...",
626:"Il est plutôt classe, ton perso !\n... Wouah, déjà-vu...",
627:"Tu sais quoi ?",
628:"Quoi ? Tu veux quoi ? Arrête de me suivre. Je suis occupé.",
629:"Les objets de cette ville sont plutôt nazes.",
630:"Y a des gens vraiment pénibles. C'est quoi le problème de Yuckey ?! Elle me gonfle grave.",
631:"Y a un prof qu'on déteste tous au collège. On verra ce que ça lui fait de se prendre une brosse.",
632:"Y a un autre gars qui parle comme un yakuza. Je parie qu'il livre des journaux.",
633:"Une fille m'a proposé de sortir avec elle. Mais niveau visage, bof... J'espère pas la croiser.",
634:"Les serveurs de The World plantent tout le temps.",
635:"Hé, je parie que c'est sa faute si le serveur a planté. C'est trop bizarre...",
636:"Alors, il se passe quoi ce soir ?",
637:"Ils devraient tous les ouvrir, pas seulement %1...",
638:"Enfin, ils pourraient au moins nous offrir du temps gratuit ou un truc du genre... franchement...",
639:"Ils auraient dû vérifier la sécurité avant que ce virus se répande.",
640:"Je râle pas mal, mais j'aime toujours ce jeu, tu sais.",
641:"Je m'ennuie trop.",
642:"... Pfiou... Je suis crevé, je décolle. Salut.",
643:"... et crevé... faut que je dorme...",
644:"Hé ! Y a l'émission de radio ce soir !",
645:"Tu connais l'émission Talk ON ? C'est troooop drôle. Talk ON !! Trop fort !",
646:"Lalalala. C'était quoi cette chanson ?! Ca fait lalalala...",
647:"Elle tourne en boucle dans ma tête. Mais impossible de retrouver le titre.",
648:"En parlant de radio, ils ont lu ma lettre à l'antenne le week-end dernier. Trop bien, mec !",
649:"Talk ON ! Yeah !",
650:"Lalalala... tu sais, CETTE chanson ?! Tu vois de quoi je parle ?",
651:"C'est le seul passage dont je me souviens.",
652:"Je commence à avoir faim.\nJe crois que je vais y aller...",
653:"Oh non ! Ca va bientôt commencer ! Je file. A plus.",
654:"Reste ON pour toujours, mec !",
655:"Lalalala...",
656:"Oh ! Ca me revient !! Tu sais, c'est le générique de cette émission... elle s'appelait comment ???",
657:"Zut...\nJe crois qu'il est temps de me déconnecter...",
658:"Les serveurs sont instables...\nJe pense à me déconnecter...",
659:"Content qu'ils aient trouvé le problème...\nBon, je me déconnecte...",
660:"Je crois qu'il est temps de partir...\nMais j'arrive pas à m'arrêter...",
661:"Ca me tracasse un peu...",
662:"Tant de questions dans la vie... Pourquoi, pourquoi, pourquoi ? C'est la question infinie.",
663:"Y a toujours du monde ici... Ils font quoi dans la vie, tous... ?",
664:"Pourquoi je monte pas de niveau ? J'ai battu tellement d'ennemis.",
665:"Plein de bateaux passaient sur ce fleuve, et maintenant plus un seul. Il s'est passé quoi ?",
666:"Orca de la Mer Azur... Ca fait un moment que je l'ai pas vu... Je me demande pourquoi.",
667:"J'ai commencé à 8 h du matin et quand j'ai regardé l'heure, il était encore 8 h... Flippant.",
668:"Hé, tu crois que les manches de Balmung sont inspirées d'Elvis ?",
669:"Le serveur a planté y a pas si longtemps... et pourtant y a encore tant de monde...",
670:"Le jour où le serveur a planté, mon couple a planté aussi.",
671:"Hé, les Grunties mangent leurs légumes crus ?\nOh la vache... ?!",
672:"Ils ont ouvert le serveur %1, mais %2 et %3, c'est pour quand ?",
673:"Pourquoi y a sans arrêt des problèmes de serveur... ?",
674:"Avec le virus qui traîne encore, pourquoi y a toujours autant de monde ici ?",
675:"J'ai l'impression que quelque chose a changé... il s'est passé quoi dans The World ?",
676:"Les chats, c'est trop mignon !",
677:"Miaou ! Ah, mes chats m'appellent. Faut que j'y aille.",
678:"J'adore leurs petites pattes...",
679:"Mia-lut ! C'est mon nouveau bonjour.",
680:"T'en penses quoi ? Moitié humain, moitié chat. Plutôt cool, hein ?",
681:"Je te présente mes chats. Maine, un Maine Coon, et Bleu, un Bleu russe. Original, non ?",
682:"Les chats installés au soleil ont toujours l'air si heureux.",
683:"Tous les amoureux des chats vont sûrement l'adopter. Ca va se répandre comme une traînée de poudre.",
684:"Tu crois que ça va prendre ?",
685:"La nuit, les chats pleurent comme des bébés. Un peu flippant ! Mais mignon aussi...",
686:"Mon chat veille avec moi quand je bois un verre. Je sais que c'est pour la bouffe, mais c'est sympa.",
687:"J'ai acheté les meilleurs jouets pour chat ! 100%% poil de chat. J'adore les chats.",
688:"Je veux être plus félin et mignon. Un mec peut porter des oreilles de chat ? T'en as déjà vu ?",
689:"Mon chat me mord tout le temps...\n=)",
690:"Faut jamais donner d'oignon ni de poireau à un chat.",
691:"J'ai l'impression de comprendre ce que disent les chats, ces temps-ci...",
692:"Coucou !\nTu veux échanger ?",
693:"... Quoi ? Rien ?! Je croyais avoir écrit tout le scénario ! J'ai dû rêver !",
694:"Là, ça sent vraiment pas bon. Faut que je m'y mette tout de suite. A plus.",
695:"Quand je bossais au bureau, le dîner était une corvée, mais maintenant que je bosse chez moi...",
696:"... le déjeuner aussi est une corvée...",
697:"Je devrais vraiment pas faire ça. J'ai une deadline à tenir.",
698:"Mais c'est plus fort que moi...\nC'est tellement addictif...",
699:"Hé, tu manges quoi ce soir ? Voyons, hier riz sauté, aujourd'hui curry...",
700:"Hé, attends ! Et un riz sauté au curry ?! Appelle-moi chef Gyokuro, désormais.",
701:"Je bosse chez moi, mais ils ont lancé des travaux, impossible de rien faire en journée...",
702:"Du coup, je bosse la nuit. Et je dors quand, moi ?",
703:"Il paraît que des gens paient en vrai argent pour des objets rares. CC l'interdit... mais bon...",
704:"J'en veux pas à ce point... J'arrive à peine à payer mon loyer... Pourvu que je règle mes factures ce mois-ci...",
705:"Si seulement j'avais une copine, j'aurais pas à manger dehors tout seul...",
706:"Et on pourrait se donner la becquée... C'est si triste de manger seul...",
707:"J'ai un fichu bouton de fièvre.",
708:"Bon, je ferais mieux de retourner bosser.\n...",
709:"OK, encore un niveau...",
710:"Ah oui, j'ai versé du curry sur du riz sauté, un régal. Ca va révolutionner les cartes des restos.",
711:"J'aurais dû apprendre la cuisine. Tu crois qu'il est trop tard pour devenir chef ?",
712:"Tu connais un bon resto de ramen ?",
713:"J'avais un super poil de nez que je gardais, mais je l'ai perdu... Je fais quoi, moi ?",
714:"Tu détestes pas quand ton nez te gratte alors que t'es dehors ?",
715:"Hé hé hé,\nj'ai une copine.\nJe l'ai rencontrée ici.",
716:"Bonjour !\n... ou bon après-midi ?",
717:"Je devrais pas en parler... c'est vraiment gênant. Et ça va aller de pire en pire...",
718:"L'été, je rêve du froid mordant de l'hiver.",
719:"Et l'hiver, le soleil brûlant de l'été me manque... Je suis capricieuse... ?",
720:"Je te jure que j'avais plein de sous là-dedans, et mon portefeuille est presque vide...",
721:"T'as jamais rêvé de scènes comme ça ?",
722:"Parfois je fais une sieste et je finis par dormir toute la journée.",
723:"L'hiver, je mange de la glace à côté du chauffage...",
724:"Et l'été, du ragoût brûlant sous la clim...\nC'est mal... ?",
725:"Ouais, comme quand tu cherches un truc et qu'il est dans ta main.",
726:"Je suis allée faire les courses hier, mais j'avais inversé mes chaussures.",
727:"Je suis allée au resto, j'arrivais pas à choisir, et après j'ai oublié ce que j'avais commandé...",
728:"Parfois j'oublie le petit-déj, je me dis que je me rattraperai à midi, et je mange rien du tout.",
729:"Ecoute ça, je suis si romantique... Je lève les yeux vers le ciel d'été rempli...",
730:"... de feux d'artifice, et je m'arrête pour toucher les flocons qui tourbillonnent dans le ciel d'hiver...",
731:"T'as déjà passé une nuit blanche à chercher un souvenir, puis dormi toute la journée ?",
732:"T'as déjà cru perdre une lentille pour découvrir que t'avais les deux dans le même oeil ?",
733:"L'autre jour, le distributeur m'a sorti une canette de jus d'orange bien chaude...",
734:"Ca t'arrive pas de finir avec un curry en voulant faire un ragoût ? ... ou c'est que moi ?",
735:"Salut !\nTu t'es habitué au jeu ?",
736:"Euh... faut que j'aille aux toilettes. On se reparle plus tard.",
737:"Les mots-clés aléatoires, c'est pratique, mais attention, on peut tomber dans une zone de haut niveau.",
738:"Au début, mieux vaut utiliser des mots qui permettent de contrôler le niveau.",
739:"T'as des animaux ? Moi j'ai une chatte, elle est adorable !!",
740:"... Oh non ! J'ai oublié de la nourrir !!! Salut !!",
741:"J'enchaîne les nuits blanches sur ce jeu. Je tourne à l'adrénaline pure.",
742:"T'as des animaux ? Moi j'ai un chat.",
743:"J'ai parlé chats avec Meowman l'autre jour. Tu me trouves grave ?! Essaie de lui parler, à lui !",
744:"J'essaie de battre le record. 48 heures non-stop ! Je sais pas combien de temps je vais tenir, par contre.",
745:"Parfois je vois un truc bizarre dans le ciel...\nTu sais ce que c'est ?",
746:"Le plantage, encore, ça allait, mais j'ai dû tout réinitialiser et repartir de zéro... Tant pis...",
747:"C'était dur pour moi aussi de jouer toute la nuit... mais The World, c'est tellement fun !",
748:"Pour manier des armes puissantes, il faut monter de niveau.",
749:"Sauvegarder, ça évite les drames quand le chat appuie sur reset...",
750:"Je joue plus qu'une heure par jour !\n... à partir de demain =-)",
751:"Hé, quoi de neuf ?",
752:"Je galère à écrire ma nouvelle chanson. Les rimes tombent mal. Je vais laisser reposer un peu.",
753:"Au début, fais le plein de parchemins, vu que t'as pas beaucoup de compétences.",
754:"Je me suis mis au rap.\nCa détend bien.\nCheck, check it out.",
755:"J'ai vécu un an en Russie. Je parle un peu russe, je t'apprendrai un jour.",
756:"Sauvegarder souvent au Recorder, c'est du bon sens.\nOh m$rde ! J'ai des devoirs !",
757:"Mais je débute, alors on me laisse pas scratcher ni toucher aux platines.",
758:"QUOI ?!\nRappeur et DJ, c'est pas pareil ?!",
759:"Le mot russe du jour.\nVodka. Pas mal, hein ?",
760:"Plus russe que ça, y a pas.",
}
