# descriptions des competences (2e ligne et suivantes) ; cle = texte anglais
SK={
"Continuously slash at high speed.":["Enchaîne les coups à grande vitesse."],
"Spin like a top and slash at / high speed.":["Tournoie comme une toupie en","frappant à grande vitesse."],
"Slash at high speed like a dance.":["Frappe à grande vitesse en dansant."],
"Continuously slash at high speed / with blades in flame.":["Enchaîne les coups à grande","vitesse, lames enflammées."],
"Lightning strikes while slashing / at high speed.":["La foudre s'abat pendant les","coups à grande vitesse."],
"Continuously slash at high speed / with blades in darkness.":["Enchaîne les coups à grande","vitesse, lames de ténèbres."],
"Slash diagonally, and then slash / diagonally from the other side.":["Taille en diagonale, puis en","diagonale de l'autre côté."],
"Jump and strike down from head / to toe.":["Saute et fend l'ennemi de la","tête aux pieds."],
"Somersault forward and strike / down.":["Salto avant suivi d'un coup","vers le bas."],
"Quick draw attack dicing the / opponent in a flash.":["Dégaine éclair qui découpe","l'adversaire en un instant."],
"Powerful attack above and below / the waist.":["Attaque puissante au-dessus et","au-dessous de la taille."],
"Spin the blade and strike down / with force.":["Fait tournoyer la lame et","l'abat avec force."],
"Hold the weapon parallel and / spin side-ways.":["Tient l'arme à l'horizontale","et tournoie sur le côté."],
"Swing the axe. / Range increases with level.":["Balaie avec la hache.","Portée accrue avec le niveau."],
"Wide range damage from tremors / and boulders.":["Dégâts de zone par secousses","et rochers."],
"Spin the spear in one hand and / slash repeatedly.":["Fait tournoyer la lance d'une","main et frappe à répétition."],
"Slash parallel to the ground. / Range increases with level.":["Fauche à l'horizontale.","Portée accrue avec le niveau."],
"Drop stone on the target.":["Lâche une pierre sur la cible."],"Drop stones on the target.":["Lâche des pierres sur la cible."],
"Drop boulders on the target.":["Lâche des rochers sur la cible."],"Generate a tornado.":["Génère une tornade."],
"Raise stone columns below the / target.":["Dresse des colonnes de pierre","sous la cible."],
"Summon Yarthkins.":["Invoque Yarthkins."],
"Generate a tornado with ice / blocks.":["Génère une tornade de blocs","de glace."],
"Ice blocks converge on the / target.":["Des blocs de glace convergent","sur la cible."],
"Raise ice columns below the / target.":["Dresse des colonnes de glace","sous la cible."],
"Summon Merrows.":["Invoque Merrows."],
"Drop a fire ball on the target.":["Lâche une boule de feu sur la cible."],"Drop fire balls on the target.":["Lâche des boules de feu sur la cible."],
"Generate a tornado with fire.":["Génère une tornade de feu."],
"Fire balls converge on the / target.":["Des boules de feu convergent","sur la cible."],
"Summon Vulcan.":["Invoque Vulcan."],"Generate a tornado with leaves.":["Génère une tornade de feuilles."],
"Tree branches converge on the / target.":["Des branches convergent","sur la cible."],
"Raise trees below the target.":["Dresse des arbres sous la cible."],"Summon Krake.":["Invoque Krake."],
"Drop lightning on the target.":["Abat la foudre sur la cible."],"Generate a tornado with plasma.":["Génère une tornade de plasma."],
"Thunder balls converge on the / target.":["Des boules de foudre convergent","sur la cible."],
"Summon Lanceor.":["Invoque Lanceor."],"Drop a skull on the target.":["Lâche un crâne sur la cible."],
"Drop skulls on the target.":["Lâche des crânes sur la cible."],"Skulls converge on the target.":["Des crânes convergent sur la cible."],
"Creatures of darkness converge / on the target.":["Des créatures des ténèbres","convergent sur la cible."],
"Raise dark claws below the / target.":["Dresse des griffes sombres","sous la cible."],
"Summon Wryneck.":["Invoque Wryneck."],"Summon Black Cat Gang!":["Invoque le Black Cat Gang !"],
"Summon master bomber from / another dimension.":["Invoque le maître artificier","d'une autre dimension."],
"Summon a giant goblin!":["Invoque un gobelin géant !"],
}
G={}
