# -*- coding: utf-8 -*-
G={
1347:"Oh, très cher ?\nAuriez-vous besoin de moi ?",
1348:"Oh, très cher ! Merci ! Grâce à vous, me voilà devenu un parfait gentleman.",
1349:"Pour vous remercier de vos tendres soins, je tiens à vous offrir ceci, très cher !",
1350:"Utilisez ceci sur le terrain pour m'appeler, très cher !",
1351:"Je paierai ma dette envers vous, très cher !",
1352:"Bien que je sois désormais un gentleman... cette ville n'a nul besoin de deux Noble Grunties.",
1353:"Adieu !\nMerci, très cher !",
1354:"Oh, très cher !\nSouhaitez-vous échanger contre mon trésor ?",
1355:"Si vous m'adorez, vous m'offrirez du grandiose, n'est-ce pas ?",
1356:"Très cher ! Très cher !\nHahaha !!!",
1357:"... Pardonnez-moi.",
1358:"... Je pensais à Fersen...\nAu fait, qui êtes-vous ?",
1359:"Comparé à Marie-Antoinette, vous n'êtes rien. Vous la servirez pour l'éternité.",
1360:"Et moi de même ! AHAHAHAHAHA !",
1361:"Oh, très cher ! Mille mercis ! Grâce à vous, me voilà devenu un parfait gentleman.",
1362:"Je me dois de payer ma dette envers vous, très cher !",
1363:"Maître ?\nQue puis-je pour vous, clang !",
1364:"Oh, maître ! Merci infiniment ! Grâce à vous, j'ai fini de grandir, clang !",
1365:"Pour vos tendres soins, veuillez accepter ceci, clang !",
1366:"Utilisez-le sur le terrain pour m'appeler, clang !",
1367:"Je dois payer ma dette envers vous, clang !",
1368:"J'ai fini de grandir, mais cette ville n'a pas besoin de deux Iron Grunties, clang !",
1369:"Je vous remercie clang !\nAdieu, clang !",
1370:"Maître...\nVous m'avez manqué clang !\nOn échange, clang ?",
1371:"Un jour...\nJe veux encore courir sur le terrain avec vous, clang !",
1372:"Mon maître...\nMon dos n'est pas un scarabée, clang !",
1373:"Oh, maître...\nMon armure me vient de mon ancien maître, clang !",
1374:"Maître ?\nQu'y a-t-il, coâ ?",
1375:"Oh, maître ! Merci coâ ! Grâce à vous, je suis devenu adulte, coâ !",
1376:"Pour vous remercier de m'avoir élevé, prenez ceci, coâ !",
1377:"Utilisez-le sur le terrain pour m'appeler, coâ !",
1378:"Je dois payer ma dette envers vous, coâ !",
1379:"Je suis adulte, mais cette ville n'a pas besoin de deux Poison Grunties, coâ !",
1380:"Au revoir, coâ !\nMerci, coâ !",
1381:"Maître ?\nVous êtes bien rouge aujourd'hui, coâ !\nOn échange, coâ ?",
1382:"Je suis tout seul, coâ...\nPersonne ne veut être mon ami, coâ.",
1383:"En quoi suis-je différent des autres, coâ ?",
1384:"Malgré moi, je vois plein, plein de choses, coâ !",
1385:"Je vous observe toujours, maître, coâ !",
1386:"Parlez-moi plus, coâ... Maître, vous ne m'aimez pas, coâ ?",
1387:"Ohh, maître ! Merci, coâ ! Grâce à vous, je suis adulte, coâ !",
1388:"Maître ? Qu'y a-t-il, clac !?",
1389:"Maître ! Merci, clac ! Grâce à vous, j'ai grandi, clac !",
1390:"Pour vous remercier de m'avoir élevé, je vous donne ceci, clac !",
1391:"Utilisez-le sur le terrain pour m'appeler, clac !",
1392:"Je dois payer ma dette envers vous, clac !",
1393:"J'ai grandi, clac. Mais cette ville n'a pas besoin de deux Boney Grunties, clac.",
1394:"Au revoir, clac.\nMerci, clac.",
1395:"Je vous échange un objet riche et onctueux contre un bien épais et délicieux, clac !",
1396:"Mon corps tout en os est rempli de rêves, clac !\nClac ?",
1397:"Même s'il ne reste que mes os, ils se réaliseront, clac !\nClac ?",
1398:"Quoi qu'il arrive, j'aurai toujours mes os, clac !",
1399:"On échange, clac ?",
1400:"Ca vous va, clac ?\nOK, clac !",
1401:"Vous voulez encore échanger, clac ?",
1402:"On échangera encore un de ces jours, clac !",
1403:"Chef ?\nQu'y a-t-il, ssss !",
1404:"Chef ! Merci, ssss ! Grâce à vous, j'ai fini de grandir, ssss !",
1405:"Pour vous remercier de m'avoir élevé, je vous donne ceci, ssss !",
1406:"Utilisez-le sur le terrain pour m'appeler, ssss !",
1407:"Je travaille très bien pour vous, ssss !",
1408:"J'ai fini de grandir, mais cette ville n'a pas besoin de deux Snakey Grunties, ssss !",
1409:"Au revoir, ssss !\nMerci, ssss !",
1410:"Echangeons mes jolies choses contre les jolies choses du chef, ssss !",
1411:"Je suis...\nUn petit diable, ssss !",
1412:"On va où ?\nAllons-y ensemble, ssss !",
1413:"Ssss...",
1414:"Trop bruyant, ssss ?\nJe ne sais parler que comme ça, ssss !",
1415:"Chef !! Merci, ssss ! Grâce à vous, j'ai fini de grandir, ssss !",
1416:"Je travaille bien pour vous, ssss !",
1417:"Vous voulez échanger, ssss ?",
1418:"Ca vous va, ssss ?\nOK ssss !",
1419:"Encore un échange, ssss ?",
1420:"A la prochaine, ssss !",
1421:"Roi Rouge ?\nBesoin de quelque chose, gloup gloup ?",
1422:"Roi Rouge, merci, gloup gloup ! Grâce à vous, j'ai mûri, gloup gloup !",
1423:"Pour vous remercier de m'avoir élevé, je vous offre ceci, gloup gloup !",
1424:"Utilisez-le sur le terrain pour m'appeler, gloup gloup !",
1425:"Je dois payer ma dette envers vous, gloup gloup !",
1426:"J'ai mûri, mais cette ville n'a pas besoin de deux Aqua Grunties, gloup gloup !",
1427:"Au revoir, gloup gloup !\nMerci, gloup gloup !",
1428:"Echangeons l'objet du Roi Rouge contre cet objet qui flotte en mer, gloup gloup !",
1429:"Mon coeur est aussi pur que mon corps, gloup gloup...",
1430:"Ma vie ne sera pas une écume à la dérive, je vivrai avec fougue, gloup gloup !",
1431:"Les vagues... je pousse, puis je tire... je tire, puis je pousse... gloup gloup...",
1432:"... ce n'est pas mon genre.",
1433:"Je partirai à mon heure, gloup gloup !",
1434:"Que voulez-vous échanger ?\nGloup gloup ?",
1435:"Ca vous va, gloup gloup ?\nOK, gloup gloup !",
1436:"Encore un échange, gloup gloup ?",
1437:"On remettra ça, gloup gloup !",
1438:"Baby !\nIl te faut quoi ?",
1439:"Merci, baby ! Grâce à toi, je suis devenu tout grand, baby !",
1440:"Même si je suis qu'un gamin des bas-fonds... t'as été sympa, baby ! Prends ça, baby !",
1441:"Utilise-le sur le terrain et appelle-moi quand tu veux, baby !",
1442:"Le samedi soir, une fois lancé, personne m'arrête, baby !",
1443:"Je suis devenu tout grand... mais baby, pas besoin de deux Rocker Grunties, baby !",
1444:"Salut, baby ! Mon petit coeur en sucre !",
1445:"Et si on échangeait mon âme en feu contre ce que t'as de chaud, baby ?",
1446:"Bien chaud, baby...",
1447:"Je brûle, baby...",
1448:"Je prends feu, baby...",
1449:"Tu échanges quoi, baby ?",
1450:"Ca te va, baby ?\nOK, baby !",
}
