# -*- coding: utf-8 -*-
G={
1101:"Ca change agréablement.",1102:"Bien, allons-y.",
1103:"Yo !\nAttends, j'arrive !",1104:"Oh, ça va...\nDu calme !",1105:"Ah, c'est toi.\nAttends une minute.",
1106:"Tu veux jouer avec moi, hein ? Super ! J'arrive tout de suite !",
1107:"Compte sur moi.",1108:"... J'arrive.",
1109:"Oyez ! Beaux Yeux !\nPartons ensemble à l'aventure !",
1110:"Tiens, bonjour.\nDonne-moi un instant.\nJ'arrive.",
1111:"Euh... d'accord.",1112:"Merci de m'avoir choisie !\nJe ferai de mon mieux !",
1113:"Merci de l'invitation.\nAujourd'hui, je fais fortune !",1114:"C'est toi.\n... Je suis en route.",
1115:"Merci infiniment de m'avoir invitée aujourd'hui.",
1116:"OK, j'arrive !",1117:"Ca marche, j'arrive !",1118:"Amusons-nous un peu.",1119:"Bi1, alon zy.",
1120:"Oh ?\nT'as changé d'avis ?",
1121:"Je le savais, je le savais.\nT'es perdu sans moi, hein ?",
1122:"Hé, décide-toi une bonne fois, tu veux ?",
1123:"Quoi ?\nT'as besoin de moi, finalement ?",
1124:"Ouais, ouais !\nToujours partant !",
1125:"Aurais-tu changé d'avis ?\nSoit... je n'y vois pas d'objection.",
1126:"... Encore ?",1127:"Tu as donc besoin de moi, finalement ! Mais bien sûr !",
1128:"Changement de plan ?\nSois sûr de tes décisions.",
1129:"Oh ? On y retourne ?\nBon, ça me dérange pas...",
1130:"Oui ! Compris !\nFaisons de notre mieux !",
1131:"Hein ? On y retourne ?\nCa me va.",1132:"On y retourne ?\n... D'accord.",
1133:"Encore une fois, donc ?\nAvec grand plaisir.",
1134:"Quoi ?\nT'as peur d'y aller sans moi ?",
1135:"Hm ? Une autre aventure ?\nChouette. Je voulais encore jouer.",
1136:"Oh ?\nTu as encore besoin de moi ?",
1137:["O ?","Tachan gé da vi ?","0"],
1138:"On s'est bien amusés aujourd'hui.\nA la prochaine... peut-être.",
1139:"A plus !\nSois pas en retard en cours !",
1140:"A plus !\nJe reviendrai peut-être avec toi un de ces jours.",
1141:"Merci pour tout.\nA bientôt !",1142:"Salut !\nOn remet ça !",
1143:"Rappelle-moi si tu as besoin d'aide. Adieu !",1144:"... Adieu.",
1145:"Splendide aventure !\nAdieu, Beaux Yeux !",
1146:"Une aventure fort profitable.\nRéinvite-moi donc.",
1147:"Merci pour aujourd'hui.\nBon, ben, salut...",
1148:"Merci beaucoup !\nRéinvite-moi, s'il te plaît !",
1149:"Hmm, pas gagné grand-chose...\nLa prochaine fois, on devient riches !",
1150:"Hmph ! Bien. Adieu.",1151:"Merci pour aujourd'hui.\nPrenez soin de vous.",
1152:"Ciao !\nAppelle-moi direct quand tu repars !",
1153:"Bye bye. :)\nC'était super sympa aujourd'hui.",1154:"Bon, à bientôt.",
1155:"Onses bi1 a muzé ojour dui.\nA la proch N... peu têtre.",
1156:"Hmmm...\nAlors, c'est quoi ce truc ?",1157:"Merci !\nJ'accepte volontiers.",
1158:"Merci !\nT'es vraiment quelqu'un de bien.",
1159:"On dirait que tu sais exactement ce qu'il me faut.",
1160:"Merci...\nCa me gêne un peu de te remercier comme ça.",
1161:"Bon...\nOK, je prends.",1162:"Merci, mec !\nJe prends !",
1163:"Plutôt généreux de ta part. C'est un objet super cool. Merci !",
1164:"Wow, quelle chance !\nPile ce qu'il me fallait.",
1165:"T'es sûr que je peux l'avoir ?\nLa vache ! Merci, mec !",
1166:"Ouais, c'est ça.\nJe suis censé en faire quoi ?!",
1167:"Si tu le donnes, je prends.",1168:"Vraiment...\nT'es un sacré gars.",
1169:"Espèce d'idiot ! Jamais je pourrai te rendre la pareille.",
1170:"Zut...\nFaut bien que je le dise...\nM... merci...",
1171:"Bon, je prends...\nMais c'est de la camelote...",
1172:"Hé, merci !",1173:"Merci.\nJe m'en servirai.",
1174:"Whoa, ça, ça va me servir.\nMerci !",
1175:"J'aimerais savoir mieux te montrer ma gratitude... Merci beaucoup.",
1176:"Hé, attends !\nJe vais en faire quoi ?",1177:"OK !\nJe prends !",
1178:"Hé, merci.\nCa sert toujours, ces trucs.",
1179:"Génial !\nC'est pas donné, ça, tu sais !\nMerci beaucoup !",
1180:"Ooooh ! Génial !\nJe le voulais trop !\nJe te... revaudrai ça !",
1181:"... Très bien.\nJe le prends.",1182:"Hm, merci.",1183:"Merci !\nJ'accepte.",
1184:"Merci pour un objet si rare. J'en prendrai le plus grand soin.",
1185:"Un objet aussi précieux ?! Merci. Je l'accepte en gage de notre amitié.",
1186:"... hmm",1187:"... Merci.",1188:"... Tu as mes remerciements.",
1189:"... Merci.\nJe te suis très reconnaissant.",
1190:"Merci...\nJe n'oublierai jamais ce jour.",
1191:"... Je trouverai peut-être un usage à cet objet, un jour...",
1192:"Oh, merci, Beaux Yeux !",
1193:"Sois remercié, Beaux Yeux !\nTa bonté me touche !",
1194:"Splendide ! Sois remercié. Tu es le plus grand des amis !!",
1195:"Wouah, quel objet délicieux ! Tu es assurément l'ami ultime !!",
1196:"Entendu.\nJe le prends pour l'instant.",
1197:"Merci.\nJe suis sûr qu'il sera utile.",
1198:"Pas mal, cet objet.\nJ'en ferai bon usage.",
1199:"Quel objet ! Je ne peux qu'admirer ta générosité.",
1200:"C'est... un objet incroyable ! Merci ! Je te revaudrai ça, sois-en sûr.",
1201:"Je... euh... hum...\nMerci.",
1202:"Euh... je peux vraiment l'avoir ?\n... Merci.",
1203:"Je peux vraiment l'avoir gratuitement ?\n... Merci beaucoup.",
1204:"Oh, wow !\nUn si bel objet...\nMerci infiniment.",
1205:"Merci... Je suis si contente. On... on ne m'offre pas souvent de cadeaux.",
1206:"Oh, merci beaucoup.",1207:"Merci beaucoup !\nJe ferai de mon mieux !",
1208:"Quelle délicate attention !\nMerci beaucoup !",
1209:"Un objet si précieux...\nJe peux vraiment l'avoir ?\nMerci infiniment.",
1210:"Quel objet merveilleux !\nMerci beaucoup !\nJe le chérirai toujours !",
1211:"Hmm ?\nSi tu me l'offres, je prends.",1212:"Oh, merci.\nJe prends.",
1213:"Ca tombe bien ! J'en cherchais justement un.",
1214:"Oh, merci.\nT'es sûr que je peux prendre un si bel objet ?",
1215:"Oh wow !\nVraiment superbe, cet objet !\nMerci mille fois !",
1216:"Hmph ! Je le prends.",1217:"Reçu !\nJe m'en servirai !",
1218:"Plutôt bon objet.\nIl devrait servir.",1219:"Un objet coûteux.\nMerci.",
1220:"Hm, un objet merveilleux ! J'accepte ta sincérité avec ce présent.",
1221:"Merci beaucoup.",1222:"Merci beaucoup.\nJe le garderai précieusement.",
1223:"Merci beaucoup.\nJe suis très heureuse !",
1224:"Un merveilleux cadeau.\nMerci beaucoup.\nJ'en prendrai grand soin !",
1225:"Quel merveilleux cadeau !\nMerci infiniment.\nVous me comblez de joie !",
1226:"Hein ?\nC'est quoi, cet objet ?",1227:"Ouais, je prends.\nMerci.",
1228:"Hé, tu lis dans mes pensées. C'est pile ce que je voulais.",
1229:"Wow, c'est gentil.\nCelui-là, je le garde.",
1230:"T'es sûr que je peux l'avoir ?\nJe, euh... hum...\n... Merci.",
1231:"Hmmm... :/\nJe sais pas trop ce que c'est, mais je prends, j'imagine.",
1232:"Merci !\nJe prends. :)",1233:"Oh, wow !\nMerci !\nHé hé, veinarde que je suis ;)",
1234:"Oh là là ! :D\nJe le voulais trop, celui-là.\nMerci beaucoup !",
1235:"Non ! Tu me le donnes ?\nOuaiiiis ! :*\nUn de plus pour la collection !",
1236:"Tu pourrais être un peu plus attentionné quand tu fais un cadeau.",
1237:"Quel cadeau mignon.",1238:"Merci.\nJ'accepte.",
1239:"Oh !\nUn objet si coûteux.\nEh bien, merci.",
1240:"Attends-tu quelque chose en échange de ce précieux objet ? Je me le demande...",
1241:"Pfff mmm...\nAlor sékoa ce tru Kk ?",
1242:"Mer si !\nJak 7 vol on tié.",
1243:"Mer si !\nTé vré man kel kun 2 bi1.",
1244:"On di ré ke tu C pil ce\nkil me fo.",
1245:["Mer si...","Sa me gên 1 peu 2 te re mer","sié kom sa."],
1246:"Je m'appelle Johnny, le Grunty errant.",
1247:"Si je m'arrête, je meurs.",1248:"Arrête de me parler !",
1249:"Je t'ai jamais vu dans le coin.",1250:"T'es... qui ?",
1251:"T'as déjà entendu parler du Grunty rockeur ?",
1252:"C'était le plus rapide de notre tribu.",
1253:"Si tu le croises, passe-lui le bonjour.",
1254:"Moi c'est Sal, le Grunty errant, pardi.",
1255:"C'est-y vous qu'élevez des p'tiots dans l'étable là-bas ?",
1256:"C'est les miens, pardi. Z'avez intérêt à ben les élever !",
1257:"L'air de c'te ville, l'est pur et ben propre.",
1258:"Pas vrai ?",
1259:"Le Grunty de fer, ça vous cause ?",
1260:"C'est point grave sinon. Allez, oubliez ça.",
1261:"Genre, je m'appelle Lottel, le Grunty errant ?",
1262:"Genre, j'aime bien traîner par ici ?",
1263:"Donc genre, laisse-moi tranquille, OK ?",
1264:"Genre, les gens ici savent pas se détendre ?",
1265:"Ils devraient genre marcher moins vite, tu crois pas ?",
1266:"Genre, t'as déjà entendu parler du Grunty osseux ?",
1267:"Ah ouais ? Bah genre, tant pis.",
1268:"Je m'appelle Suzie, le Grunty errant.",
1269:"J'adore cette ville.\nPourquoi, tu demandes ?",
1270:"Hé hé hé...\nCa te regarde pas.",
1271:"Ca te dérange ?\nTu regardes quoi, au juste ?",
1272:"Regarde tant que tu veux, je n'échangerai pas avec toi.",
1273:"Tu connais le Grunty aqua ?",
1274:"Non, tu dis ?\nBon, laisse tomber.",
1275:"Papa ! J'ai faim groin !",1276:"Trop faim, je mangerais de tout !",
1277:"J'ai faim groin !\nDonne-moi à manger, groin !",
1278:"Je veux manger un truc mentholé, groin !",
1279:"Ca pousse près d'une tête carrée toute brûlante groin !",
1280:"Je veux manger un truc cru et piquant, groin !",
1281:"Ca pousse près d'une arme bizarre très vieille, groin !",
1282:"Je veux manger un truc juteux, groin !",
1283:"Ca pousse près de côtes qui étaient un océan avant, groin !",
1284:"Je veux manger un truc tout rond et très sucré, groin !",
1285:"Ca pousse près d'une bernacle, groin !",
1286:"Je veux manger un truc froid et piquant, groin !",
1287:"Ca pousse près d'un grand bouddha, groin !",
1288:"Je veux manger un truc froid et très sucré, groin !",
1289:"Ca pousse près d'un pilier tout glacé, groin !",
1290:"Je veux manger un truc blanc et piquant, groin !",
1291:"Ca pousse près d'un mur au bout d'un labyrinthe, groin !",
1292:"Je veux manger un truc très sucré, groin !",
1293:"Ca pousse près d'un gros cocon, groin !",
1294:"Je veux manger un truc qui me fait grandir, groin !",
1295:"Ca pousse à l'ombre d'un rocher champignon, groin !",
1296:"Je veux manger un truc qui fait du bruit, groin !",
1297:"Ca pousse près d'une tour pointue, groin !",
1298:"Je veux manger un truc croquant et sucré, groin !",
1299:"Ca pousse au fond de la forêt verte, groin !",
1300:"Je veux manger un truc très amer, groin !",
1301:"Ca pousse au fond d'un labyrinthe tout noir, groin !",
1302:"Je veux manger un truc très acide, groin !",
1303:"Ca pousse au fond d'une galerie très chic, groin !",
1304:"Je veux manger un truc très salé, groin !",
1305:"Ca pousse dans une grotte très profonde, groin !",
1306:"Je veux manger un truc au goût de sang, groin !",
1307:"Ca pousse dans le ventre d'un monstre très effrayant, groin !",
1308:"Je veux manger un truc très cher, groin !",
1309:"Y en a qui poussent dans une histoire importante, groin !",
1310:"Père ! J'ai faim, groin !",1311:"J'ai si faim, je mangerais de tout !",
1312:"J'ai faim, groin !\nDonne-moi à manger,\ngroin !",
1313:"Je veux des Grunt Mints, groin !",
1314:"Ca pousse près d'une tête carrée brûlante, groin !",
1315:"Je veux des Oignon vespérals, groin !",
1316:"Ca pousse près d'une arme étrange et très ancienne, groin !",
1317:"Je veux du Snaky Cactus, groin !",
1318:"Ca pousse près de côtes qui furent un océan, groin !",
1319:"Je veux du Oh No Melon, groin !",
1320:"Ca pousse près des bernacles, groin !",
1321:"Je veux des Cordyceps, groin !",
1322:"Ca pousse près d'une grande statue de Bouddha, groin !",
1323:"Je veux des White Cherries, groin !",
1324:"Ca pousse près d'un pilier glacial, groin !",
1325:"Je veux des Légume racines, groin !",
1326:"Ca pousse près d'un mur au bout du labyrinthe, groin !",
1327:"Je veux des La Citrouilles, groin !",
1328:"Ca pousse près d'énormes cocons, groin !",
1329:"Je veux des Mushrooms, groin !",
1330:"Ca pousse à l'ombre des rochers champignons, groin !",
1331:"Je veux des Mandragoras, groin !",
1332:"Ca pousse près des tours pointues, groin !",
1333:"Je veux des Pomme de pins, groin !",
1334:"Ca pousse au fond des forêts vertes, groin !",
1335:"Je veux des Oeuf immatures, groin !",
1336:"Ca pousse au fond d'un labyrinthe très sombre, groin !",
1337:"Je veux des Oeuf ours-chats, groin !",
1338:"Ca pousse au fond d'une galerie très chic, groin !",
1339:"Je veux des Oeuf invisibles, groin !",
1340:"Ca pousse dans une grotte très profonde, groin !",
1341:"Je veux des Oeuf sanglants, groin !",
1342:"Ca pousse dans le ventre d'un monstre très effrayant, groin !",
1343:"Je veux des Golden Eggs, groin !",
1344:"Quelques-uns poussent dans une histoire importante, groin !",
1345:"... !?\nIl se passe quelque chose !",
1346:"Son corps est en train de changer. Il devient adulte !",
}
