# -*- coding: utf-8 -*-
"""Noms de monstres, PNJ/boutiques, objets du decor, competences, parchemins. Noms propres et mots inventes : inchanges."""
# --- monstres (0x6aec00-0x6b0c00), 17 caracteres max ---
MON={
"Gladiator":"Gladiateur","Nobunaga Soul":"Ame de Nobunaga","Phalanx":"Phalange","Dark Rider":"Cavalier noir","Dark Horse":"Cheval noir","Nightmare":"Cauchemar",
"Tetra Armor":"Armure tétra","General Armor":"Armure générale","Mummy Ripper":"Momie éventreuse","Mummy Scissors":"Momie ciseaux","Temple Night":"Chevalier temple",
"Holy Night":"Chevalier saint","Hand of God":"Main de Dieu","Cadet Valkyrie":"Valkyrie cadette","Fresh Valkyrie":"Valkyrie novice","Long Lived":"Longue vie",
"Grand Mage":"Grand mage","Grand Cold":"Grand froid","Grand Electric":"Grand électrique","Forest Hsien":"Hsien des bois","Dark Guru":"Gourou noir",
"Earth Hsien":"Hsien de terre","Ancient":"Ancien","Evil Horn":"Corne maléfique","Rich":"Liche","Rich Lord":"Seigneur liche","Dark Lord":"Seigneur noir",
"Flamer":"Incendiaire","Fire Witch":"Sorcière de feu","Water Witch":"Sorcière d'eau","Dark Witch":"Sorcière noire","Hysteria":"Hystérie","Druid Witch":"Sorcière druide",
"Mad Witch":"Sorcière folle","Earth Maiden":"Vierge de terre","Spark Maiden":"Vierge étincelle","Dark Maiden":"Vierge noire","Wood Maiden":"Vierge des bois",
"Flame Maiden":"Vierge de flamme","Madam Niagara":"Madame Niagara","Guardian":"Gardien","Metal Eraser":"Gomme de métal","Metal Emperor":"Empereur métal",
"House Golem":"Golem maison","Earthman Drill":"Foreur terrien","Mu Guardian":"Gardien Mu","Nega Guardian":"Gardien Nega","Spin Figure":"Figurine toupie",
"Drill  Idol":"Idole foreuse","Chicken Hand":"Main de poulet","Wood Harpy":"Harpie des bois","Death Crane":"Grue de mort","Harpy Queen":"Reine harpie",
"Phoenix Queen":"Reine phénix","Aurora Feather":"Plume d'aurore","Rainbow Tail":"Queue arc-en-ciel","Psyche Vision":"Vision psyché","Monkey Crab":"Crabe singe",
"Snip Snap":"Clic-clac","Crab Turtle":"Tortue crabe","Red Scissors":"Ciseaux rouges","Squilla Demon":"Démon squille","Hell Slicer":"Coupeur d'enfer",
"Mantis":"Mante","Scorpion Tank":"Tank scorpion","Shield Man":"Homme bouclier","Shield Devil":"Diable bouclier","Wander Demon":"Démon errant",
"Astro King":"Roi astral","Ark Prince":"Prince de l'arche","Watcher":"Guetteur","Stare":"Regard","Death Glare":"Regard mortel","Necrotic Eye":"Oeil nécrosé",
"Rock Head":"Tête de roc","Mystery Rock":"Roc mystère","Easter Rock":"Roc de Pâques","Sand Hill":"Dune","Sand Mountain":"Mont de sable","Stone Tuttle":"Tortue de pierre",
"Gaia Turtle":"Tortue Gaia","Minnow":"Vairon","Sky Fish":"Poisson céleste","Arrow Fish":"Poisson flèche","Star Fish":"Poisson étoile","Smiley Ray":"Raie souriante",
"Big Eyes":"Gros yeux","Cyclo Shark":"Requin cyclope","Hammer Shark":"Requin marteau","Star Eater":"Mange-étoiles","Dark Starfish":"Astérie noire",
"Goblin":"Gobelin","Hob Goblin":"Hobgobelin","Goblin Night":"Chevalier gobelin","Metal Goblin":"Gobelin de métal","Gob Machine":"Machine gob",
"Magical Goblin":"Gobelin magique","Goblin Wiz":"Gobelin sorcier","Voodoo Goblin":"Gobelin vaudou","Cannibal":"Cannibale","Starving Ogre":"Ogre affamé",
"IronBall Mania":"Fana du boulet","IronBall Freak":"Dingue du boulet","IronBall Titan":"Titan du boulet","Little Doggie":"Petit toutou","Sled Dog":"Husky",
"Great Sled Dog":"Grand husky","Sled Dog King":"Roi husky","Hell Doberman":"Doberman d'enfer","Hell Hound":"Chien d'enfer","Hades Hound":"Chien d'Hadès",
"Flame Heads":"Têtes de flamme","Black Death":"Mort noire","Wiggle Snake":"Serpent ondulant","Statue Menhir":"Menhir statue","Sphinx Menhir":"Menhir sphinx",
"Fiend Menhir":"Menhir démon","Limp Knife":"Couteau mou","Disco Knife":"Couteau disco","Lambada Knife":"Couteau lambada","Dust Curse":"Poussière maudite",
"Cursed Blades":"Lames maudites","Sword of Chaos":"Epée du chaos","Armor Shogun":"Armure shogun","Armor General":"Général en armure","Armor Evil":"Armure maléfique",
"Dragon Puppy":"Bébé dragon","Lead Snakoid":"Chef Snakoid","King Snakoid":"Roi Snakoid","Green Wyrm":"Wyrm vert","Brown Wyrm":"Wyrm brun","Red Wyrm":"Wyrm rouge",
"Blue Wyrm":"Wyrm bleu","Parasite Dragon":"Dragon parasite","Twinkle Grass":"Herbe étoilée","Mad Grass":"Herbe folle","Hungry Grass":"Herbe affamée",
"Snappy Grass":"Herbe mordante","Thousand Trees":"Mille arbres","Scarlet King":"Roi écarlate","Hackberry King":"Roi micocoulier","Mushroom King":"Roi champignon",
"Charmer":"Charmeuse","Lamia Fighter":"Lamia guerrière","Lamia Hunter":"Lamia chasseuse","Lamia Assassin":"Lamia assassine","Killer Snaker":"Snaker tueur",
"Jealous Cobra":"Cobra jaloux","Neptune Medusa":"Méduse Neptune","Fake Money":"Fausse monnaie","Hell Box":"Boîte d'enfer","Killer Box":"Boîte tueuse",
"Deadly Present":"Cadeau mortel","Pandora's Box":"Boîte de Pandore","Death Head":"Tête de mort","Nomadic Bones":"Os nomades","Bone Army":"Armée d'os",
"Skull Hero":"Héros crâne","Living Dead":"Mort-vivant","Undead Voodoo":"Zombie vaudou","Headhunter":"Chasseur de têtes","Headhunt Lord":"Maître des têtes",
"Headless King":"Roi sans tête","Ominous Skull":"Crâne funeste","Wiggly":"Tortillon","Deadly Moth":"Papillon mortel","Phantom Wing":"Aile fantôme",
"Moonlighter":"Noctambule","Bee Army":"Armée d'abeilles","Bee Assault":"Abeille d'assaut","Bee Commando":"Abeille commando","Baby Worm":"Bébé ver",
"King Worm":"Roi ver","Miasma Wyvern":"Wyverne miasme","Mugai Wyvern":"Wyverne Mugai","Demon Wyvern":"Wyverne démon","Ectoplasm":"Ectoplasme",
"Noisy Wisp":"Follet bruyant","Pumpkin Head":"Tête citrouille","Pumpkin King":"Roi citrouille","Specter":"Spectre","Dark Stalker":"Traqueur noir",
"Shining Eyes":"Yeux brillants","Astro Prince":"Prince astral","Time Visitor":"Visiteur du temps","Dejected":"Abattu","Conqueror":"Conquérant",
"Death Implant":"Implant mortel","Star Viking":"Viking stellaire","Dark Asteroid":"Astéroïde noir","Inis Illusion":"Illusion d'Inis","Magus Leaf":"Feuille de Magus",
"Cubia Core":"Noyau de Cubia",
}
# --- PNJ, boutiques, Grunty, objets du decor (0x6b0c00-0x6b2200) ---
NPC={
"Weapon Shop":"Armurerie","Item Shop":"Magasin d'objets","Magic Shop":"Magasin de magie","Grunt Shop":"Boutique Grunty","Administrator":"Administrateur",
"Cossack Leader":"Chef cosaque","Silver Knight":"Chevalier Argent",
"Noble Grunty":"Grunty noble","Iron Grunty":"Grunty de fer","Poison Grunty":"Grunty poison","Bony Grunty":"Grunty osseux","Snakey Grunty":"Grunty serpent",
"Aqua Grunty":"Grunty aqua","Milky Grunty":"Grunty laiteux","Rocker Grunty":"Grunty rockeur","Woody Grunty":"Grunty boisé","Little Grunty":"Petit Grunty",
"Grunty the Kid":"Grunty le Kid",
"Treasure":"Trésor","Risky Treasure":"Trésor piégé","Wooden Box":"Caisse en bois","Barrel":"Tonneau","Virus Crystal":"Cristal viral","Jar":"Jarre","Urn":"Urne",
"Skeleton":"Squelette","Warrior's Body":"Corps de guerrier","Egg":"Oeuf","Small Eggs":"Petits oeufs","Magic Portal":"Portail magique","Symbol":"Symbole",
"Spring of Myst":"Source de Myst","Zeit Statue":"Statue Zeit",
}
# --- competences (0x6b2180-0x6b85e0), 15 caracteres max ---
SKILL={
"Saber Dance":"Danse du sabre","Tiger Claws":"Serres du tigre","Staccatto":"Staccato","Flame Dance":"Danse de flamme","Blazing Wheel":"Roue ardente",
"Twin Dragons":"Duo de dragons","Red Flame":"Flamme rouge","Flame Vortex":"Vortex de feu","Dragon Rage":"Rage du dragon","Orchid Dance":"Danse orchidée",
"Splinter Slash":"Coupe en éclats","Gale of Swords":"Rafale d'épées","Orchid Strike":"Frappe orchidée","Wildflower":"Fleur sauvage","Typhoon Blade":"Lame typhon",
"Thunder Dance":"Danse foudre","Thunder Coil":"Spire de foudre","Lightning Rage":"Rage d'éclair","Storm Strike":"Frappe d'orage","Tempest Strike":"Frappe tempête",
"Storm Rage":"Rage d'orage","Dark Dance":"Danse sombre","Swirling Dark":"Tourbillon noir","Twin Darkness":"Double ténèbres","Darkness Slash":"Entaille sombre",
"Terror Cyclone":"Cyclone terreur","Evil Twin":"Jumeau du mal",
"Cross Slash":"Entaille croix","Crack Beat":"Fracas rythmé","Death Bringer":"Porte-mort","Calamity":"Calamité","Triple Wield":"Triple moulinet",
"Brandish":"Brandir","Triple Doom":"Triple ruine","Repulse Cage":"Cage répulsive","Double Sweep":"Double balayage",
"Meooow":"Miaaaou","Summon Goblin":"Appel gobelin","More Goblins":"Renfort gobelin","Goblin King":"Roi gobelin","King of Goblin":"Sire gobelin",
"2128 Drain multiple enemies.":"2128 Drain sur plusieurs ennemis.",
}
# competences hybrides : prefixe invente + mot anglais -> mot francais + prefixe
SUFFIX={"Slash":"Entaille","Crack":"Fracas","Revolver":"Revolver","Spiral":"Spirale","Smash":"Choc","Drive":"Percée","Divider":"Diviseur","Maxima":"Maxima",
"Break":"Brisure","Tornado":"Tornade","Basher":"Cogneur","Rampage":"Ravage","Punish":"Châtiment","Doom":"Ruine","Repulse":"Repousse","Wipe":"Balayage",
"Vortex":"Vortex","Vortext":"Vortex","Tempest":"Tempête"}
# --- parchemins et objets restants (0x6b85e0-0x6bec20), 15 caracteres max ---
ITEM2={
"Raining Rocks":"Pluie de rocs","Raging Earth":"Terre enragée","Stone Storm":"Orage de pierre","Gaia's Spell":"Sort de Gaia","Meteor Strike":"Frappe météore",
"Cosmic Truth":"Vérité cosmique","Ice Storm":"Orage de glace","Ice Floe":"Banquise","Ice Strike":"Frappe de glace","Absolute Zero":"Zéro absolu",
"Permafrost":"Pergélisol","Fire Tempest":"Tempête de feu","Meteor Swarm":"Essaim météore","Flame Blast":"Souffle ardent","Fireball Storm":"Pluie de feu",
"Hellstorm":"Orage infernal","Inferno Strike":"Frappe inferno","Green Gale":"Rafale verte","Gale Breath":"Souffle rafale","Leafblight":"Feuille flétrie",
"Wood Sprite":"Esprit des bois","Jungle Rage":"Rage de jungle","Forest of Fear":"Forêt d'effroi","Lightning Bolt":"Eclair","Plasma Storm":"Orage plasma",
"Ion Strike":"Frappe ionique","Raging Plasma":"Plasma enragé","Thunderbolt":"Coup de foudre","Plasma Gale":"Rafale plasma","Nightblight":"Nuit flétrie",
"Dark Night":"Nuit noire","Dark Traitor":"Traître noir","Chaos Spell":"Sort du chaos","Nightfear":"Peur nocturne","Nightshade":"Belladone",
"Summon Earth":"Invoque Terre","Summon Water":"Invoque Eau","Summon Fire":"Invoque Feu","Summon Wood":"Invoque Bois","Summon Thunder":"Invoque Foudre",
"Summon Night":"Invoque Nuit","Stonecall":"Appel de pierre","Aquacall":"Appel d'eau","Infernocall":"Appel d'enfer","Greencall":"Appel vert",
"Thundercall":"Appel foudre","Nightcall":"Appel de nuit",
"Secret: Might":"Secret : Force","Secret: Rigid":"Secret : Rigide","Secret: Awaken":"Secret : Eveil","Secret: Reason":"Secret : Raison",
"Secret: Divine":"Secret : Divin","Secret: Thief":"Secret : Voleur","Secret: Sage":"Secret : Sage","Secret: Dreams":"Secret : Rêves",
"3-Floor Tower":"Tour 3 étages","Memory fragment.":"Fragment de mémoire.",

}
# --- remplacements sur place (chaines sans pointeur propre) : adresse -> texte, limite = place disponible ---
INPLACE_A={
0x6a4038:"Livre Ryu I",0x6a4050:"Zones visitées :",0x6a4070:"Temps :",0x6a4080:"Livre Ryu II",0x6a4090:"Portails magiques ouverts :",
0x6a40b0:"Terrains sans portail :",0x6a40d0:"Donjons sans portail :",0x6a40f0:"Livre Ryu III",0x6a4100:"Liste de noms :",0x6a4110:"Total des échanges :",
0x6a4130:" inscrits.",0x6a4148:" échanges.",0x6a4158:"",0x6a4160:" échanges avec ",0x6a4170:"Actif",0x6a4178:"Objets échangés",
0x6a4190:"  : détails.",0x6a41b0:"  : retour.",0x6a41c8:"Livre Ryu IV",0x6a41d8:"Monstres :",0x6a41e8:"Total : ",0x6a41f8:" monstres inscrits",
0x6a4210:"dans la liste des monstres.",0x6a4230:"Vaincu ",0x6a4240:" fois.",0x6a4248:"Nom : ",0x6a4250:"Données",0x6a4258:"Niveau",0x6a4270:"Compét.",
0x6a4278:"Objets",0x6a4280:"Aucun",0x6a4290:"Data Drain : impossible",0x6a42b0:"Data Drain : attaques efficaces.",0x6a42e0:"Data Drain : magies efficaces.",
0x6a4310:"Dernière victoire :",0x6a4350:"Livre Ryu V",0x6a4360:"Total des cadeaux",0x6a4380:"Total des cadeaux : ",0x6a43a0:"Cadeaux : ",
0x6a43b0:"Temps en groupe : ",0x6a43d0:"Affection : ",0x6a43e8:"Livre Ryu VI",0x6a4400:"Coffres ouverts :",0x6a4420:"Caisses, os, etc. brisés :",
0x6a4440:"Coffres de Statue Gott :",0x6a4460:"Livre Ryu VII",0x6a4470:"Sources de Myst trouvées",0x6a4490:"Rencontres avec Monsieur :",
0x6a44b0:"Rencontres avec Grandpa :",0x6a44d0:"Symboles activés :",0x6a44f0:"Rencontrés à ce jour : ",0x6a4510:"Livre Ryu VIII",0x6a4520:"Liste Grunty",
0x6a4530:"Nourriture Grunty",0x6a4548:"Nom",0x6a4550:"Elevés",0x6a4560:"Total nourriture Grunty :",0x6a4580:" aliments au total.",0x6a4598:" obtenus.",
0x6a45b0:"Actuel : ",0x6a45c0:"dans le Vol. 1.",0x6a45d0:"dans le Vol. 2.",0x6a45e0:"dans le Vol. 3.",0x6a45f0:"#RLimite atteinte.",
0x6a4610:"Plus aucun objet à créer",0x6a4640:" est ajouté au bureau.",0x6a4678:"#GVidéo ",0x6a4690:"#R(Débloqué en fin de jeu.)",
0x6a46b0:"Nombre de zones visitées",0x6a46d0:"via la Chaos Gate.",0x6a46f0:"Temps de jeu actuel.",0x6a4710:"Portails magiques ouverts",
0x6a4730:"sur terrains et donjons.",0x6a4750:"Terrains vidés de",0x6a4770:"tous leurs portails magiques.",0x6a4790:"Donjons vidés de",
0x6a47b0:"Coffres au trésor ouverts",0x6a47e0:"sur terrains et donjons.",0x6a4800:"Caisses, fûts, jarres et os",0x6a4820:"détruits dans les donjons.",
0x6a4840:"Coffres de Statue Gott",0x6a4860:"ouverts.",0x6a4870:"Rencontres avec Monsieur",0x6a48a0:"à la Source de Myst.",0x6a48c0:"Rencontres avec Grandpa",
0x6a48f0:"Symboles activés",0x6a4910:"sur terrains et donjons.",0x6a4930:"Liste des Grunty élevés.",0x6a4950:"Nourriture Grunty obtenue.",
0x6a4970:"Le Livre Ryu I crée un objet.",0x6a4990:"Plus de ",0x6a49a0:" zones vues.",0x6a49b0:" de jeu au total.",0x6a49d0:"Le Livre Ryu II crée un objet.",
0x6a4a00:" portails magiques ouverts.",0x6a4a20:" terrains vidés de",0x6a4a40:" donjons vidés de",0x6a4a60:"Le Livre Ryu III crée un objet.",
0x6a4a90:" noms inscrits.",0x6a4ab0:"Liste de noms complète.",0x6a4ad0:"Echanges faits avec tous les joueurs.",0x6a4b00:"Le Livre Ryu IV crée un objet.",
0x6a4b30:" monstres dans la liste.",0x6a4b50:"Liste des monstres complète.",0x6a4b70:"Le Livre Ryu V crée un objet.",0x6a4b90:"GP en cadeaux.",
0x6a4ba0:"Le Livre Ryu VI crée un objet.",0x6a4bd0:" coffres au trésor ouverts.",0x6a4bf0:" caisses, fûts, jarres",0x6a4c10:"et os détruits.",
0x6a4c30:" coffres de Statue Gott.",0x6a4c50:"Le Livre Ryu VII crée un objet.",0x6a4c80:" rencontres avec Monsieur.",0x6a4ca0:" rencontres avec Grandpa.",
0x6a4cc0:" Symboles activés.",0x6a4ce0:"Le Livre Ryu VIII crée un objet.",
0x6e0140:"Infos de zone",0x6e06a8:"#W !",0x6e06c8:"#W ?",
0x6e1540:"#RLoin du sol brisé par la Vague,#W",0x6e1567:"#Rla fille d'ombre murmure :#W",0x6e1588:"#R\"Je reviendrai, assurément.\"#W",
0x6e15b0:"#RHélas, la vérité ignorée#W",0x6e15d1:"#Rl'attend au terme du voyage :#W",0x6e15f4:"#Rle deuil éternel de sa terre.#W",
0x6f0120:"Terre",0x6f0128:"Eau",0x6f0130:"Feu",0x6f0138:"Bois",0x6f0140:"Foudre",0x6f0148:"Ténèbres",
}
# --- textes absents de la premiere extraction (symboles speciaux, bulles de groupe) : anglais -> francais ---
GT={
"It seems the vibe went away and / I'm a normal girl now.<8199>":"On dirait que la magie est passée,\nje suis une fille normale.<8199>",
"It seems the vibe went away and / I'm a normal girl now<8199>":"On dirait que la magie est passée,\nje suis une fille normale<8199>",
"Oh my, what is it, darling<819a>?":"Oh là là, qu'y a-t-il, chéri<819a> ?",
"Oh darling! Thank you<819a>! / Thanks to you, I'm all grown / up now<819a>!":"Oh chéri ! Merci<819a> !\nGrâce à toi, me voilà toute\ngrande<819a> !",
"Oh my, now I can respond to / darling's luv<819a>! / Take this<819a>!":"Oh là là, je peux enfin répondre\nà l'amour de mon chéri<819a> !\nPrends ça<819a> !",
"Oh my, use that in the field to / call me<819a>!":"Oh là là, sers-t'en sur le\nterrain pour m'appeler<819a> !",
"Oh my, I'll repay my debt and / then some<819a>!":"Oh là là, je te revaudrai ça\nau centuple<819a> !",
"Although I'm all grown up now... / There's no room for two Milky / Grunties! Thank you<819a>.":"J'ai beau être toute grande...\nPas de place pour deux Grunty\nlaiteux ! Merci<819a>.",
"But this isn't goodbye<819a>.":"Mais ce n'est pas un adieu<819a>.",
"Oh my, would you like to trade, / darling<819a>?":"Oh là là, tu veux échanger,\nchéri<819a> ?",
"Darling, I love you!! / Hee hee hee hee...<819a>":"Chéri, je t'aime !!\nHi hi hi hi...<819a>",
"Darling, if you cheat on me, I'll / hit you with the super-ultra / mega-atomic smash! Got it<819a>?!":"Chéri, si tu me trompes, c'est\nle super-ultra-méga-coup\natomique ! Compris<819a> ?!",
"Darling, take me out, won't you<819a>? / Oh my, why I'd go anywhere if / it's with you, darling<819a>.":"Chéri, tu m'emmènes<819a> ?\nOh là là, j'irais n'importe où\navec toi, chéri<819a>.",
"Thank you, darling<819a>! / Thanks to you, I'm all grown up<819a>!":"Merci, chéri<819a> !\nGrâce à toi, je suis grande<819a> !",
"Oh my, what shall we trade<819a>?":"Oh là là, on échange quoi<819a> ?",
"Is this OK<819a>? / OK<819a><8149>":"Ca te va<819a> ?\nOK<819a><8149>",
"Oh my, want to trade again<819a>?":"Oh là là, encore un échange<819a> ?",
"Oh my, next time<819a>!":"Oh là là, à la prochaine<819a> !",
"I see":"Je vois","0ooooK ;)":"0ooooK ;)","You gotta save 'em SP":"Faut économiser les SP","Recovering your HP-":"Je te rends des HP-",
"Tell me during battle":"Dis-le-moi en combat","Oooooooooooh thanx ;D":"Oooooooooooh merki ;D","Let's have some fun ;)":"On va bien s'amuser ;)",
"Noooooooooooooo :'(":"Noooooooooooooon :'(","Let's play again :D":"On rejoue bientôt :D","But I can't :'(":"Mais je peux pas :'(","I got hit *sniff*":"Je suis touchée *snif*",
}
