# -*- coding: utf-8 -*-
"""Noms d'armes (anglais -> francais), 15 caracteres max. Noms propres et noms japonais absents d'ici : inchanges."""
NAMES={
# --- lames jumelles ---
"Amateur Blades":"Lames d'amateur","Steel Blades":"Lames d'acier","Phantom Blades":"Lames fantômes","Spark Blades":"Lames étincelle",
"Lath Blades":"Lames de latte","Fuse Blades":"Lames à mèche","Shadow Blades":"Lames d'ombre","Cats Blades":"Lames de chat","Ronin Blades":"Lames de ronin",
"Spell Blades":"Lames de sort","Bloody Blades":"Lames de sang","Masterblades":"Lames maîtres","Hell's Gate":"Porte d'enfer","Dante's Blades":"Lames de Dante",
"Slayers":"Tueuses","Professional":"Professionnel","Specter Blades":"Lames spectres","Stealth Blades":"Lames furtives","Black Chapter":"Chapitre noir",
"Sorcery Swords":"Epées sorcières","Diablo Blades":"Lames Diablo","Miracle Twin":"Jumeaux miracle","Tiger King":"Roi tigre","Spiral Edge":"Lame spirale",
"Blades of Bond":"Lames du lien","Moon Knives":"Dagues de lune","Lady Killers":"Tombeurs","Time Blades":"Lames du temps","Rusty Nails":"Clous rouillés",
"Soul Blades":"Lames d'âme","Gemini Soul":"Ame Gémeaux","Vampire Blades":"Lames vampires","Crimson Raid":"Raid écarlate","Sin of Hades":"Péché d'Hadès",
"Fishskin":"Peau écaillée","Golden Yasha":"Yasha d'or","Two Together":"Deux ensemble","Prepare to Die":"Fais ta prière",
# --- épées (Maître Lame) ---
"Basic Sword":"Epée simple","Brave Sword":"Epée du brave","Strange Blade":"Lame étrange","Executioner":"Bourreau","Unicorn Blade":"Lame licorne",
"Corpseblade":"Lame cadavre","Oval Sword":"Epée ovale","Grunty's Sword":"Epée de Grunty","Souleater":"Mangeuse d'âme","Singing Blade":"Lame chantante",
"Dogman's Sword":"Epée de Dogman","Steelblade":"Lame d'acier","Glitter":"Eclat","Seal Sword":"Epée du sceau","Patriot":"Patriote","Comet Blade":"Lame comète",
"Demon Killer":"Tue-démon","Lion's Blade":"Lame du lion","Menhir Sword":"Epée menhir","Bloody Pain":"Peine sanglante","Phantom Blade":"Lame fantôme",
"Rising Sun":"Soleil levant","Banished Blade":"Lame bannie","Pegasus Comet":"Comète Pégase","Seventh Seal":"Septième sceau","Fair Soul":"Ame juste",
"Stream Sword":"Epée du courant","Honor's Breath":"Vent d'honneur","Scarlet Cross":"Croix écarlate","Godslayer":"Tue-dieux","Needleblade":"Lame aiguille",
"Gold Sword":"Epée d'or","Trickster":"Farceur","Saturn Sword":"Epée Saturne","Mercury Sword":"Epée Mercure","Mars Sword":"Epée Mars",
"Phantom Pain":"Douleur fantôme","Skysweeper":"Balaie-ciel","Rugrats Nights":"Nuits Razmoket","Evil Eyes":"Mauvais oeil","Eternity":"Eternité",
"Ends of Earth":"Bout du monde","Heavenly Sword":"Epée céleste","Phoenix's Wing":"Aile du phénix","Chaos Sword":"Epée du chaos","Phoenix's Fire":"Feu du phénix",
"Gimme Life":"Donne la vie","Maniac Sword":"Epée maniaque",
# --- lames lourdes ---
"Adventurer":"Aventurier","Earth Sword":"Epée de terre","Curing Sword":"Epée de soin","Green Sword":"Epée verte","Stun Sword":"Epée K.-O.","Slayer":"Tueuse",
"Defense Sword":"Epée de défense","Magnifier":"Amplificateur","Absorber":"Absorbeur","Sharp Blade":"Lame acérée","Spiderblade":"Lame araignée",
"Sun Fang One":"Croc solaire 1","Sun Fang Five":"Croc solaire 5","Sun Fang Zero":"Croc solaire 0","The Sun Fang":"Le Croc solaire","Devil Blade":"Lame du diable",
"Earthian Sword":"Epée terrienne","Life Sword":"Epée de vie","Flame Sword":"Epée de flamme","Dryad's Sword":"Epée de dryade","Light Giver":"Porte-lumière",
"Pain Giver":"Porte-douleur","Horse-Killer":"Tue-cheval","Blessed Blade":"Lame bénie","Soul Linker":"Lieuse d'âmes","Stonecrusher":"Brise-pierre",
"Sonic Blade":"Lame sonique","Sharktooth":"Dent de requin","Ghostdancer":"Danse fantôme","High Forger":"Grand forgeron","Peace Blade":"Lame de paix",
"Corona Blade":"Lame corona","Forest Sword":"Epée de forêt","Plasma Blade":"Lame plasma","Executer":"Exécuteur","Dispeller":"Dissipatrice",
"Smiling Blade":"Lame souriante","Destroyer":"Destructeur","Avenger":"Vengeur","Honeyflower":"Fleur de miel","Divine Speed":"Vitesse divine",
"Grim Sword":"Epée sinistre","Earthbreaker":"Brise-terre","Nightingale":"Rossignol","Azure Blade":"Lame d'azur","Heavy Tempest":"Lourde tempête",
"Mercy Killer":"Coup de grâce","Guadian Blade":"Lame gardienne","Stonegod Sword":"Epée dieu-roc","Sword of Gain":"Epée du gain","Asian Phoenix":"Phénix d'Asie",
"Thunderlord":"Seigneur foudre","Oni's Fork":"Fourche d'oni","Kotetsu Sword":"Epée Kotetsu","Spark Sword":"Epée étincelle","Demonic Sword":"Epée démoniaque",
"Tonosama Sword":"Epée Tonosama","Zero Katana":"Katana zéro","Forsaken Light":"Lumière oubliée","Blade 3000":"Lame 3000","Five Stars":"Cinq étoiles",
"Dreams of Yore":"Rêves d'antan",
# --- haches ---
"Hatchet":"Hachette","Short Swing":"Court élan","Full Swing":"Plein élan","Over Swing":"Grand élan","Battle Axe":"Hache d'armes","Water Axe":"Hache d'eau",
"Flame Axe":"Hache de flamme","Wind Axe":"Hache de vent","Thunder Axe":"Hache foudre","Midnight Axe":"Hache de minuit","Razor Axe":"Hache rasoir",
"Bronze Axe":"Hache bronze","Cursed Axe":"Hache maudite","Earth Axe":"Hache de terre","Water God Axe":"Hache dieu-eau","Bloody Axe":"Hache sanglante",
"Bandit's Axe":"Hache de bandit","Charged Axe":"Hache chargée","Darkness Axe":"Hache ténèbres","Master's Axe":"Hache du chef","Papillon Axe":"Hache papillon",
"Devil's Axe":"Hache du diable","Handyman's Axe":"Hache bricoleur","Drought Axe":"Hache aride","Brook Axe":"Hache ruisseau","Vitality Axe":"Hache vitalité",
"Sinner's Axe":"Hache pécheur","Overloaded":"Surchargée","Darkness":"Ténèbres","Golden Mean":"Juste milieu","New Scythe":"Faux neuve",
"Sorcery's Axe":"Hache sorcière","Quake Axe":"Hache séisme","Dragon Axe":"Hache dragon","Splatter Axe":"Hache gore","Axe of Mobs":"Hache de foule",
"Vortex Axe":"Hache vortex","Alien Axe":"Hache alien","Artisan Axe":"Hache d'artisan","Fairy Axe":"Hache de fée","Dark God's Axe":"Hache dieu noir",
"Lumberjack":"Bûcheron","Desert Axe":"Hache du désert","Liquid Axe":"Hache liquide","Vibrant Blade":"Lame vibrante","Brute's Axe":"Hache de brute",
"Shock Axe":"Hache de choc","Black Axe":"Hache noire","Plasma Axe":"Hache plasma","Miracle Axe":"Hache miracle","Malice's Axe":"Hache de malice",
"Gaia's Axe":"Hache de Gaia","Vampire Axe":"Hache vampire","Crazy Axe":"Hache folle","Lightning Axe":"Hache d'éclair","Maestro Axe":"Hache maestro",
"Angel Axe":"Hache d'ange","Missing Axe":"Hache perdue","Golden Axe":"Hache d'or","Silver Axe":"Hache d'argent","Meteor Axe":"Hache météore",
"White Axe":"Hache blanche","Giant Hill":"Colline géante","Hell's Herald":"Héraut d'enfer","Key Axe":"Hache clé","Tri-Tips":"Tri-pointes",
"Thunder Dad":"Papa tonnerre","Watcher":"Guetteur",
# --- lances ---
"Bronze Spear":"Lance bronze","Iron Spear":"Lance de fer","Relief Lance":"Pique de répit","Water Spear":"Lance d'eau","Fire Spear":"Lance de feu",
"Wooden Spear":"Lance de bois","Electric Spear":"Lance d'éclair","Gold Spear":"Lance d'or","Spear of Spell":"Lance de sort","Bloody Lance":"Pique sanglante",
"Merman Spear":"Lance de triton","Lavaman Spear":"Lance de lave","Treeman Spear":"Lance d'arbre","Strormer Spear":"Lance d'orage","Berserk Spear":"Lance berserk",
"Fairy Spear":"Lance de fée","Fiend Spear":"Lance du malin","Copper Lance":"Pique de cuivre","Steel Spear":"Lance d'acier","River Spear":"Lance du fleuve",
"Flame Spear":"Lance de flamme","Globe Spear":"Lance globe","Blitz Spear":"Lance blitz","Knight Glaive":"Glaive du preux","Adamant Lance":"Pique d'adamant",
"Super Spear":"Super lance","Mage Spear":"Lance de mage","Dhampir Lance":"Pique dhampir","Fox Spear":"Lance renard","Blazing Spear":"Lance ardente",
"Treebeam Spear":"Lance de tronc","Flash Spear":"Lance flash","Insane Spear":"Lance démente","Erling's Spear":"Lance d'Erling","Demon Spear":"Lance démon",
"Sacred Spear":"Lance sacrée","Damascus Spear":"Lance de Damas","Happiness":"Bonheur","Aquaspear":"Aqualance","Volcanic Spear":"Lance volcan",
"Forest Spear":"Lance de forêt","Thunder Spear":"Lance foudre","Kaiser Glaive":"Glaive Kaiser","Golden Dragon":"Dragon d'or","Awful Spear":"Lance affreuse",
"Spear of Curse":"Lance maudite","Demon Lance":"Pique démon","Rivergod Spear":"Lance fluviale","Hellfire Spear":"Lance infernale","Primal Spear":"Lance primale",
"Plasma Lance":"Pique plasma","Madlance":"Pique folle","Spirit Lance":"Pique d'esprit","Ultimate Spear":"Lance ultime","Marine Spear":"Lance marine",
"Eternal Victor":"Eternel gagnant","Amazon Spear":"Lance amazone","Scarlet Autumn":"Automne rouge","Minerva":"Minerve",
# --- baguettes, sceptres, bâtons ---
"Cypress Wand":"Baguette cyprès","Iron Rod":"Sceptre de fer","Earth Wand":"Baguette terre","Water Wand":"Baguette d'eau","Fire Wand":"Baguette feu",
"Air Wand":"Baguette d'air","Electric Wand":"Baguette éclair","Ebony Wand":"Baguette ébène","Wand of Wisdom":"Baguette sage","Basho Wand":"Baguette Basho",
"Diabolic Wand":"Baguette diable","Earth Rod":"Sceptre terre","Rod of the Sea":"Sceptre marin","Inferno Wand":"Baguette enfer","Cedar Wand":"Baguette cèdre",
"Wand of Storms":"Baguette orage","Adian's Rod":"Sceptre d'Adian","Almighty Wand":"Omnipotente","Groovy Stick":"Bâton groovy","Starstorm Wand":"Orage d'étoiles",
"Spiral Wand":"Baguette spire","Silver Rod":"Sceptre argent","Muddy Rod":"Sceptre boueux","Bubble Rod":"Sceptre bulle","Flaming Rod":"Sceptre ardent",
"Dark Green Rod":"Sceptre vert","Bolt Rod":"Sceptre éclair","Nerd Staff":"Bâton d'intello","Revelation":"Révélation","Treasure Wand":"Baguette trésor",
"Witch's Wand":"Bâton sorcier","Gaia's Staff":"Bâton de Gaia","Ocean's Rod":"Sceptre d'océan","Firedrake Bone":"Os de drake","Rod of Gales":"Sceptre rafale",
"Stormlord Rod":"Sceptre orage","Apocalypse Rod":"Apocalypse","Moonstruck":"Lunatique","Cosmic Staff":"Bâton cosmique","Oak Staff":"Bâton de chêne",
"Crystal Rod":"Sceptre cristal","Earth Staff":"Bâton de terre","Cygnus Rod":"Sceptre Cygnus","Burning Brand":"Tison ardent","Hag's Wand":"Baguette mégère",
"Stun Rod":"Sceptre choc","Negation Wand":"Baguette néant","Wand of Truth":"Baguette vérité","Dharma Wand":"Bâton Dharma","Witch's Stick":"Bâton occulte",
"Ishtar Wand":"Baguette Ishtar","Commandments":"Commandements","Megiddo Wand":"Bâton Megiddo","Wand of Dreams":"Baguette songe","Awful Stun Rod":"Sceptre K.-O.",
"Shinto Dream":"Rêve shinto","Caduceus Rod":"Caducée","Staff of Truth":"Bâton de vérité","Expert Wand":"Bâton d'expert","Nautilus Wand":"Bâton Nautilus",
"Flaming Wand":"Baguette flamme","Dark History":"Histoire sombre","Rod of Pattern":"Sceptre à motif","Jester's Wand":"Marotte","Great Elite":"Grande élite",
# --- divers ---
"Midnight Helm?":"Heaume minuit ?","6 Side Blade":"Lame 6 côtés","7 Star Sword":"Epée 7 étoiles","8 Phase Sword":"Epée 8 phases","8 Key Guardian":"Gardien 8 clés","8 Wise Men":"8 sages",
"Ryu Book I":"Livre Ryu I","Ryu Book II":"Livre Ryu II","Ryu Book III":"Livre Ryu III","Ryu Book IV":"Livre Ryu IV","Ryu Book V":"Livre Ryu V",
"Ryu Book VI":"Livre Ryu VI","Ryu Book VII":"Livre Ryu VII","Ryu Book VIII":"Livre Ryu VIII",
}
NAMES.update({"Movie %02d"%i:"Vidéo %02d"%i for i in range(1,100)})
