# -*- coding: utf-8 -*-
"""Noms d'objets et d'armures (anglais -> francais), 15 caracteres max. Les noms propres absents d'ici restent tels quels."""
NAMES={
# --- objets ---
"Health Drink":"Boisson santé","Healing Potion":"Potion de soin","Healing Elixir":"Elixir de soin","Restorative":"Fortifiant","Resurrect":"Résurrection",
"Warrior Blood":"Sang guerrier","Knight Blood":"Sang chevalier","Hunter Blood":"Sang chasseur","Hermit Blood":"Sang d'ermite","Beast Blood":"Sang de bête","Wizard Blood":"Sang de sorcier",
"Well Water":"Eau de puits","Pure Water":"Eau pure","Burning Oil":"Huile ardente","Holy Sap":"Sève sacrée","Sports Drink":"Boisson sport","Cooked Bile":"Bile cuite",
"Mage's Soul":"Ame de mage","Artisan's Soul":"Ame d'artisan","Emperor's Soul":"Ame d'empereur","Noble Wine":"Vin noble","Risky Coffee":"Café risqué","Recovery Drink":"Boisson tonique",
"The Death":"La Mort","The Hanged Man":"Le Pendu","The Lovers":"Les Amoureux","The Moon":"La Lune","The Fool":"Le Mat","The Devil":"Le Diable",
"Warrior's Bane":"Fléau guerrier","Knight's Bane":"Fléau chevalier","Hunter's Bane":"Fléau chasseur","Hermit's Bane":"Fléau d'ermite","Beast's Bane":"Fléau de bête","Wizard's Bane":"Fléau sorcier",
"Stonebane":"Fléau de pierre","Waterbane":"Fléau d'eau","Firebane":"Fléau de feu","Treebane":"Fléau de bois","Lightbane":"Fléau d'éclair","Nightbane":"Fléau de nuit",
"Health Charm":"Charme de vie","Soul Charm":"Charme d'âme","Speed Charm":"Charme vitesse","Light Cross":"Croix légère","Hale Cross":"Croix vigueur","Divine Cross":"Croix divine",
"Golden Grunty":"Grunty d'or","Silver Grunty":"Grunty d'argent","Energy Sutras":"Sutras énergie","Spirit Sutras":"Sutras esprit",
"Fortune Wire":"Fil de fortune","Sprite Ocarina":"Ocarina esprit","Fairy's Orb":"Orbe de fée","Grunt Doll":"Poupée Grunt",
"Rainbow Card":"Carte irisée","Yellow Candy":"Bonbon jaune","Silver Scarab":"Scarabée argent","Ivory Barette":"Barrette ivoire","Scarlet Plate":"Plaque écarlate","Ruby Brooch":"Broche rubis",
"Crystal Stone":"Pierre cristal","Golem Parts":"Pièces de golem","Vessel of Sky":"Vase du ciel","Aromatic Grass":"Herbe parfumée","Chinese Food":"Plat chinois","Doll Amulet":"Amulette poupée",
"Magnolia Miso":"Miso magnolia","Scent of Gero":"Parfum de Gero","Boxed Lunch":"Bento","Field's Deed":"Titre de champ","Rouge Fragment":"Fragment rouge","Maiden's Plot":"Complot ingénu",
"Christmas Card":"Carte de Noël","Ice Bar":"Bâtonnet glacé",
"Golden Egg":"Oeuf d'or","Grunt Mints":"Menthe Grunt","Twilight Onion":"Oignon vespéral","Snaky Cactus":"Cactus serpent","Oh No Melon":"Melon Oh Non","White Cherry":"Cerise blanche",
"Root Vegetable":"Légume racine","La Pumpkin":"La Citrouille","Mushroom":"Champignon","Mandragora":"Mandragore","Piney Apple":"Pomme de pin","Immature Egg":"Oeuf immature",
"Bear Cat Egg":"Oeuf ours-chat","Invisible Egg":"Oeuf invisible","Bloody Egg":"Oeuf sanglant",
"Epitaph 00":"Epitaphe 00","Epitaph 01":"Epitaphe 01","Epitaph 02":"Epitaphe 02","Epitaph 03":"Epitaphe 03","Epitaph 04":"Epitaphe 04",
"Harald's Note":"Note de Harald","Harald's Note 2":"Note Harald 2","Grunty Flute":"Flûte Grunty","Imp's Pin":"Badge de lutin","Imp's Praises":"Eloges de lutin","Imp's Cross":"Croix de lutin","Imp's Crown":"Couronne lutin",
"Remedy":"Remède","Custom Remedy":"Remède maison","True Remedy":"Vrai remède","First Remedy":"Premier remède","Love Letter":"Lettre d'amour","The Twilight":"Le Crépuscule",
"Book of Law":"Livre de la loi","Book of Iron":"Livre de fer","Spark Blade":"Lame étincelle","Paper Cloak":"Cape de papier","Basin Shield":"Ecu bassine","Love Archery":"Arc d'amour",
"Plastic Sword":"Epée plastique","Absolute Book":"Livre absolu","Red Sword":"Epée rouge","Blue Boots":"Bottes bleues","Yellow Cap":"Bonnet jaune",
"Power Book":"Livre de force","Tolerance Book":"Livre tolérance","Insight Book":"Livre lucidité","Spiritual Book":"Livre spirituel","Graceful Book":"Livre de grâce","Swift Book":"Livre vélocité",
"Water Magic":"Magie de l'eau","Fire Magic":"Magie du feu","Wood Magic":"Magie du bois","Thunder Magic":"Magie foudre","Black Magic":"Magie noire",
"Earthlore":"Savoir terre","Sealore":"Savoir mer","Firelore":"Savoir feu","Forestlore":"Savoir forêt","Stormlore":"Savoir orage","Darklore":"Savoir ombre",
"Piros' Diary":"Journal Piros","Book of Ideals":"Livre d'idéal","Book of Ideas":"Livre d'idées",
# --- tete ---
"Steel Cap":"Casque d'acier","Cougar Bandana":"Bandana puma","Raccoon Earcap":"Toque de raton","Newt Necklace":"Collier triton","Scarab Earring":"Boucle scarabée","Thunder Torque":"Torque foudre",
"Bat Earrings":"Boucles de nuit","Gold Necklace":"Collier d'or","War Headband":"Bandeau martial","Imp Earrings":"Boucles lutin","Dragon Crest":"Cimier dragon","Fox Crest":"Cimier renard",
"Wolf Crest":"Cimier loup","Owl Crest":"Cimier hibou","Rat Crest":"Cimier rat","Raven Crest":"Cimier corbeau","Blade's Chain":"Chaîne de lame","Angel Chain":"Chaîne d'ange","Golden Crown":"Couronne d'or",
"Nomad's Hood":"Capuche nomade","Guard Cap":"Calot de garde","Hunter's Hood":"Capuche chasse","Ice Hunter Cap":"Toque polaire","Fire Dance Hat":"Chapeau flamme","Peasant's Cap":"Bonnet paysan",
"Lightning Cap":"Bonnet foudre","Darkness Hood":"Capuche sombre","Golden Turban":"Turban d'or","Infantry Cap":"Képi fantassin","Demon's Cap":"Bonnet démon","Eagle Hood":"Capuche d'aigle",
"Ice Tiger Hood":"Capuche tigre","Fire Lion Hood":"Capuche lion","Cave Bear Hood":"Capuche ours","Giraffe Hood":"Capuche girafe","Night Ape Hood":"Capuche singe","Matador Hood":"Capuche torero",
"Angel's Cap":"Bonnet d'ange","Fallen Pope":"Pape déchu","Head Gear":"Serre-tête","Face Guard":"Protège-visage","Mountain Helm":"Heaume alpin","Ice Helm":"Heaume glacé","Fire Helm":"Heaume de feu",
"Forester Helm":"Heaume sylvain","Stormlord Helm":"Heaume d'orage","Golden Helm":"Heaume d'or","Samurai Helm":"Heaume samouraï","Devil Helm":"Heaume diable",
"Rock Dragon":"Dragon de roc","Ice Dragon":"Dragon de glace","Fire Dragon":"Dragon de feu","Spirit Dragon":"Dragon esprit","Thunder Dragon":"Dragon foudre","Dark Dragon":"Dragon sombre",
"Mercenary Mask":"Masque soudard","Angel Helm":"Heaume d'ange","Usurper Helm":"Heaume félon","Goblin Cap":"Calot gobelin","Goblin Cap A":"Calot gobelin A","Goblin Cap S":"Calot gobelin S","Goblin Cap Z":"Calot gobelin Z",
"Ceramic Helm":"Heaume d'émail","Bent Glasses":"Lunettes pliées","Lady's Cap":"Bonnet de dame","Time Headband":"Bandeau temps","Cats Hat":"Chapeau chat",
# --- corps ---
"Leather Coat":"Manteau de cuir","Noble Cloak":"Cape noble","Hiking Gear":"Tenue de rando","Winter Coat":"Manteau d'hiver","Fireman's Coat":"Veste pompier","Lincoln Green":"Vert Lincoln",
"Thunder Cloak":"Cape de foudre","Demon Cloak":"Cape de démon","Saint Cross":"Croix sainte","Blood Suit":"Tenue de sang","Priest's Stole":"Etole de prêtre","Tribal Robes":"Robe tribale",
"Flowing Robes":"Robe fluide","Blazing Robes":"Robe ardente","Airy Robes":"Robe aérienne","Thunder Robes":"Robe de foudre","Magus Robes":"Robe de mage","Sublime Stole":"Etole sublime",
"Celestial Robe":"Robe céleste","Shadow Robes":"Robe d'ombre","Leather Armor":"Armure de cuir","Ring Mail":"Cotte annelée","Wyrm Hide":"Cuir de wyrm","Wyrm Scale":"Ecaille de wyrm",
"Firedrake Mail":"Cotte de drake","Holy Tree Mail":"Cotte sylvestre","Quakebeast Fur":"Fourrure séisme","Bone Armor":"Armure d'os","Linen Cuirass":"Cuirasse de lin","Bandit Mail":"Cotte de bandit",
"Jasper Hauberk":"Haubert jaspe","Frost Hauberk":"Haubert givre","Blaze Hauberk":"Haubert brasier","Spirit Hauberk":"Haubert esprit","Storm Hauberk":"Haubert orage","Ebony Hauberk":"Haubert ébène",
"Killer Hauberk":"Haubert tueur","Able Lamellar":"Lamellaire apte","Demon Mail":"Cotte de démon","Plate Armor":"Armure à plates","Grand Armor":"Grande armure","Frost Armor":"Armure de givre",
"Blaze Armor":"Armure brasier","Spirit Armor":"Armure esprit","Thunder Armor":"Armure foudre","Ebony Armor":"Armure d'ébène","Kris Armor":"Armure Kris","Masamune Armor":"Cotte Masamune",
"Armor of Hell":"Armure d'enfer","Earth Beast":"Bête de terre","Water Beast":"Bête d'eau","Fire Beast":"Bête de feu","Tree Beast":"Bête des bois","Thunder Beast":"Bête de foudre","Dark Beast":"Bête sombre",
"Paladin Mail":"Cotte paladin","Ragaraja Mail":"Cotte Ragaraja","Omega Guard":"Garde Oméga","Goblin Mail":"Cotte gobelin","Goblin Mail A":"Cotte gobelin A","Goblin Mail S":"Cotte gobelin S","Goblin Mail Z":"Cotte gobelin Z",
"Lady's Mail":"Cotte de dame","Time Sash":"Echarpe temps","Cats Mail":"Cotte chat",
# --- mains ---
"Wrist Band":"Serre-poignet","Silver Bracer":"Brassard argent","Fossil Bracer":"Brassard pierre","Frost Bracer":"Brassard givre","Fire Bracer":"Brassard feu","Air Bracer":"Brassard air",
"Storm Bracer":"Brassard orage","Jet Bracer":"Brassard jais","Protect Ring":"Anneau gardien","Able Ring":"Anneau apte","Geist Ring":"Anneau Geist","Rock Guard":"Garde de roc","Briny Guard":"Garde saline",
"Charred Guard":"Garde calcinée","Hunting Guard":"Garde chasseur","Ion Guard":"Garde ionique","Shadow Guard":"Garde d'ombre","War God Guard":"Garde martiale","Sacred Guard":"Garde sacrée","Uber Guard":"Garde ultime",
"Leather Gloves":"Gants de cuir","Silver Gloves":"Gants d'argent","Miner's Gloves":"Gants de mineur","Fishing Gloves":"Gants de pêche","Smith's Gloves":"Gants de forge","Forest Gloves":"Gants de forêt",
"Thunder Gloves":"Gants foudre","Gloves of Dark":"Gants d'ombre","Bouncer Gloves":"Gants de videur","Able Gloves":"Gants aptes","Drain Gloves":"Gants Drain","Hammer Gloves":"Gants marteau",
"Ocean Gloves":"Gants d'océan","Inferno Gloves":"Gants Inferno","Sonic Gloves":"Gants soniques","Shield Gloves":"Gants bouclier","Jet Gloves":"Gants de jais","Bladed Gloves":"Gants à lames",
"Divine Gloves":"Gants divins","Hades Gloves":"Gants d'Hadès","Rusted Hands":"Mains rouillées","Silver Hands":"Mains d'argent","Hands of Earth":"Mains de terre","Hands of Water":"Mains d'eau",
"Hands of Fire":"Mains de feu","Hands of Wood":"Mains de bois","Hands of Storm":"Mains d'orage","Hands of Ebony":"Mains d'ébène","Hands of Ronin":"Mains de ronin","Able Hands":"Mains aptes",
"Cursed Hands":"Mains maudites","Gaia Hands":"Mains de Gaia","Aqua hands":"Mains Aqua","Fire Hands":"Mains ardentes","Sprite Hands":"Mains d'esprit","Electric Hands":"Mains électro",
"Midnight Hands":"Mains de minuit","Master's Hands":"Mains de maître","Divine Hands":"Mains divines","Demon's Hands":"Mains de démon","Goblin Gloves":"Gants gobelin","Goblingloves A":"Gants gobelin A",
"Goblingloves S":"Gants gobelin S","Goblingloves Z":"Gants gobelin Z","Lady's Gloves":"Gants de dame","Time Bracer":"Brassard temps","Cats Gloves":"Gants chat",
# --- pieds ---
"Sandals":"Sandales","Leg Mail":"Jambières","Ceramic Anklet":"Chevillère grès","Frost Anklet":"Chevillère gel","Iron Anklet":"Chevillère fer","Oak Anklet":"Chevillère bois",
"Thunder Anklet":"Chevill. foudre","Ninja Anklet":"Chevill. ninja","Greave Sticker":"Grève collante","Ivory Greaves":"Grèves d'ivoire","Devil Greaves":"Grèves diable","Stone Greaves":"Grèves pierre",
"Sea Greaves":"Grèves marines","Lava Greaves":"Grèves de lave","Oaken Greaves":"Grèves de chêne","Storm Greaves":"Grèves d'orage","Ebony Greaves":"Grèves d'ébène","Alert Greaves":"Grèves d'alerte",
"Greaves of Awe":"Grèves d'effroi","Denial Greaves":"Grèves du refus","Safety Shoes":"Souliers sûrs","Jungle Boots":"Bottes jungle","Mountain Boots":"Bottes alpines","Snow Panther":"Panthère neiges",
"Fire Lizard":"Lézard de feu","Ranger's Boots":"Bottes ranger","Thunder Boots":"Bottes foudre","Ninja Socks":"Tabi ninja","Deluxe Boots":"Bottes de luxe","Powered Boots":"Bottes motrices",
"Osorezan Socks":"Tabi Osorezan","Stone Solleret":"Soleret pierre","Frost Solleret":"Soleret givre","Blaze Solleret":"Soleret brasier","Oaken Solleret":"Soleret chêne","Storm Solleret":"Soleret orage",
"Night Solleret":"Soleret nuit","Guard Solleret":"Soleret garde","Magus Solleret":"Soleret mage","Ultra Solleret":"Soleret ultra","Used Greaves":"Grèves usées","Leather Legs":"Jambes de cuir",
"Mountain Guard":"Garde montagne","Aqua Guard":"Garde Aqua","Flare Guard":"Garde flamme","Green Guard":"Garde verte","Electric Guard":"Garde électro","Benkei's Guard":"Garde de Benkei",
"Spiked Guard":"Garde à pointes","Rare Greaves":"Grèves rares","Magic Leg Mail":"Jambières magie","Imp's Leg Mail":"Jambières lutin","Ice Leg Mail":"Jambières glace","Flame Leg Mail":"Jambières feu",
"Oaken Leg Mail":"Jambières chêne","Storm Leg Mail":"Jambières orage","Ebony Leg Mail":"Jambières ébène","Lone Leg Mail":"Jambières solo","Alien Leg Mail":"Jambières alien","Ultra Leg Mail":"Jambières ultra",
"Goblin Boots":"Botte gobelin","Goblin Boots A":"Botte gobelin A","Goblin Boots S":"Botte gobelin S","Goblin Boots Z":"Botte gobelin Z","Lucky Shoes":"Souliers chance","Lady's Shoes":"Soulier de dame",
"Time Sandals":"Sandales temps","Cats Boots":"Bottes chat",
}
